import { Calculator, Disc, Fuel, Wrench } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const automotiveConverters: Record<string, ConverterMeta> = {
  "fuel-efficiency": {
    id: "fuel-efficiency",
    slug: "fuel-efficiency",
    category: "automotive",
    subcategory: "fuel",
    keywords: [
      "fuel",
      "efficiency",
      "consumption",
      "L/100km",
      "km/L",
      "MPG",
      "gas",
      "mileage",
      "trip cost",
      "annual cost",
      "economy",
    ],
    icon: Fuel,
    featured: false,
  },
  "tire-sizing": {
    id: "tire-sizing",
    slug: "tire-sizing",
    category: "automotive",
    subcategory: "tires",
    keywords: [
      "tire",
      "tyre",
      "size",
      "dimension",
      "diameter",
      "speedometer",
      "205/55R16",
      "aspect ratio",
      "rim",
      "wheel",
      "load index",
      "speed rating",
      "comparison",
    ],
    icon: Disc,
    featured: false,
  },
  "maintenance-intervals": {
    id: "maintenance-intervals",
    slug: "maintenance-intervals",
    category: "automotive",
    subcategory: "maintenance",
    keywords: [
      "maintenance",
      "service",
      "intervals",
      "oil change",
      "MFK",
      "inspection",
      "schedule",
      "reminder",
      "service due",
      "km",
      "timing belt",
    ],
    icon: Wrench,
    featured: false,
  },
  "vehicle-financing": {
    id: "vehicle-financing",
    slug: "vehicle-financing",
    category: "automotive",
    subcategory: "financing",
    keywords: [
      "financing",
      "loan",
      "lease",
      "payment",
      "auto loan",
      "car loan",
      "interest",
      "APR",
      "CHF",
      "EUR",
      "amortization",
      "residual value",
    ],
    icon: Calculator,
    featured: false,
  },
};
