import { Apple, Scale, Utensils, Wallet } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const cookingConverters: Record<string, ConverterMeta> = {
  "cooking-units": {
    id: "cooking-units",
    slug: "cooking-units",
    category: "cooking",
    subcategory: "units",
    keywords: [
      "cooking",
      "units",
      "convert",
      "cups",
      "tablespoon",
      "teaspoon",
      "ml",
      "grams",
      "liters",
      "ounces",
      "volume",
      "weight",
      "metric",
      "imperial",
      "kitchen",
      "baking",
      "density",
      "flour",
      "sugar",
    ],
    icon: Scale,
    featured: true,
  },
  "recipe-scaler": {
    id: "recipe-scaler",
    slug: "recipe-scaler",
    category: "cooking",
    subcategory: "recipes",
    keywords: [
      "recipe",
      "scale",
      "scaler",
      "servings",
      "multiply",
      "divide",
      "cooking",
      "baking",
      "portion",
      "adjust",
      "double",
      "half",
      "ingredients",
      "kitchen",
      "conversion",
    ],
    icon: Utensils,
    featured: true,
  },
  "food-cost": {
    id: "food-cost",
    slug: "food-cost",
    category: "cooking",
    subcategory: "cost",
    keywords: [
      "food",
      "cost",
      "recipe",
      "price",
      "ingredient",
      "budget",
      "cooking",
      "meal",
      "serving",
      "expense",
      "kitchen",
      "grocery",
      "calculation",
      "per serving",
      "total cost",
    ],
    icon: Wallet,
    featured: false,
  },
  "nutrition-calculator": {
    id: "nutrition-calculator",
    slug: "nutrition-calculator",
    category: "cooking",
    subcategory: "nutrition",
    keywords: [
      "nutrition",
      "calories",
      "protein",
      "carbs",
      "fat",
      "macro",
      "food",
      "diet",
      "meal",
      "calculator",
      "health",
      "fitness",
      "tracking",
      "fiber",
      "sodium",
      "cholesterol",
      "vitamins",
    ],
    icon: Apple,
    featured: true,
  },
};
