import { ArrowRightLeft, Cpu, Hash, Wallet } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const cryptoConverters: Record<string, ConverterMeta> = {
  "exchange-rate": {
    id: "exchange-rate",
    slug: "exchange-rate",
    category: "crypto",
    subcategory: "exchange",
    keywords: [
      "crypto",
      "exchange",
      "rate",
      "bitcoin",
      "ethereum",
      "chf",
      "eur",
      "usd",
      "convert",
      "price",
      "btc",
      "eth",
      "ltc",
      "xrp",
      "doge",
      "ada",
      "cryptocurrency",
    ],
    icon: ArrowRightLeft,
    featured: true,
  },
  "hash-calculator": {
    id: "hash-calculator",
    slug: "hash",
    category: "crypto",
    subcategory: "hashing",
    keywords: [
      "hash",
      "md5",
      "sha1",
      "sha256",
      "sha512",
      "checksum",
      "digest",
      "crypto",
      "security",
    ],
    icon: Hash,
    featured: true,
  },
  "wallet-validator": {
    id: "wallet-validator",
    slug: "wallet-validator",
    category: "crypto",
    subcategory: "wallet",
    keywords: [
      "wallet",
      "address",
      "bitcoin",
      "ethereum",
      "validate",
      "btc",
      "eth",
      "ltc",
      "litecoin",
      "crypto",
      "blockchain",
    ],
    icon: Wallet,
    featured: false,
  },
  "mining-calculator": {
    id: "mining-calculator",
    slug: "mining",
    category: "crypto",
    subcategory: "mining",
    keywords: [
      "mining",
      "bitcoin",
      "profitability",
      "hashrate",
      "electricity",
      "roi",
      "asic",
      "crypto",
      "btc",
      "miner",
      "profit",
      "antminer",
      "whatsminer",
      "s19",
      "m30s",
    ],
    icon: Cpu,
    featured: false,
  },
};
