import { Calendar, Clock } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const datetimeConverters: Record<string, ConverterMeta> = {
  age: {
    id: "age",
    slug: "age",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["age", "birthday", "years", "months", "days", "birth date"],
    icon: Calendar,
    featured: true,
  },
  date: {
    id: "date",
    slug: "date",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["date", "add", "subtract", "days", "weeks", "months", "years"],
    icon: Calendar,
    featured: false,
  },
  time: {
    id: "time",
    slug: "time",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["time", "add", "subtract", "hours", "minutes", "seconds"],
    icon: Calendar,
    featured: false,
  },
  hours: {
    id: "hours",
    slug: "hours",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["hours", "time", "duration", "work hours", "between"],
    icon: Calendar,
    featured: false,
  },
  "time-duration": {
    id: "time-duration",
    slug: "time-duration",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["duration", "time", "between", "difference", "elapsed"],
    icon: Calendar,
    featured: false,
  },
  "time-zone": {
    id: "time-zone",
    slug: "time-zone",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["time zone", "convert", "utc", "gmt", "timezone"],
    icon: Calendar,
    featured: false,
  },
  "day-counter": {
    id: "day-counter",
    slug: "day-counter",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["days", "count", "between", "until", "countdown"],
    icon: Calendar,
    featured: false,
  },
  "day-of-week": {
    id: "day-of-week",
    slug: "day-of-week",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["day", "week", "monday", "tuesday", "date", "weekday"],
    icon: Calendar,
    featured: false,
  },
  "duration-converter": {
    id: "duration-converter",
    slug: "duration-converter",
    category: "datetime",
    subcategory: "date-time",
    keywords: [
      "duration",
      "time",
      "convert",
      "seconds",
      "minutes",
      "hours",
      "days",
      "weeks",
      "months",
      "years",
    ],
    icon: Clock,
    featured: false,
  },
};
