import { Activity, ArrowRightLeft, Box, Droplets, Pilcrow, Ruler } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const engineeringConverters: Record<string, ConverterMeta> = {
  "stress-strain": {
    id: "stress-strain",
    slug: "stress-strain",
    category: "engineering",
    subcategory: "materials",
    keywords: [
      "stress",
      "strain",
      "Young's modulus",
      "elasticity",
      "safety factor",
      "material properties",
    ],
    icon: Activity,
    featured: true,
  },
  "moment-of-inertia": {
    id: "moment-of-inertia",
    slug: "moment-of-inertia",
    category: "engineering",
    subcategory: "structural",
    keywords: [
      "moment of inertia",
      "second moment",
      "area",
      "cross-section",
      "I-beam",
      "parallel axis",
      "radius of gyration",
    ],
    icon: Box,
    featured: true,
  },
  "beam-deflection": {
    id: "beam-deflection",
    slug: "beam-deflection",
    category: "engineering",
    subcategory: "structural",
    keywords: [
      "beam deflection",
      "shear",
      "moment",
      "bending",
      "structural analysis",
      "cantilever",
      "simply supported",
      "fixed",
    ],
    icon: Ruler,
    featured: true,
  },
  "column-buckling": {
    id: "column-buckling",
    slug: "column-buckling",
    category: "engineering",
    subcategory: "structural",
    keywords: [
      "column buckling",
      "Euler",
      "critical load",
      "slenderness",
      "AISC",
      "compression",
      "stability",
    ],
    icon: Pilcrow,
    featured: false,
  },
  "pipe-flow": {
    id: "pipe-flow",
    slug: "pipe-flow",
    category: "engineering",
    subcategory: "hydraulics",
    keywords: [
      "pipe flow",
      "pressure drop",
      "Darcy-Weisbach",
      "friction factor",
      "Reynolds number",
      "Colebrook-White",
      "head loss",
    ],
    icon: Droplets,
    featured: false,
  },
  "engineering-unit-converter": {
    id: "engineering-unit-converter",
    slug: "engineering-unit-converter",
    category: "engineering",
    subcategory: "conversion",
    keywords: [
      "unit converter",
      "force",
      "pressure",
      "stress",
      "torque",
      "density",
      "engineering units",
      "NIST",
    ],
    icon: ArrowRightLeft,
    featured: false,
  },
};
