import { DollarSign } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const financeConverters: Record<string, ConverterMeta> = {
  mortgage: {
    id: "mortgage",
    slug: "mortgage",
    category: "finance",
    subcategory: "loans",
    keywords: [
      "mortgage",
      "home loan",
      "amortization",
      "monthly payment",
      "interest rate",
      "down payment",
    ],
    icon: DollarSign,
    featured: true,
  },
  "compound-interest": {
    id: "compound-interest",
    slug: "compound-interest",
    category: "finance",
    subcategory: "interest",
    keywords: ["compound interest", "investment", "savings", "growth", "contributions"],
    icon: DollarSign,
    featured: true,
  },
  loan: {
    id: "loan",
    slug: "loan",
    category: "finance",
    subcategory: "loans",
    keywords: ["loan", "personal loan", "auto loan", "monthly payment", "amortization"],
    icon: DollarSign,
    featured: false,
  },
  retirement: {
    id: "retirement",
    slug: "retirement",
    category: "finance",
    subcategory: "investments",
    keywords: ["retirement", "401k", "pension", "savings", "social security", "investment"],
    icon: DollarSign,
    featured: true,
  },
  tip: {
    id: "tip",
    slug: "tip",
    category: "finance",
    subcategory: "everyday",
    keywords: ["tip", "gratuity", "restaurant", "bill split", "service"],
    icon: DollarSign,
    featured: false,
  },
  "savings-goal": {
    id: "savings-goal",
    slug: "savings-goal",
    category: "finance",
    subcategory: "investments",
    keywords: ["savings", "goal", "investment", "planning", "future"],
    icon: DollarSign,
    featured: false,
  },
  inflation: {
    id: "inflation",
    slug: "inflation",
    category: "finance",
    subcategory: "investments",
    keywords: ["inflation", "purchasing power", "CPI", "cost of living"],
    icon: DollarSign,
    featured: false,
  },
  roi: {
    id: "roi",
    slug: "roi",
    category: "finance",
    subcategory: "investments",
    keywords: ["roi", "return on investment", "profit", "investment return"],
    icon: DollarSign,
    featured: false,
  },
  "break-even": {
    id: "break-even",
    slug: "break-even",
    category: "finance",
    subcategory: "business",
    keywords: ["break even", "business", "costs", "revenue", "profit"],
    icon: DollarSign,
    featured: false,
  },
  "profit-margin": {
    id: "profit-margin",
    slug: "profit-margin",
    category: "finance",
    subcategory: "business",
    keywords: ["profit margin", "gross margin", "net margin", "markup"],
    icon: DollarSign,
    featured: false,
  },
  discount: {
    id: "discount",
    slug: "discount",
    category: "finance",
    subcategory: "everyday",
    keywords: ["discount", "sale", "percent off", "savings", "price"],
    icon: DollarSign,
    featured: false,
  },
  currency: {
    id: "currency",
    slug: "currency",
    category: "finance",
    subcategory: "conversion",
    keywords: ["currency", "exchange rate", "forex", "money", "conversion"],
    icon: DollarSign,
    featured: true,
  },

  // Loans
  "auto-loan": {
    id: "auto-loan",
    slug: "auto-loan",
    category: "finance",
    subcategory: "loans",
    keywords: ["auto loan", "car loan", "vehicle financing", "car payment"],
    icon: DollarSign,
    featured: false,
  },
  "personal-loan": {
    id: "personal-loan",
    slug: "personal-loan",
    category: "finance",
    subcategory: "loans",
    keywords: ["personal loan", "loan payment", "APR", "origination fee"],
    icon: DollarSign,
    featured: false,
  },
  "student-loan": {
    id: "student-loan",
    slug: "student-loan",
    category: "finance",
    subcategory: "loans",
    keywords: ["student loan", "education loan", "grace period", "college"],
    icon: DollarSign,
    featured: false,
  },
  "home-equity": {
    id: "home-equity",
    slug: "home-equity",
    category: "finance",
    subcategory: "loans",
    keywords: ["home equity", "HELOC", "second mortgage", "equity loan"],
    icon: DollarSign,
    featured: false,
  },
  "debt-payoff": {
    id: "debt-payoff",
    slug: "debt-payoff",
    category: "finance",
    subcategory: "payments",
    keywords: ["debt payoff", "extra payments", "debt free", "pay off debt"],
    icon: DollarSign,
    featured: false,
  },
  "credit-card": {
    id: "credit-card",
    slug: "credit-card",
    category: "finance",
    subcategory: "payments",
    keywords: ["credit card", "minimum payment", "card debt", "payoff"],
    icon: DollarSign,
    featured: false,
  },
  "down-payment": {
    id: "down-payment",
    slug: "down-payment",
    category: "finance",
    subcategory: "payments",
    keywords: ["down payment", "savings goal", "home savings", "house deposit"],
    icon: DollarSign,
    featured: false,
  },
  "retirement-401k": {
    id: "retirement-401k",
    slug: "retirement-401k",
    category: "finance",
    subcategory: "investments",
    keywords: ["401k", "retirement", "employer match", "retirement savings"],
    icon: DollarSign,
    featured: false,
  },
  "ira-calculator": {
    id: "ira-calculator",
    slug: "ira-calculator",
    category: "finance",
    subcategory: "investments",
    keywords: ["IRA", "Roth IRA", "Traditional IRA", "retirement account"],
    icon: DollarSign,
    featured: false,
  },
  "bond-calculator": {
    id: "bond-calculator",
    slug: "bond-calculator",
    category: "finance",
    subcategory: "investments",
    keywords: ["bond", "yield", "coupon", "fixed income"],
    icon: DollarSign,
    featured: false,
  },
  "annuity-calculator": {
    id: "annuity-calculator",
    slug: "annuity-calculator",
    category: "finance",
    subcategory: "investments",
    keywords: ["annuity", "retirement income", "periodic payment", "pension"],
    icon: DollarSign,
    featured: false,
  },
  "debt-snowball-avalanche": {
    id: "debt-snowball-avalanche",
    slug: "debt-snowball-avalanche",
    category: "finance",
    subcategory: "payments",
    keywords: ["debt", "snowball", "avalanche", "debt payoff", "payoff plan"],
    icon: DollarSign,
    featured: true,
  },
  "income-tax": {
    id: "income-tax",
    slug: "income-tax",
    category: "finance",
    subcategory: "payments",
    keywords: ["income tax", "tax", "progressive tax", "brackets", "calculator"],
    icon: DollarSign,
    featured: true,
  },
};
