import { Heart } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const healthConverters: Record<string, ConverterMeta> = {
  bmi: {
    id: "bmi",
    slug: "bmi",
    category: "health",
    keywords: ["bmi", "body mass index", "weight", "health", "obesity"],
    icon: Heart,
    featured: true,
  },
  corpulence: {
    id: "corpulence",
    slug: "corpulence",
    category: "health",
    keywords: ["corpulence", "ponderal index", "body composition", "weight"],
    icon: Heart,
    featured: false,
  },
  "body-fat": {
    id: "body-fat",
    slug: "body-fat",
    category: "health",
    subcategory: "body",
    keywords: ["body fat", "body composition", "navy method", "fat percentage"],
    icon: Heart,
    featured: false,
  },
  "lean-body-mass": {
    id: "lean-body-mass",
    slug: "lean-body-mass",
    category: "health",
    subcategory: "body",
    keywords: ["lean body mass", "lbm", "fat-free mass", "muscle mass"],
    icon: Heart,
    featured: false,
  },
  "body-surface-area": {
    id: "body-surface-area",
    slug: "body-surface-area",
    category: "health",
    subcategory: "body",
    keywords: ["body surface area", "bsa", "du bois", "mosteller"],
    icon: Heart,
    featured: false,
  },
  "ideal-weight": {
    id: "ideal-weight",
    slug: "ideal-weight",
    category: "health",
    subcategory: "body",
    keywords: ["ideal weight", "ideal body weight", "ibw", "healthy weight"],
    icon: Heart,
    featured: false,
  },
  "bmr-calculator": {
    id: "bmr-calculator",
    slug: "bmr-calculator",
    category: "health",
    subcategory: "nutrition",
    keywords: ["bmr", "basal metabolic rate", "metabolism", "calories"],
    icon: Heart,
    featured: true,
  },
  "tdee-calculator": {
    id: "tdee-calculator",
    slug: "tdee-calculator",
    category: "health",
    subcategory: "nutrition",
    keywords: ["tdee", "total daily energy expenditure", "calories", "activity"],
    icon: Heart,
    featured: false,
  },
  "calorie-calculator": {
    id: "calorie-calculator",
    slug: "calorie-calculator",
    category: "health",
    subcategory: "nutrition",
    keywords: ["calories", "weight loss", "weight gain", "diet", "macros"],
    icon: Heart,
    featured: true,
  },
  "calories-burned": {
    id: "calories-burned",
    slug: "calories-burned",
    category: "health",
    subcategory: "fitness",
    keywords: ["calories burned", "exercise", "activity", "met", "workout"],
    icon: Heart,
    featured: false,
  },
  "target-heart-rate": {
    id: "target-heart-rate",
    slug: "target-heart-rate",
    category: "health",
    subcategory: "fitness",
    keywords: ["heart rate", "cardio zones", "fat burning", "exercise intensity"],
    icon: Heart,
    featured: false,
  },
  "one-rep-max": {
    id: "one-rep-max",
    slug: "one-rep-max",
    category: "health",
    subcategory: "fitness",
    keywords: ["one rep max", "1rm", "strength", "weightlifting", "powerlifting"],
    icon: Heart,
    featured: false,
  },
  "pace-calculator": {
    id: "pace-calculator",
    slug: "pace-calculator",
    category: "health",
    subcategory: "fitness",
    keywords: ["pace", "running", "speed", "marathon", "race time"],
    icon: Heart,
    featured: false,
  },
  "macro-calculator": {
    id: "macro-calculator",
    slug: "macro-calculator",
    category: "health",
    subcategory: "nutrition",
    keywords: ["macros", "protein", "carbs", "fat", "nutrition", "diet"],
    icon: Heart,
    featured: false,
  },
  "protein-calculator": {
    id: "protein-calculator",
    slug: "protein-calculator",
    category: "health",
    subcategory: "nutrition",
    keywords: ["protein", "nutrition", "muscle", "diet", "amino acids"],
    icon: Heart,
    featured: false,
  },
  "carb-calculator": {
    id: "carb-calculator",
    slug: "carb-calculator",
    category: "health",
    subcategory: "nutrition",
    keywords: ["carbs", "carbohydrates", "nutrition", "diet", "fiber"],
    icon: Heart,
    featured: false,
  },
  "fat-intake": {
    id: "fat-intake",
    slug: "fat-intake",
    category: "health",
    subcategory: "nutrition",
    keywords: ["fat", "lipids", "nutrition", "omega-3", "saturated fat"],
    icon: Heart,
    featured: false,
  },
  "water-intake": {
    id: "water-intake",
    slug: "water-intake",
    category: "health",
    subcategory: "nutrition",
    keywords: ["water", "hydration", "fluid intake", "dehydration"],
    icon: Heart,
    featured: false,
  },
  "body-type": {
    id: "body-type",
    slug: "body-type",
    category: "health",
    subcategory: "body",
    keywords: ["body type", "somatotype", "ectomorph", "mesomorph", "endomorph"],
    icon: Heart,
    featured: false,
  },
  "healthy-weight": {
    id: "healthy-weight",
    slug: "healthy-weight",
    category: "health",
    subcategory: "body",
    keywords: ["healthy weight", "ideal weight", "weight range", "BMI"],
    icon: Heart,
    featured: false,
  },
  "army-body-fat": {
    id: "army-body-fat",
    slug: "army-body-fat",
    category: "health",
    subcategory: "body",
    keywords: ["army", "body fat", "military", "tape test", "fitness standards"],
    icon: Heart,
    featured: false,
  },
  "bac-calculator": {
    id: "bac-calculator",
    slug: "bac-calculator",
    category: "health",
    subcategory: "medical",
    keywords: ["blood alcohol", "BAC", "drinking", "alcohol", "impairment"],
    icon: Heart,
    featured: false,
  },
  "gfr-calculator": {
    id: "gfr-calculator",
    slug: "gfr-calculator",
    category: "health",
    subcategory: "medical",
    keywords: ["GFR", "kidney", "creatinine", "renal function", "CKD"],
    icon: Heart,
    featured: false,
  },
  "sleep-calculator": {
    id: "sleep-calculator",
    slug: "sleep-calculator",
    category: "health",
    subcategory: "medical",
    keywords: ["sleep", "sleep cycle", "bedtime", "wake time", "REM"],
    icon: Heart,
    featured: false,
  },
  "due-date": {
    id: "due-date",
    slug: "due-date",
    category: "health",
    subcategory: "pregnancy",
    keywords: ["due date", "pregnancy", "conception", "trimester", "EDD"],
    icon: Heart,
    featured: false,
  },
  "ovulation-calculator": {
    id: "ovulation-calculator",
    slug: "ovulation-calculator",
    category: "health",
    subcategory: "pregnancy",
    keywords: ["ovulation", "fertility", "fertile window", "conception", "cycle"],
    icon: Heart,
    featured: false,
  },
  "period-calculator": {
    id: "period-calculator",
    slug: "period-calculator",
    category: "health",
    subcategory: "pregnancy",
    keywords: ["period", "menstrual cycle", "PMS", "menstruation"],
    icon: Heart,
    featured: false,
  },
  "pregnancy-weight-gain": {
    id: "pregnancy-weight-gain",
    slug: "pregnancy-weight-gain",
    category: "health",
    subcategory: "pregnancy",
    keywords: ["pregnancy", "weight gain", "prenatal", "trimester", "BMI"],
    icon: Heart,
    featured: false,
  },
};
