import { Cpu, DollarSign, HardDrive, Receipt, Server } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const infrastructureConverters: Record<string, ConverterMeta> = {
  "vm-storage-calculator": {
    id: "vm-storage-calculator",
    slug: "vm-storage-calculator",
    category: "infrastructure",
    subcategory: "virtualization",
    keywords: [
      "vm",
      "virtual machine",
      "storage",
      "vmware",
      "vsphere",
      "esx",
      "esxi",
      "capacity",
      "provisioning",
      "thin provisioning",
      "datastore",
      "swap",
      "snapshot",
    ],
    icon: HardDrive,
    featured: true,
  },
  "k8s-capacity-calculator": {
    id: "k8s-capacity-calculator",
    slug: "k8s-capacity-calculator",
    category: "infrastructure",
    subcategory: "containers",
    keywords: [
      "kubernetes",
      "k8s",
      "capacity",
      "node sizing",
      "cluster",
      "pods",
      "containers",
      "resources",
      "cpu",
      "memory",
      "scheduling",
      "allocatable",
      "utilization",
    ],
    icon: Server,
    featured: true,
  },
  "server-virtualization-calculator": {
    id: "server-virtualization-calculator",
    slug: "server-virtualization-calculator",
    category: "infrastructure",
    subcategory: "virtualization",
    keywords: [
      "vmware",
      "esx",
      "esxi",
      "host",
      "sizing",
      "virtualization",
      "n+1",
      "ha",
      "high availability",
      "capacity",
      "vcpu",
      "consolidation",
    ],
    icon: Server,
    featured: true,
  },
  "vmware-licensing-calculator": {
    id: "vmware-licensing-calculator",
    slug: "vmware-licensing-calculator",
    category: "infrastructure",
    subcategory: "vmware",
    keywords: [
      "vmware",
      "vcf",
      "vvf",
      "licensing",
      "subscription",
      "vsan",
      "cost",
      "broadcom",
      "cloud foundation",
      "vsphere foundation",
    ],
    icon: Receipt,
    featured: true,
  },
  "virtualization-cost": {
    id: "virtualization-cost",
    slug: "virtualization-cost",
    category: "infrastructure",
    subcategory: "cost",
    keywords: ["tco", "cost", "virtualization", "capex", "opex", "datacenter"],
    icon: DollarSign,
    featured: true,
  },
  "hyperv-consolidation": {
    id: "hyperv-consolidation",
    slug: "hyperv-consolidation",
    category: "infrastructure",
    subcategory: "hyperv",
    keywords: [
      "hyper-v",
      "hyperv",
      "microsoft",
      "consolidation",
      "virtualization",
      "windows server",
      "licensing",
      "datacenter",
      "standard",
      "ha",
      "high availability",
      "replica",
      "capacity",
    ],
    icon: Server,
    featured: true,
  },
  "windows-licensing": {
    id: "windows-licensing",
    slug: "windows-licensing",
    category: "infrastructure",
    subcategory: "hyperv",
    keywords: [
      "windows server",
      "licensing",
      "datacenter",
      "standard",
      "microsoft",
      "cost",
      "core licensing",
      "break-even",
      "comparison",
    ],
    icon: Receipt,
    featured: true,
  },
  "hypervisor-comparison": {
    id: "hypervisor-comparison",
    slug: "hypervisor-comparison",
    category: "infrastructure",
    subcategory: "cost",
    keywords: [
      "hypervisor",
      "comparison",
      "vmware",
      "hyper-v",
      "proxmox",
      "xcp-ng",
      "tco",
      "cost",
      "features",
      "sizing",
      "licensing",
      "virtualization",
      "multi-platform",
    ],
    icon: Server,
    featured: true,
  },
  "cpu-comparison-calculator": {
    id: "cpu-comparison-calculator",
    slug: "cpu-comparison-calculator",
    category: "infrastructure",
    subcategory: "cpu",
    keywords: [
      "cpu",
      "processor",
      "specint",
      "spec",
      "benchmark",
      "performance",
      "intel",
      "amd",
      "epyc",
      "xeon",
      "arm",
      "ampere",
      "altra",
      "comparison",
      "per-core",
      "per-watt",
      "sizing",
    ],
    icon: Cpu,
    featured: true,
  },
  "server-refresh-calculator": {
    id: "server-refresh-calculator",
    slug: "server-refresh-calculator",
    category: "infrastructure",
    subcategory: "cpu",
    keywords: [
      "server",
      "refresh",
      "fleet",
      "migration",
      "upgrade",
      "specint",
      "cpu",
      "performance",
      "headroom",
      "power",
      "tco",
      "datacenter",
      "rack",
      "socket",
    ],
    icon: Server,
    featured: true,
  },
};
