import { Calculator } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const mathConverters: Record<string, ConverterMeta> = {
  // Basic
  "basic-calculator": {
    id: "basic-calculator",
    slug: "basic-calculator",
    category: "math",
    subcategory: "basic",
    keywords: ["calculator", "arithmetic", "math", "add", "subtract", "multiply", "divide"],
    icon: Calculator,
    featured: true,
  },
  "fraction-calculator": {
    id: "fraction-calculator",
    slug: "fraction-calculator",
    category: "math",
    subcategory: "basic",
    keywords: ["fraction", "numerator", "denominator", "simplify", "mixed number"],
    icon: Calculator,
    featured: false,
  },
  "percentage-calculator": {
    id: "percentage-calculator",
    slug: "percentage-calculator",
    category: "math",
    subcategory: "basic",
    keywords: ["percentage", "percent", "percent change", "percent difference"],
    icon: Calculator,
    featured: true,
  },
  "percent-error": {
    id: "percent-error",
    slug: "percent-error-calculator",
    category: "math",
    subcategory: "basic",
    keywords: ["percent error", "error", "experimental", "actual", "accuracy"],
    icon: Calculator,
    featured: false,
  },
  "rounding-calculator": {
    id: "rounding-calculator",
    slug: "rounding-calculator",
    category: "math",
    subcategory: "basic",
    keywords: ["round", "ceil", "floor", "truncate", "significant figures"],
    icon: Calculator,
    featured: false,
  },
  "average-calculator": {
    id: "average-calculator",
    slug: "average-calculator",
    category: "math",
    subcategory: "basic",
    keywords: ["average", "mean", "median", "mode", "weighted average"],
    icon: Calculator,
    featured: false,
  },
  "long-division": {
    id: "long-division",
    slug: "long-division",
    category: "math",
    subcategory: "basic",
    keywords: ["long division", "divide", "remainder", "quotient", "step by step"],
    icon: Calculator,
    featured: false,
  },

  // Algebra
  "exponent-calculator": {
    id: "exponent-calculator",
    slug: "exponent-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["exponent", "power", "base", "exponential", "squared", "cubed"],
    icon: Calculator,
    featured: false,
  },
  "root-calculator": {
    id: "root-calculator",
    slug: "root-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["root", "square root", "cube root", "nth root", "radical"],
    icon: Calculator,
    featured: false,
  },
  "logarithm-calculator": {
    id: "logarithm-calculator",
    slug: "logarithm-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["logarithm", "log", "natural log", "ln", "log10", "base"],
    icon: Calculator,
    featured: false,
  },
  "quadratic-calculator": {
    id: "quadratic-calculator",
    slug: "quadratic-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["quadratic", "equation", "roots", "discriminant", "parabola", "vertex"],
    icon: Calculator,
    featured: true,
  },
  "factor-calculator": {
    id: "factor-calculator",
    slug: "factor-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["factor", "divisor", "factor pairs", "common factors"],
    icon: Calculator,
    featured: false,
  },
  "gcd-calculator": {
    id: "gcd-calculator",
    slug: "gcd-lcm-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["gcd", "greatest common divisor", "gcf", "hcf", "euclidean"],
    icon: Calculator,
    featured: false,
  },
  "lcm-calculator": {
    id: "lcm-calculator",
    slug: "gcd-lcm-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["lcm", "least common multiple", "common multiple"],
    icon: Calculator,
    featured: false,
  },
  "prime-factorization": {
    id: "prime-factorization",
    slug: "prime-factorization-calculator",
    category: "math",
    subcategory: "algebra",
    keywords: ["prime", "factorization", "prime factors", "divisors", "factor tree"],
    icon: Calculator,
    featured: false,
  },

  // Geometry
  "triangle-calculator": {
    id: "triangle-calculator",
    slug: "triangle-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["triangle", "sides", "angles", "area", "perimeter", "law of cosines"],
    icon: Calculator,
    featured: true,
  },
  "pythagorean-calculator": {
    id: "pythagorean-calculator",
    slug: "pythagorean-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["pythagorean", "theorem", "a² + b² = c²", "hypotenuse"],
    icon: Calculator,
    featured: false,
  },
  "circle-calculator": {
    id: "circle-calculator",
    slug: "circle-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["circle", "radius", "diameter", "circumference", "area", "pi"],
    icon: Calculator,
    featured: false,
  },
  "area-calculator": {
    id: "area-calculator",
    slug: "area-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["area", "square", "rectangle", "circle", "triangle", "trapezoid"],
    icon: Calculator,
    featured: false,
  },
  "surface-area-calculator": {
    id: "surface-area-calculator",
    slug: "surface-area-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["surface area", "cube", "sphere", "cylinder", "cone", "pyramid"],
    icon: Calculator,
    featured: false,
  },
  "volume-calculator": {
    id: "volume-calculator",
    slug: "volume-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["volume", "cube", "sphere", "cylinder", "cone", "prism"],
    icon: Calculator,
    featured: false,
  },
  "slope-calculator": {
    id: "slope-calculator",
    slug: "slope-calculator",
    category: "math",
    subcategory: "geometry",
    keywords: ["slope", "line", "gradient", "rise over run", "linear equation"],
    icon: Calculator,
    featured: false,
  },

  // Statistics
  "standard-deviation": {
    id: "standard-deviation",
    slug: "standard-deviation-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["standard deviation", "variance", "population", "sample", "spread"],
    icon: Calculator,
    featured: true,
  },
  "statistics-calculator": {
    id: "statistics-calculator",
    slug: "statistics-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["statistics", "mean", "median", "mode", "quartiles", "skewness"],
    icon: Calculator,
    featured: false,
  },
  "probability-calculator": {
    id: "probability-calculator",
    slug: "probability-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["probability", "odds", "events", "combinations", "likelihood"],
    icon: Calculator,
    featured: false,
  },
  "sample-size": {
    id: "sample-size",
    slug: "sample-size-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["sample size", "survey", "confidence level", "margin of error"],
    icon: Calculator,
    featured: false,
  },
  "z-score-calculator": {
    id: "z-score-calculator",
    slug: "z-score-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["z-score", "standard score", "normal distribution", "probability"],
    icon: Calculator,
    featured: false,
  },
  "p-value-calculator": {
    id: "p-value-calculator",
    slug: "p-value-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["p-value", "hypothesis testing", "significance", "t-test", "chi-square"],
    icon: Calculator,
    featured: false,
  },
  "confidence-interval": {
    id: "confidence-interval",
    slug: "confidence-interval-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["confidence interval", "margin of error", "CI", "estimation"],
    icon: Calculator,
    featured: false,
  },
  "permutation-combination": {
    id: "permutation-combination",
    slug: "permutation-combination-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["permutation", "combination", "nPr", "nCr", "factorial", "arrangements"],
    icon: Calculator,
    featured: false,
  },
  "ratio-calculator": {
    id: "ratio-calculator",
    slug: "ratio-calculator",
    category: "math",
    subcategory: "statistics",
    keywords: ["ratio", "proportion", "scale", "equivalent", "simplify"],
    icon: Calculator,
    featured: false,
  },

  // Number Systems
  "binary-calculator": {
    id: "binary-calculator",
    slug: "binary-calculator",
    category: "math",
    subcategory: "numbers",
    keywords: ["binary", "base 2", "decimal", "convert", "bit operations"],
    icon: Calculator,
    featured: false,
  },
  "hex-calculator": {
    id: "hex-calculator",
    slug: "hex-calculator",
    category: "math",
    subcategory: "numbers",
    keywords: ["hexadecimal", "hex", "base 16", "convert", "0x"],
    icon: Calculator,
    featured: false,
  },
  "scientific-notation": {
    id: "scientific-notation",
    slug: "scientific-notation",
    category: "math",
    subcategory: "numbers",
    keywords: ["scientific notation", "exponent", "mantissa", "engineering notation"],
    icon: Calculator,
    featured: false,
  },
  "big-number": {
    id: "big-number",
    slug: "big-number",
    category: "math",
    subcategory: "numbers",
    keywords: ["big number", "large integer", "arbitrary precision", "big int"],
    icon: Calculator,
    featured: false,
  },
  "number-sequence": {
    id: "number-sequence",
    slug: "number-sequence",
    category: "math",
    subcategory: "numbers",
    keywords: ["sequence", "arithmetic", "geometric", "fibonacci", "pattern"],
    icon: Calculator,
    featured: false,
  },

  // Advanced
  "matrix-calculator": {
    id: "matrix-calculator",
    slug: "matrix-calculator",
    category: "math",
    subcategory: "advanced",
    keywords: ["matrix", "determinant", "transpose", "inverse", "multiplication"],
    icon: Calculator,
    featured: false,
  },
  "half-life-calculator": {
    id: "half-life-calculator",
    slug: "half-life-calculator",
    category: "math",
    subcategory: "advanced",
    keywords: ["half-life", "decay", "radioactive", "carbon dating", "exponential"],
    icon: Calculator,
    featured: false,
  },
  "distance-calculator": {
    id: "distance-calculator",
    slug: "distance-calculator",
    category: "math",
    subcategory: "advanced",
    keywords: ["distance", "euclidean", "haversine", "manhattan", "coordinates"],
    icon: Calculator,
    featured: false,
  },
  "random-number": {
    id: "random-number",
    slug: "random-number-calculator",
    category: "math",
    subcategory: "advanced",
    keywords: ["random", "generator", "dice", "lottery", "shuffle"],
    icon: Calculator,
    featured: false,
  },
  "unit-converter": {
    id: "unit-converter",
    slug: "unit-converter",
    category: "math",
    subcategory: "conversion",
    keywords: ["unit converter", "conversion", "length", "mass", "temperature", "convert"],
    icon: Calculator,
    featured: true,
  },
  "set-calculator": {
    id: "set-calculator",
    slug: "set-calculator",
    category: "math",
    subcategory: "discrete",
    keywords: ["set", "union", "intersection", "set theory", "calculator"],
    icon: Calculator,
    featured: false,
  },
  "programmer-calculator": {
    id: "programmer-calculator",
    slug: "programmer-calculator",
    category: "math",
    subcategory: "numbers",
    keywords: ["programmer", "base converter", "hex", "binary", "bitwise", "calculator"],
    icon: Calculator,
    featured: true,
  },
};
