import { ImageIcon } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const photoConverters: Record<string, ConverterMeta> = {
  // Resolution & Format
  "aspect-ratio": {
    id: "aspect-ratio",
    slug: "aspect-ratio",
    category: "photo",
    subcategory: "resolution",
    keywords: ["aspect ratio", "width", "height", "image", "video", "screen"],
    icon: ImageIcon,
    featured: true,
  },
  "aspect-fit": {
    id: "aspect-fit",
    slug: "aspect-fit",
    category: "photo",
    subcategory: "resolution",
    keywords: ["aspect fit", "letterbox", "pillarbox", "screen", "resize"],
    icon: ImageIcon,
    featured: false,
  },
  dpi: {
    id: "dpi",
    slug: "dpi",
    category: "photo",
    subcategory: "resolution",
    keywords: ["dpi", "ppi", "print", "resolution", "megapixels"],
    icon: ImageIcon,
    featured: false,
  },
  megapixels: {
    id: "megapixels",
    slug: "megapixels",
    category: "photo",
    subcategory: "resolution",
    keywords: ["megapixel", "resolution", "pixels", "image size"],
    icon: ImageIcon,
    featured: false,
  },
  "megapixel-aspects": {
    id: "megapixel-aspects",
    slug: "megapixel-aspects",
    category: "photo",
    subcategory: "resolution",
    keywords: ["megapixel", "aspect ratio", "resolution", "format"],
    icon: ImageIcon,
    featured: false,
  },
  "image-filesize": {
    id: "image-filesize",
    slug: "image-filesize",
    category: "photo",
    subcategory: "resolution",
    keywords: ["image", "file size", "jpeg", "png", "raw", "compression"],
    icon: ImageIcon,
    featured: false,
  },

  // Composition & Framing
  composition: {
    id: "composition",
    slug: "composition",
    category: "photo",
    subcategory: "composition",
    keywords: ["composition", "focal length", "field of view", "crop factor"],
    icon: ImageIcon,
    featured: false,
  },
  "portrait-distance": {
    id: "portrait-distance",
    slug: "portrait-distance",
    category: "photo",
    subcategory: "composition",
    keywords: ["portrait", "distance", "focal length", "headshot"],
    icon: ImageIcon,
    featured: false,
  },
  "focal-equivalent": {
    id: "focal-equivalent",
    slug: "focal-equivalent",
    category: "photo",
    subcategory: "composition",
    keywords: ["focal length", "equivalent", "crop factor", "sensor", "field of view"],
    icon: ImageIcon,
    featured: false,
  },

  // Depth of Field
  "depth-of-field": {
    id: "depth-of-field",
    slug: "depth-of-field",
    category: "photo",
    subcategory: "dof",
    keywords: ["depth of field", "dof", "aperture", "bokeh", "hyperfocal"],
    icon: ImageIcon,
    featured: false,
  },
  hyperfocal: {
    id: "hyperfocal",
    slug: "hyperfocal",
    category: "photo",
    subcategory: "dof",
    keywords: ["hyperfocal", "depth of field", "landscape", "sharpness", "focus"],
    icon: ImageIcon,
    featured: false,
  },
  "advanced-dof": {
    id: "advanced-dof",
    slug: "advanced-dof",
    category: "photo",
    subcategory: "dof",
    keywords: ["depth of field", "dof", "circle of confusion", "print", "viewing distance"],
    icon: ImageIcon,
    featured: false,
  },
  "macro-dof": {
    id: "macro-dof",
    slug: "macro-dof",
    category: "photo",
    subcategory: "dof",
    keywords: ["macro", "depth of field", "magnification", "close-up", "focus stacking"],
    icon: ImageIcon,
    featured: false,
  },
  "dof-table": {
    id: "dof-table",
    slug: "dof-table",
    category: "photo",
    subcategory: "dof",
    keywords: ["depth of field", "table", "aperture", "distance", "reference"],
    icon: ImageIcon,
    featured: false,
  },
  "circle-of-confusion": {
    id: "circle-of-confusion",
    slug: "circle-of-confusion",
    category: "photo",
    subcategory: "dof",
    keywords: ["circle of confusion", "coc", "depth of field", "print", "sharpness"],
    icon: ImageIcon,
    featured: false,
  },

  // Exposure & Light
  "light-ev": {
    id: "light-ev",
    slug: "light-ev",
    category: "photo",
    subcategory: "exposure",
    keywords: ["exposure", "ev", "aperture", "shutter", "iso", "light"],
    icon: ImageIcon,
    featured: false,
  },
  "nd-filter": {
    id: "nd-filter",
    slug: "nd-filter",
    category: "photo",
    subcategory: "exposure",
    keywords: ["nd filter", "neutral density", "long exposure", "shutter speed"],
    icon: ImageIcon,
    featured: false,
  },
  "golden-hour": {
    id: "golden-hour",
    slug: "golden-hour",
    category: "photo",
    subcategory: "exposure",
    keywords: ["golden hour", "blue hour", "twilight", "sunrise", "sunset", "geolocation"],
    icon: ImageIcon,
    featured: false,
  },
  "sun-position": {
    id: "sun-position",
    slug: "sun-position",
    category: "photo",
    subcategory: "exposure",
    keywords: [
      "sun position",
      "altitude",
      "azimuth",
      "twilight",
      "golden hour",
      "blue hour",
      "astrophotography",
    ],
    icon: ImageIcon,
    featured: false,
  },

  // Astrophotography
  "star-trails": {
    id: "star-trails",
    slug: "star-trails",
    category: "photo",
    subcategory: "astro",
    keywords: ["star trails", "astrophotography", "long exposure", "night", "rotation"],
    icon: ImageIcon,
    featured: false,
  },
  "spot-stars": {
    id: "spot-stars",
    slug: "spot-stars",
    category: "photo",
    subcategory: "astro",
    keywords: ["spot stars", "npf rule", "milky way", "astrophotography", "500 rule"],
    icon: ImageIcon,
    featured: false,
  },
  "time-lapse": {
    id: "time-lapse",
    slug: "time-lapse",
    category: "photo",
    subcategory: "astro",
    keywords: ["time lapse", "timelapse", "interval", "photography", "video"],
    icon: ImageIcon,
    featured: false,
  },

  // Optics
  diffraction: {
    id: "diffraction",
    slug: "diffraction",
    category: "photo",
    subcategory: "optics",
    keywords: ["diffraction", "airy disk", "aperture", "sharpness", "pixel pitch"],
    icon: ImageIcon,
    featured: false,
  },
  "macro-diffraction": {
    id: "macro-diffraction",
    slug: "macro-diffraction",
    category: "photo",
    subcategory: "optics",
    keywords: ["macro", "diffraction", "effective aperture", "magnification", "sharpness"],
    icon: ImageIcon,
    featured: false,
  },
};
