import { Building2, Calculator, TrendingUp } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const realestateConverters: Record<string, ConverterMeta> = {
  "mortgage-swiss": {
    id: "mortgage-swiss",
    slug: "mortgage-swiss",
    category: "realestate",
    subcategory: "loans",
    keywords: [
      "mortgage",
      "hypothek",
      "hypotheque",
      "loan",
      "swiss",
      "chf",
      "eur",
      "house",
      "apartment",
      "property",
      "amortization",
    ],
    icon: Building2,
    featured: true,
  },
  "rental-yield": {
    id: "rental-yield",
    slug: "rental-yield",
    category: "realestate",
    subcategory: "investment",
    keywords: [
      "rental",
      "yield",
      "investment",
      "roi",
      "return",
      "mietrendite",
      "rendement",
      "property",
      "landlord",
      "income",
    ],
    icon: TrendingUp,
    featured: true,
  },
  "property-valuation": {
    id: "property-valuation",
    slug: "property-valuation",
    category: "realestate",
    subcategory: "valuation",
    keywords: [
      "property",
      "valuation",
      "estimate",
      "value",
      "liegenschaft",
      "immobilier",
      "house",
      "apartment",
      "price",
      "market",
    ],
    icon: Calculator,
    featured: true,
  },
};
