import { jsPDF } from "jspdf";

export interface PdfExportOptions {
  title: string;
  subtitle?: string;
  filename?: string;
}

export interface PdfSection {
  title: string;
  items: PdfItem[];
}

export interface PdfItem {
  label: string;
  value: string | number;
  unit?: string;
}

/**
 * Export calculator results to PDF
 */
export function exportToPdf(sections: PdfSection[], options: PdfExportOptions): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(options.title, pageWidth / 2, y, { align: "center" });
  y += 10;

  // Subtitle
  if (options.subtitle) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(options.subtitle, pageWidth / 2, y, { align: "center" });
    y += 5;
  }

  // Reset text color
  doc.setTextColor(0);
  y += 10;

  // Sections
  for (const section of sections) {
    // Check if we need a new page
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = margin;
    }

    // Section title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(section.title, margin, y);
    y += 8;

    // Section items
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    for (const item of section.items) {
      // Check if we need a new page
      if (y > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = margin;
      }

      const valueText = item.unit ? `${item.value} ${item.unit}` : String(item.value);

      // Label (left aligned)
      doc.setTextColor(80);
      doc.text(item.label, margin + 5, y);

      // Value (right aligned)
      doc.setTextColor(0);
      doc.text(valueText, pageWidth - margin, y, { align: "right" });

      y += 7;
    }

    y += 8;
  }

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `Generated by Converty - ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" }
    );
  }

  // Save
  const filename = options.filename ?? `${options.title.toLowerCase().replace(/\s+/g, "-")}.pdf`;
  doc.save(filename);
}

/**
 * Simple helper to export a single result set
 */
export function exportSimpleResult(
  title: string,
  items: PdfItem[],
  options?: Partial<PdfExportOptions>
): void {
  exportToPdf([{ title: "Results", items }], { title, ...options });
}
