// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/all">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/automotive/fuel-efficiency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automotive/fuel-efficiency">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/automotive/fuel-efficiency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/automotive/maintenance-intervals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automotive/maintenance-intervals">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/automotive/maintenance-intervals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/automotive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automotive">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/automotive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/automotive/tire-sizing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automotive/tire-sizing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/automotive/tire-sizing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/automotive/vehicle-financing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/automotive/vehicle-financing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/automotive/vehicle-financing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/dilution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry/dilution">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/dilution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/molarity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry/molarity">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/molarity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/molecular-weight/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry/molecular-weight">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/molecular-weight/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/periodic-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry/periodic-table">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/periodic-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/ph-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry/ph-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/ph-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chemistry/stoichiometry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chemistry/stoichiometry">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chemistry/stoichiometry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/color/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/color">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/color/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/color/rgb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/color/rgb">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/color/rgb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cooking/cooking-units/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cooking/cooking-units">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cooking/cooking-units/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cooking/food-cost/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cooking/food-cost">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cooking/food-cost/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cooking/nutrition-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cooking/nutrition-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cooking/nutrition-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cooking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cooking">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cooking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cooking/recipe-scaler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cooking/recipe-scaler">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cooking/recipe-scaler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/crypto/exchange-rate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/crypto/exchange-rate">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/crypto/exchange-rate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/crypto/hash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/crypto/hash">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/crypto/hash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/crypto/mining/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/crypto/mining">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/crypto/mining/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/crypto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/crypto">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/crypto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/crypto/wallet-validator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/crypto/wallet-validator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/crypto/wallet-validator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/data/bandwidth-delay-product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/data/bandwidth-delay-product">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/data/bandwidth-delay-product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/data/bandwidth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/data/bandwidth">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/data/bandwidth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/data/data-size/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/data/data-size">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/data/data-size/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/data/download-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/data/download-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/data/download-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/data">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/data/tcp-throughput/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/data/tcp-throughput">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/data/tcp-throughput/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/age/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/age">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/age/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/date/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/date">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/date/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/day-counter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/day-counter">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/day-counter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/day-of-week/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/day-of-week">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/day-of-week/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/duration-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/duration-converter">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/duration-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/hours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/hours">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/hours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/time-duration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/time-duration">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/time-duration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/time-zone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/time-zone">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/time-zone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/datetime/time/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/datetime/time">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/datetime/time/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/beam-deflection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering/beam-deflection">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/beam-deflection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/column-buckling/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering/column-buckling">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/column-buckling/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/engineering-unit-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering/engineering-unit-converter">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/engineering-unit-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/moment-of-inertia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering/moment-of-inertia">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/moment-of-inertia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/pipe-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering/pipe-flow">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/pipe-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/engineering/stress-strain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/engineering/stress-strain">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/engineering/stress-strain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/annuity-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/annuity-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/annuity-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/auto-loan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/auto-loan">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/auto-loan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/bond-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/bond-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/bond-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/break-even/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/break-even">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/break-even/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/compound-interest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/compound-interest">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/compound-interest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/credit-card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/credit-card">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/credit-card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/currency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/currency">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/currency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/debt-payoff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/debt-payoff">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/debt-payoff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/debt-snowball-avalanche/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/debt-snowball-avalanche">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/debt-snowball-avalanche/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/discount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/discount">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/discount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/down-payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/down-payment">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/down-payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/home-equity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/home-equity">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/home-equity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/income-tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/income-tax">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/income-tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/inflation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/inflation">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/inflation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/ira-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/ira-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/ira-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/loan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/loan">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/loan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/mortgage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/mortgage">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/mortgage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/personal-loan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/personal-loan">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/personal-loan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/profit-margin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/profit-margin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/profit-margin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/retirement-401k/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/retirement-401k">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/retirement-401k/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/retirement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/retirement">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/retirement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/roi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/roi">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/roi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/savings-goal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/savings-goal">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/savings-goal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/student-loan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/student-loan">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/student-loan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/finance/tip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/finance/tip">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/finance/tip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/army-body-fat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/army-body-fat">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/army-body-fat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/bac-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/bac-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/bac-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/bmi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/bmi">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/bmi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/bmr-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/bmr-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/bmr-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/body-fat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/body-fat">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/body-fat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/body-surface-area/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/body-surface-area">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/body-surface-area/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/body-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/body-type">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/body-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/calorie-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/calorie-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/calorie-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/calories-burned/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/calories-burned">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/calories-burned/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/carb-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/carb-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/carb-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/corpulence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/corpulence">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/corpulence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/due-date/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/due-date">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/due-date/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/fat-intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/fat-intake">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/fat-intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/gfr-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/gfr-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/gfr-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/healthy-weight/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/healthy-weight">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/healthy-weight/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/ideal-weight/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/ideal-weight">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/ideal-weight/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/lean-body-mass/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/lean-body-mass">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/lean-body-mass/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/macro-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/macro-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/macro-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/one-rep-max/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/one-rep-max">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/one-rep-max/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/ovulation-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/ovulation-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/ovulation-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/pace-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/pace-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/pace-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/period-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/period-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/period-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/pregnancy-weight-gain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/pregnancy-weight-gain">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/pregnancy-weight-gain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/protein-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/protein-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/protein-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/sleep-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/sleep-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/sleep-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/target-heart-rate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/target-heart-rate">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/target-heart-rate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/tdee-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/tdee-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/tdee-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/health/water-intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/health/water-intake">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/health/water-intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/cpu-comparison-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/cpu-comparison-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/cpu-comparison-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/hyperv-consolidation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/hyperv-consolidation">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/hyperv-consolidation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/hypervisor-comparison/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/hypervisor-comparison">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/hypervisor-comparison/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/k8s-capacity-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/k8s-capacity-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/k8s-capacity-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/server-refresh-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/server-refresh-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/server-refresh-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/server-virtualization-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/server-virtualization-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/server-virtualization-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/virtualization-cost/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/virtualization-cost">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/virtualization-cost/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/vm-storage-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/vm-storage-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/vm-storage-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/vmware-licensing-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/vmware-licensing-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/vmware-licensing-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/infrastructure/windows-licensing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/infrastructure/windows-licensing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/infrastructure/windows-licensing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/area-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/area-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/area-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/average-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/average-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/average-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/basic-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/basic-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/basic-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/big-number/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/big-number">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/big-number/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/binary-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/binary-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/binary-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/circle-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/circle-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/circle-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/confidence-interval-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/confidence-interval-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/confidence-interval-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/distance-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/distance-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/distance-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/exponent-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/exponent-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/exponent-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/factor-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/factor-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/factor-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/fraction-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/fraction-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/fraction-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/gcd-lcm-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/gcd-lcm-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/gcd-lcm-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/half-life-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/half-life-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/half-life-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/hex-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/hex-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/hex-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/logarithm-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/logarithm-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/logarithm-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/long-division/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/long-division">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/long-division/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/matrix-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/matrix-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/matrix-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/number-sequence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/number-sequence">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/number-sequence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/p-value-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/p-value-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/p-value-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/percent-error-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/percent-error-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/percent-error-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/percentage-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/percentage-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/percentage-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/permutation-combination-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/permutation-combination-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/permutation-combination-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/prime-factorization-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/prime-factorization-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/prime-factorization-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/probability-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/probability-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/probability-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/programmer-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/programmer-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/programmer-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/pythagorean-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/pythagorean-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/pythagorean-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/quadratic-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/quadratic-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/quadratic-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/random-number-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/random-number-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/random-number-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/ratio-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/ratio-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/ratio-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/root-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/root-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/root-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/rounding-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/rounding-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/rounding-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/sample-size-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/sample-size-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/sample-size-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/scientific-notation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/scientific-notation">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/scientific-notation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/set-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/set-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/set-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/slope-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/slope-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/slope-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/standard-deviation-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/standard-deviation-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/standard-deviation-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/statistics-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/statistics-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/statistics-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/surface-area-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/surface-area-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/surface-area-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/triangle-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/triangle-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/triangle-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/unit-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/unit-converter">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/unit-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/volume-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/volume-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/volume-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/math/z-score-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/math/z-score-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/math/z-score-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/music/bpm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/music/bpm">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/music/bpm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/music/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/music">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/music/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/bb-credit-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network/bb-credit-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/bb-credit-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/cidr-range/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network/cidr-range">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/cidr-range/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/ip-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network/ip-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/ip-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/latency-converter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network/latency-converter">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/latency-converter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/subnet-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network/subnet-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/subnet-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/network/throughput-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/network/throughput-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/network/throughput-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/advanced-dof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/advanced-dof">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/advanced-dof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/aspect-fit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/aspect-fit">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/aspect-fit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/aspect-ratio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/aspect-ratio">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/aspect-ratio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/circle-of-confusion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/circle-of-confusion">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/circle-of-confusion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/composition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/composition">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/composition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/depth-of-field/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/depth-of-field">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/depth-of-field/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/diffraction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/diffraction">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/diffraction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/dof-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/dof-table">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/dof-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/dpi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/dpi">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/dpi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/focal-equivalent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/focal-equivalent">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/focal-equivalent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/golden-hour/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/golden-hour">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/golden-hour/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/hyperfocal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/hyperfocal">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/hyperfocal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/image-filesize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/image-filesize">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/image-filesize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/light-ev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/light-ev">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/light-ev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/macro-diffraction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/macro-diffraction">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/macro-diffraction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/macro-dof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/macro-dof">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/macro-dof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/megapixel-aspects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/megapixel-aspects">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/megapixel-aspects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/megapixels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/megapixels">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/megapixels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/nd-filter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/nd-filter">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/nd-filter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/portrait-distance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/portrait-distance">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/portrait-distance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/spot-stars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/spot-stars">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/spot-stars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/star-trails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/star-trails">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/star-trails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/sun-position/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/sun-position">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/sun-position/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/photo/time-lapse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/photo/time-lapse">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/photo/time-lapse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/physics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/physics">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/physics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/physics/speed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/physics/speed">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/physics/speed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/realestate/mortgage-swiss/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/realestate/mortgage-swiss">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/realestate/mortgage-swiss/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/realestate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/realestate">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/realestate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/realestate/property-valuation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/realestate/property-valuation">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/realestate/property-valuation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/realestate/rental-yield/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/realestate/rental-yield">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/realestate/rental-yield/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/sitemap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sitemap">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/sitemap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/tools/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tools/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/tools/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/audio-filesize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/audio-filesize">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/audio-filesize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/common-bitrates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/common-bitrates">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/common-bitrates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/dcp-filesize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/dcp-filesize">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/dcp-filesize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/foot-lambert/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/foot-lambert">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/foot-lambert/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/frame-rate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/frame-rate">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/frame-rate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/screen-size/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/screen-size">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/screen-size/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/video-bitrate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/video-bitrate">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/video-bitrate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/video/video-file-size/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/video/video-file-size">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/video/video-file-size/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/csp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/csp">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/csp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/emoji-chars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/emoji-chars">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/emoji-chars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/html-chars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/html-chars">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/html-chars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/html-encoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/html-encoder">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/html-encoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/https-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/https-check">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/https-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/redirect-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/redirect-check">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/redirect-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/seo-performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/seo-performance">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/seo-performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/spf-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/spf-check">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/spf-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/web/url-encoder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/web/url-encoder">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/web/url-encoder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
