import json, os

BASE = "src/messages"
LOCALES = ["zh", "zh-TW", "en", "de", "ja", "es"]

# 每个工具: 6 语言 guide。字段与现有 A 层 guide 完全一致。
G = {}

G["fraction-calculator"] = {
"zh": {"steps":["选择运算：加、减、乘、除，或直接把带分数/假分数化简。","输入各分数的分子与分母（支持多个分数连算），工具会实时校验分母不为零。","查看最简结果，并可在「假分数 / 带分数」两种呈现之间一键切换。"],
"explanationTitle":"什么是分数运算？",
"formula":"a/b ± c/d = (ad ± bc)/bd；(a/b) × (c/d) = ac/bd",
"explanation":["分数由分子与分母组成：分母表示整体被均分的总份数，分子表示取其中的几份。相加或相减必须先通分为同分母；相乘是分子乘分子、分母乘分母；相除等于乘以后者的倒数。","结果通常需要约分：用分子分母的最大公约数（GCD）同时除尽得到最简分数；若分子大于分母则可化为带分数（整数 + 真分数）。分数运算是比例、概率、配方与工程测量的基础。"],
"faq":[{"q":"分母可以是零吗？","a":"不可以。除以零在数学中无定义，输入分母为零时计算器会立即提示，避免产生错误结果。"},{"q":"带分数怎么输入？","a":"先填整数部分，再分别填分子与分母；结果也支持在假分数与带分数之间切换，方便阅读。"},{"q":"为什么有时结果是循环小数？","a":"分数化为小数时，若分母含有 2、5 以外的质因数就会得到无限循环小数，这是正常数学现象，可按需保留指定位数。"}]},
"zh-TW":{"steps":["選擇運算：加、減、乘、除，或直接把帶分數/假分數化簡。","輸入各分數的分子與分母（支援多個分數連算），工具會即時校驗分母不為零。","查看最簡結果，並可在「假分數 / 帶分數」兩種呈現之間一鍵切換。"],
"explanationTitle":"什麼是分數運算？",
"formula":"a/b ± c/d = (ad ± bc)/bd；(a/b) × (c/d) = ac/bd",
"explanation":["分數由分子與分母組成：分母表示整體被均分的總份數，分子表示取其中的幾份。相加或相減必須先通分为同分母；相乘是分子乘分子、分母乘分母；相除等於乘以後者的倒數。","結果通常需要約分：用分子分母的最大公因數（GCD）同時除盡得到最簡分數；若分子大於分母則可化為帶分數（整數 + 真分數）。分數運算是比例、機率、配方與工程測量的基礎。"],
"faq":[{"q":"分母可以是零嗎？","a":"不可以。除以零在數學中無定義，輸入分母為零時計算器會立即提示，避免產生錯誤結果。"},{"q":"帶分數怎麼輸入？","a":"先填整數部分，再分別填分子與分母；結果也支援在假分數與帶分數之間切換，方便閱讀。"},{"q":"為什麼有時結果是循環小數？","a":"分數化為小數時，若分母含有 2、5 以外的質因數就會得到無限循環小數，這是正常數學現象，可視需求保留指定位數。"}]},
"en":{"steps":["Pick an operation: add, subtract, multiply, divide, or just simplify a mixed/improper fraction.","Enter the numerators and denominators (multiple fractions supported); the tool validates that no denominator is zero.","Read the simplified result and toggle between improper and mixed-number display."],
"explanationTitle":"What are fraction operations?",
"formula":"a/b ± c/d = (ad ± bc)/bd; (a/b) × (c/d) = ac/bd",
"explanation":["A fraction has a numerator and a denominator: the denominator is how many equal parts the whole is split into, the numerator is how many of those parts you take. To add or subtract you must first rewrite both with a common denominator; multiply top-by-top and bottom-by-bottom; divide by multiplying by the reciprocal.","Results are usually reduced: divide numerator and denominator by their greatest common divisor to get the simplest form, and turn an improper fraction into a mixed number when the top is larger. Fraction arithmetic underpins ratios, probability, recipes and engineering measurement."],
"faq":[{"q":"Can the denominator be zero?","a":"No. Division by zero is undefined, so the calculator warns you the moment a denominator is zero to prevent invalid output."},{"q":"How do I enter a mixed number?","a":"Enter the whole part first, then the numerator and denominator; results can also be toggled between improper and mixed form for easier reading."},{"q":"Why is the result sometimes a repeating decimal?","a":"A fraction becomes a repeating decimal when its denominator has prime factors other than 2 or 5. That is normal, and you can keep as many digits as you need."}]},
"de":{"steps":["Wähle die Operation: Addieren, Subtrahieren, Multiplizieren, Dividieren oder nur Kürzen einer gemischten/Echtbruchs.","Gib Zähler und Nenner ein (mehrere Brüche möglich); das Tool prüft, dass kein Nenner null ist.","Lies das gekürzte Ergebnis und wechsle zwischen unechtem Bruch und gemischter Zahl."],
"explanationTitle":"Was sind Bruchrechnungen?",
"formula":"a/b ± c/d = (ad ± bc)/bd; (a/b) × (c/d) = ac/bd",
"explanation":["Ein Bruch besteht aus Zähler und Nenner: Der Nenner gibt an, in wie viele gleiche Teile das Ganze geteilt wird, der Zähler, wie viele davon genommen werden. Bei Addition/Subtraktion zuerst gleichnamig machen; multipliziere Zähler×Zähler und Nenner×Nenner; dividiere durch Multiplikation mit dem Kehrwert.","Ergebnisse werden meist gekürzt: Zähler und Nenner durch den größten gemeinsamen Teiler teilen. Ist der Zähler größer, wird aus dem unechten Bruch eine gemischte Zahl. Bruchrechnung ist Grundlage für Verhältnisse, Wahrscheinlichkeit, Rezepte und Technik."],
"faq":[{"q":"Darf der Nenner null sein?","a":"Nein. Division durch null ist nicht definiert; der Rechner warnt sofort, sobald ein Nenner null ist."},{"q":"Wie gebe ich eine gemischte Zahl ein?","a":"Zuerst den ganzzahligen Anteil, dann Zähler und Nenner; das Ergebnis lässt sich zwischen unechtem Bruch und gemischter Zahl umschalten."},{"q":"Warum ist das Ergebnis manchmal eine periodische Dezimalzahl?","a":"Ein Bruch wird periodisch, wenn der Nenner Primfaktoren außer 2 oder 5 enthält. Das ist normal, und du kannst beliebig viele Stellen behalten."}]},
"ja":{"steps":["計算を選びます。足し算・引き算・掛け算・割り算、または仮分数/帯分数の約分のみ。","各分数の分子と分母を入力します（複数の分数に対応）。分母が 0 でないかリアルタイムで検証します。","約分された結果を確認し、仮分数と帯分数の表示を切り替えられます。"],
"explanationTitle":"分数の計算とは？",
"formula":"a/b ± c/d = (ad ± bc)/bd；(a/b) × (c/d) = ac/bd",
"explanation":["分数は分子と分母からなります。分母は全体を等分した総数、分子はそのうちいくつ取るかを示します。足し算・引き算ではまず通分し、掛け算は分子同士・分母同士を掛け、割り算は逆数を掛けます。","結果は通常約分します。分子と分母を最大公約数で割って最简にし、分子が大きい場合は帯分数にします。分数計算は比・確率・レシピ・工学測定の基礎です。"],
"faq":[{"q":"分母を 0 にできますか？","a":"できません。0 での割りは定義されないため、分母が 0 になるとすぐに警告します。"},{"q":"帯分数はどう入力しますか？","a":"まず整数部を入れ、次に分子と分母を入力します。結果も仮分数と帯分数を切り替えられます。"},{"q":"なぜ結果が循環小数になることがあるのですか？","a":"分母が 2 や 5 以外の素因数を持つと循環小数になります。これは正常な現象で、必要な桁数だけ保持できます。"}]},
"es":{"steps":["Elige la operación: sumar, restar, multiplicar, dividir o simplemente simplificar una fracción mixta/impropia.","Introduce numeradores y denominadores (se admiten varias fracciones); la herramienta comprueba que ningún denominador sea cero.","Lee el resultado simplificado y alterna entre fracción impropia y número mixto."],
"explanationTitle":"¿Qué son las operaciones con fracciones?",
"formula":"a/b ± c/d = (ad ± bc)/bd; (a/b) × (c/d) = ac/bd",
"explanation":["Una fracción tiene numerador y denominador: el denominador indica en cuántas partes iguales se divide el entero y el numerador cuántas de esas partes tomas. Para sumar o restar hay que igualar denominadores; se multiplica numerador por numerador y denominador por denominador; se divide multiplicando por el recíproco.","Los resultados suelen reducirse: divide numerador y denominador por su máximo común divisor. Si el numerador es mayor, la fracción impropia se convierte en número mixto. El cálculo con fracciones es base de proporciones, probabilidad, recetas e ingeniería."],
"faq":[{"q":"¿Puede el denominador ser cero?","a":"No. La división entre cero no está definida, así que la calculadora avisa en cuanto un denominador es cero."},{"q":"¿Cómo introduzco un número mixto?","a":"Primero la parte entera y luego numerador y denominador; el resultado también se puede conmutar entre fracción impropia y mixta."},{"q":"¿Por qué a veces el resultado es decimal periódico?","a":"Una fracción da decimal periódico cuando su denominador tiene factores primos distintos de 2 o 5. Es normal y puedes conservar los decimales que necesites."}]},
}

G["average-calculator"] = {
"zh":{"steps":["把要统计的数字逐行或用逗号分隔输入，可随时增删。","工具自动剔除空值与明显异常项（如需保留离群值可关闭）。","查看算术平均值、合计与数据个数，并可切换查看中位数。"],
"explanationTitle":"平均值怎么算？",
"formula":"平均值 = (x₁ + x₂ + … + xₙ) ÷ n",
"explanation":["算术平均值是将一组数值求和后再除以个数，用来代表这组数据的「中心位置」。它计算简单、直观，但对极端值非常敏感——一个特别大或特别小的数就会把平均值明显拉高或压低。","当数据分布不对称或含有离群值时，中位数往往比平均值更能反映典型水平。例如少数超高收入会把平均收入拉高，使多数人「被平均」。分析时建议同时看平均值与中位数。"],
"faq":[{"q":"平均值和中位数有什么区别？","a":"平均值是所有数相加除以个数；中位数是排序后位于中间的数。数据 skewed 时两者差异很大，中位数更抗极端值影响。"},{"q":"空单元格会影响结果吗？","a":"不会。工具会自动忽略空值与无法识别的文本，只在有效数值上计算。"},{"q":"能算加权平均吗？","a":"本工具计算简单算术平均。若每项权重不同（如成绩占比），需要使用加权平均计算器。"}]},
"zh-TW":{"steps":["把要統計的數字逐行或用逗號分隔輸入，可隨時增刪。","工具自動剔除空值與明顯異常項（如需保留離群值可關閉）。","查看算術平均值、合計與資料個數，並可切換查看中位數。"],
"explanationTitle":"平均值怎麼算？",
"formula":"平均值 = (x₁ + x₂ + … + xₙ) ÷ n",
"explanation":["算術平均值是將一組數值加總後再除以個數，用來代表這組資料的「中心位置」。它計算簡單、直觀，但對極端值非常敏感——一個特別大或特別小的數就會把平均值明顯拉高或壓低。","當資料分佈不對稱或含有離群值時，中位數往往比平均值更能反映典型水準。例如少數超高收入會把平均收入拉高，使多數人「被平均」。分析時建議同時看平均值與中位數。"],
"faq":[{"q":"平均值和中位數有什麼區別？","a":"平均值是所有數相加除以個數；中位數是排序後位於中間的數。資料偏態時兩者差異很大，中位數更抗極端值影響。"},{"q":"空儲存格會影響結果嗎？","a":"不會。工具會自動忽略空值與無法辨識的文字，只在有效數值上計算。"},{"q":"能算加權平均嗎？","a":"本工具計算簡單算術平均。若每項權重不同（如成績佔比），需要使用加權平均計算器。"}]},
"en":{"steps":["Enter the numbers line by line or comma separated; add or remove any time.","The tool ignores blank cells and flags obvious outliers (you can keep them if needed).","Read the arithmetic mean, the sum and the count, and toggle to see the median."],
"explanationTitle":"How is the average calculated?",
"formula":"mean = (x₁ + x₂ + … + xₙ) ÷ n",
"explanation":["The arithmetic mean adds up a set of values and divides by how many there are. It is a simple, intuitive measure of the 'centre' of the data, but it is very sensitive to extremes — a single very large or very small value can pull the mean noticeably up or down.","When a distribution is skewed or contains outliers, the median usually describes the typical value better than the mean. For example, a few very high incomes pull the average income up so most people appear 'below average'. Check both mean and median together."],
"faq":[{"q":"What is the difference between mean and median?","a":"The mean is the sum divided by the count; the median is the middle value after sorting. They diverge a lot in skewed data, and the median resists extreme values."},{"q":"Do empty cells affect the result?","a":"No. Blank cells and unrecognised text are ignored; only valid numbers are used."},{"q":"Can it do a weighted average?","a":"This tool computes the simple arithmetic mean. If each item has a different weight (e.g. exam weights), use a weighted average calculator."}]},
"de":{"steps":["Gib die Zahlen zeilenweise oder durch Komma getrennt ein; jederzeit ergänzbar.","Leere Zellen werden ignoriert, offensichtliche Ausreißer markiert (bei Bedarf beibehalten).","Lies Mittelwert, Summe und Anzahl und schalte bei Bedarf auf den Median um."],
"explanationTitle":"Wie berechnet man den Durchschnitt?",
"formula":"Mittelwert = (x₁ + x₂ + … + xₙ) ÷ n",
"explanation":["Der arithmetische Mittelwert summiert eine Reihe von Werten und teilt durch deren Anzahl. Er ist ein einfaches, anschauliches Maß für die 'Mitte' der Daten, reagiert aber stark auf Extremwerte – ein einzelner sehr großer oder kleiner Wert zieht den Mittelwert spürbar nach oben oder unten.","Bei schiefer Verteilung oder Ausreißern beschreibt der Median den typischen Wert meist besser. Beispielsweise ziehen wenige sehr hohe Einkommen den Durchschnitt so hoch, dass die meisten 'unterdurchschnittlich' wirken. Betrachte Mittelwert und Median gemeinsam."],
"faq":[{"q":"Unterschied zwischen Mittelwert und Median?","a":"Der Mittelwert ist die Summe geteilt durch die Anzahl; der Median ist der mittlere Wert nach Sortierung. Bei schiefen Daten weichen sie stark ab, der Median ist robuster."},{"q":"Beeinflussen leere Zellen das Ergebnis?","a":"Nein. Leere Zellen und nicht erkennbare Texte werden ignoriert; nur gültige Zahlen zählen."},{"q":"Kann man einen gewichteten Durchschnitt berechnen?","a":"Dieses Tool liefert den einfachen arithmetischen Mittelwert. Bei unterschiedlicher Gewichtung (z. B. Notenanteile) nutze einen gewichteten Durchschnitt."}]},
"ja":{"steps":["数値を改行またはカンマ区切りで入力でき、いつでも追加・削除できます。","空欄は無視され、明らかな異常値は警告されます（必要なら保持可）。","算術平均・合計・個数を確認し、中央値の表示も切り替えられます。"],
"explanationTitle":"平均の計算方法",
"formula":"平均 = (x₁ + x₂ + … + xₙ) ÷ n",
"explanation":["算術平均は一連の数値を合計し、その個数で割ったものです。データの「中心」を表す直観的な指標ですが、極端な値に敏感で、1 つの極大・極小値で平均が大きく動きます。","分布が非対称だったり異常値を含む場合、中央値の方が典型的な水準をよく表します。例えば一部の超高収入が平均を押し上げ、多くの人が「平均以下」に見えます。平均と中央値を併せて見ることをお勧めします。"],
"faq":[{"q":"平均と中央値の違いは？","a":"平均は合計を個数で割った値、中央値は並べ替えて真ん中にある値です。偏りがあると両者は大きく離れ、中央値は極端な値に強いです。"},{"q":"空欄は結果に影響しますか？","a":"しません。空欄や読み取れない文字は無視し、有効な数値のみで計算します。"},{"q":"加重平均も計算できますか？","a":"本ツールは単純算術平均です。項目ごとに重みが違う（成績の比率など）場合は加重平均計算機を使ってください。"}]},
"es":{"steps":["Introduce los números en líneas o separados por comas; añade o quita cuando quieras.","Se ignoran las celdas vacías y se marcan los valores atípicos evidentes (puedes conservarlos).","Lee la media aritmética, la suma y el conteo, y alterna para ver la mediana."],
"explanationTitle":"¿Cómo se calcula la media?",
"formula":"media = (x₁ + x₂ + … + xₙ) ÷ n",
"explanation":["La media aritmética suma un conjunto de valores y los divide entre cuántos son. Es una medida simple e intuitiva del 'centro' de los datos, pero muy sensible a los extremos: un solo valor muy alto o bajo desplaza la media notablemente.","Cuando la distribución es asimétrica o tiene valores atípicos, la mediana suele reflejar mejor el valor típico. Por ejemplo, pocos ingresos muy altos elevan la media y hacen que la mayoría parezca 'por debajo'. Conviene ver media y mediana juntas."],
"faq":[{"q":"¿Diferencia entre media y mediana?","a":"La media es la suma dividida por el conteo; la mediana es el valor central tras ordenar. En datos sesgados divergen mucho, y la mediana resiste valores extremos."},{"q":"¿Afectan las celdas vacías al resultado?","a":"No. Se ignoran celdas vacías y textos no reconocidos; solo cuentan los números válidos."},{"q":"¿Puede calcular la media ponderada?","a":"Esta herramienta da la media aritmética simple. Si cada ítem tiene distinto peso (p. ej. porcentaje de notas), usa una media ponderada."}]},
}

G["area-calculator"] = {
"zh":{"steps":["选择图形：矩形、圆形、三角形、梯形等。","按提示输入相应尺寸（如长/宽、半径、底/高）。","查看面积结果，单位可自由切换（cm²、m²、inch² 等）。"],
"explanationTitle":"面积如何计算？",
"formula":"矩形 = 长×宽；圆 = πr²；三角形 = 底×高÷2",
"explanation":["面积是二维图形所覆盖平面大小的量度，单位为长度的平方。不同图形有各自公式：矩形用长乘宽，圆用 π 乘半径平方，三角形用底乘高再除以二。","实际测量时要注意单位统一：若边长以厘米输入，结果就是平方厘米；混用单位会直接出错。面积在装修、土地、布料裁剪与包装设计中都会频繁用到。"],
"faq":[{"q":"单位不统一怎么办？","a":"先统一边长单位再计算，或在本工具内直接切换结果单位，避免 cm 与 m 混用导致的 100 倍误差。"},{"q":"不规则图形怎么算面积？","a":"可将其拆分为若干规则图形分别求面积后相加，或用网格估算法；精确测量建议借助专业 CAD 工具。"},{"q":"π 取几位？","a":"本工具默认取足够精度（约 3.14159），日常足够；如需更高精度可在科学计算中指定。"}]},
"zh-TW":{"steps":["選擇圖形：矩形、圓形、三角形、梯形等。","依提示輸入相應尺寸（如長/寬、半徑、底/高）。","查看面積結果，單位可自由切換（cm²、m²、inch² 等）。"],
"explanationTitle":"面積如何計算？",
"formula":"矩形 = 長×寬；圓 = πr²；三角形 = 底×高÷2",
"explanation":["面積是二維圖形所覆蓋平面大小的量度，單位為長度的平方。不同圖形有各自公式：矩形用長乘寬，圓用 π 乘半徑平方，三角形用底乘高再除以二。","實際測量時要注意單位統一：若邊長以公分輸入，結果就是平方公分；混用單位會直接出錯。面積在裝修、土地、布料裁剪與包裝設計中都會頻繁用到。"],
"faq":[{"q":"單位不統一怎麼辦？","a":"先統一邊長單位再計算，或在本工具內直接切換結果單位，避免 cm 與 m 混用導致的 100 倍誤差。"},{"q":"不規則圖形怎麼算面積？","a":"可將其拆分為若干規則圖形分別求面積後相加，或用網格估算法；精確測量建議借助專業 CAD 工具。"},{"q":"π 取幾位？","a":"本工具預設取足夠精度（約 3.14159），日常足夠；如需更高精度可在科學計算中指定。"}]},
"en":{"steps":["Pick a shape: rectangle, circle, triangle, trapezoid and more.","Enter the required dimensions (length/width, radius, base/height) as prompted.","Read the area and switch the unit freely (cm², m², inch², etc.)."],
"explanationTitle":"How is area calculated?",
"formula":"rectangle = w×h; circle = πr²; triangle = base×height÷2",
"explanation":["Area measures how much two-dimensional surface a shape covers, in square units. Each shape has its own formula: a rectangle is width times height, a circle is π times radius squared, a triangle is base times height divided by two.","Keep units consistent: if sides are in centimetres the result is in square centimetres, and mixing units produces wrong answers. Area comes up constantly in renovation, land, fabric cutting and packaging design."],
"faq":[{"q":"What if my units differ?","a":"Unify the side units first, or switch the result unit inside the tool, to avoid the 100× error from mixing cm and m."},{"q":"How do I find the area of an irregular shape?","a":"Split it into regular shapes, sum their areas, or use a grid estimate; for precision use a CAD tool."},{"q":"How many digits of π are used?","a":"The tool uses enough precision (about 3.14159) for daily use; specify more only in scientific work."}]},
"de":{"steps":["Wähle eine Figur: Rechteck, Kreis, Dreieck, Trapez u. a.","Gib die geforderten Maße ein (Länge/Breite, Radius, Grundseite/Höhe).","Lies die Fläche und wechsle die Einheit frei (cm², m², Zoll² usw.)."],
"explanationTitle":"Wie berechnet man Flächen?",
"formula":"Rechteck = b×h; Kreis = πr²; Dreieck = Grundseite×Höhe÷2",
"explanation":["Die Fläche misst die von einer zweidimensionalen Figur bedeckte Oberfläche, in Quadratenheiten. Jede Figur hat ihre Formel: Rechteck ist Breite mal Höhe, Kreis π mal Radius quadrat, Dreieck Grundseite mal Höhe durch zwei.","Einheiten angleichen: Sind Seiten in Zentimetern, ist das Ergebnis in Quadratzentimetern; gemischte Einheiten führen zu Fehlern. Flächen braucht man ständig bei Renovierung, Grundstücken, Stoffzuschnitt und Verpackung."],
"faq":[{"q":"Was, wenn Einheiten unterschiedlich sind?","a":"Erst die Seitenmaße vereinheitlichen oder die Ergebniseinheit im Tool wechseln, um den 100-fachen Fehler aus cm und m zu vermeiden."},{"q":"Wie flächen einer unregelmäßigen Figur?","a":"In reguläre Teile zerlegen, Flächen addieren oder ein Raster schätzen; für Präzision CAD nutzen."},{"q":"Wie viele Stellen von π?","a":"Das Tool nutzt ausreichende Genauigkeit (ca. 3,14159) für den Alltag; mehr nur in der Wissenschaft."}]},
"ja":{"steps":["図形を選びます。長方形・円・三角形・台形など。","求められる寸法（縦/横、半径、底/高さ）を入力します。","面積を確認し、単位を自由に切り替えられます（cm²、m²、inch² など）。"],
"explanationTitle":"面積の計算方法",
"formula":"長方形 = 縦×横；円 = πr²；三角形 = 底×高さ÷2",
"explanation":["面積は二次元の図形が覆う平面の大きさで、単位は長さの二乗です。図形ごとに公式があり、長方形は縦×横、円は π×半径²、三角形は底×高さ÷2 です。","実測では単位をそろえます。辺を cm で入力すれば結果は cm² になり、単位を混ぜると誤ります。面積は内装・土地・布地・パッケージ設計で頻出します。"],
"faq":[{"q":"単位がバラバラの場合は？","a":"辺の単位をそろえてから計算するか、ツール内で結果単位を切り替えて、cm と m の混在による 100 倍の誤差を避けます。"},{"q":"不規則な図形の面積は？","a":"規則的な図形に分割して合計するか、方眼で見積もります。精密さが必要なら CAD を活用してください。"},{"q":"π は何桁ですか？","a":"本ツールは日常に十分な精度（約 3.14159）を使用します。より高い精度は科学計算で指定してください。"}]},
"es":{"steps":["Elige una figura: rectángulo, círculo, triángulo, trapecio y más.","Introduce las dimensiones que pide (largo/ancho, radio, base/altura).","Lee el área y cambia la unidad libremente (cm², m², pulg², etc.)."],
"explanationTitle":"¿Cómo se calcula el área?",
"formula":"rectángulo = b×h; círculo = πr²; triángulo = base×altura÷2",
"explanation":["El área mide la superficie bidimensional que cubre una figura, en unidades cuadradas. Cada figura tiene su fórmula: el rectángulo es base por altura, el círculo π por radio al cuadrado, el triángulo base por altura entre dos.","Unifica las unidades: si los lados están en centímetros, el resultado es en cm², y mezclar unidades da errores. El área aparece constantemente en reformas, terrenos, costura y diseño de envases."],
"faq":[{"q":"¿Y si mis unidades difieren?","a":"Unifica las unidades de los lados antes, o cambia la unidad del resultado en la herramienta, para evitar el error de 100× al mezclar cm y m."},{"q":"¿Cómo obtengo el área de una figura irregular?","a":"Divídela en figuras regulares, suma sus áreas o usa una estimación por cuadrícula; para precisión usa CAD."},{"q":"¿Cuántos decimales de π se usan?","a":"La herramienta usa suficiente precisión (unos 3,14159) para el diario; más solo en trabajos científicos."}]},
}

G["volume-calculator"] = {
"zh":{"steps":["选择立体图形：长方体、正方体、圆柱、球、锥体等。","输入对应尺寸（长/宽/高、半径、高）。","查看体积，单位可在 mm³ / cm³ / m³ / L 之间切换。"],
"explanationTitle":"体积如何计算？",
"formula":"长方体 = 长×宽×高；圆柱 = πr²h；球 = 4/3·πr³",
"explanation":["体积是三维物体所占空间大小，单位为长度的立方。长方体体积等于长乘宽乘高；圆柱是底面积 πr² 乘高；球为 4/3πr³。","注意体积单位换算：1 立方米 = 1000 升。液体常用升（L）或毫升（mL）表示，而固体常用 cm³。装修买漆、装箱、 aquarium 容量都依赖体积计算。"],
"faq":[{"q":"体积和容积一样吗？","a":"概念接近。容积多指容器内部可容纳的量（常用 L/mL），体积指物体占据的空间（常用 m³/cm³），数值可等价换算。"},{"q":"升和立方米怎么换？","a":"1 立方米 = 1000 升，1 升 = 1000 毫升 = 1000 cm³。本工具可直接切换显示。"},{"q":"不规则物体体积怎么测？","a":"可用排水法（浸入量筒测水位上升量），工程上也可三维扫描后计算。"}]},
"zh-TW":{"steps":["選擇立體圖形：長方體、正方體、圓柱、球、錐體等。","輸入對應尺寸（長/寬/高、半徑、高）。","查看體積，單位可在 mm³ / cm³ / m³ / L 之間切換。"],
"explanationTitle":"體積如何計算？",
"formula":"長方體 = 長×寬×高；圓柱 = πr²h；球 = 4/3·πr³",
"explanation":["體積是三維物體所佔空間大小，單位為長度的立方。長方體體積等於長乘寬乘高；圓柱是底面積 πr² 乘高；球為 4/3πr³。","注意體積單位換算：1 立方公尺 = 1000 公升。液體常用公升（L）或毫升（mL）表示，而固體常用 cm³。裝修買漆、裝箱、水族箱容量都依賴體積計算。"],
"faq":[{"q":"體積和容積一樣嗎？","a":"概念接近。容積多指容器內部可容納的量（常用 L/mL），體積指物體佔據的空間（常用 m³/cm³），數值可等價換算。"},{"q":"公升和立方公尺怎麼換？","a":"1 立方公尺 = 1000 公升，1 公升 = 1000 毫升 = 1000 cm³。本工具可直接切換顯示。"},{"q":"不規則物體體積怎麼測？","a":"可用排水法（浸入量筒測水位上升量），工程上也可三維掃描後計算。"}]},
"en":{"steps":["Pick a solid: cuboid, cube, cylinder, sphere, cone and more.","Enter the matching dimensions (length/width/height, radius, height).","Read the volume and switch units among mm³ / cm³ / m³ / L."],
"explanationTitle":"How is volume calculated?",
"formula":"cuboid = l×w×h; cylinder = πr²h; sphere = 4/3·πr³",
"explanation":["Volume is the space a three-dimensional object occupies, measured in cubic units. A cuboid is length × width × height; a cylinder is base area πr² times height; a sphere is 4/3πr³.","Watch the unit conversion: 1 cubic metre = 1000 litres. Liquids are usually given in litres or millilitres, solids in cm³. Volume matters for paint, packing boxes and aquarium capacity."],
"faq":[{"q":"Are volume and capacity the same?","a":"Close. Capacity is what a container holds (litres/mL); volume is the space an object takes (m³/cm³). The numbers convert directly."},{"q":"How do litres and cubic metres relate?","a":"1 m³ = 1000 L, and 1 L = 1000 mL = 1000 cm³. The tool switches display for you."},{"q":"How do I measure an irregular object's volume?","a":"Use water displacement (submerge and read the rise in a graduated cylinder), or 3D scan and compute."}]},
"de":{"steps":["Wähle einen Körper: Quader, Würfel, Zylinder, Kugel, Kegel u. a.","Gib die passenden Maße ein (Länge/Breite/Höhe, Radius, Höhe).","Lies das Volumen und wechsle Einheiten mm³ / cm³ / m³ / L."],
"explanationTitle":"Wie berechnet man Volumen?",
"formula":"Quader = l×b×h; Zylinder = πr²h; Kugel = 4/3·πr³",
"explanation":["Volumen ist der Raum, den ein dreidimensionaler Körper einnimmt, in Kubikeinheiten. Ein Quader ist Länge × Breite × Höhe; ein Zylinder Grundfläche πr² mal Höhe; eine Kugel 4/3πr³.","Achtung Einheit: 1 Kubikmeter = 1000 Liter. Flüssigkeiten nutzen Liter/Milliliter, Feststoffe cm³. Volumen braucht man für Farbe, Kartons und Aquarien."],
"faq":[{"q":"Volumen und Fassungsvermögen gleich?","a":"Ähnlich. Fassungsvermögen ist, was ein Behälter hält (L/mL); Volumen ist der Raum (m³/cm³). Zahlen lassen sich direkt umrechnen."},{"q":"Liter und Kubikmeter?","a":"1 m³ = 1000 L, 1 L = 1000 mL = 1000 cm³. Das Tool stellt um."},{"q":"Volumen eines unregelmäßigen Körpers?","a":"Wasserverdrängung (Eintauchen, Anstieg im Messzylinder) oder 3D-Scan und Berechnung."}]},
"ja":{"steps":["立体を選びます。直方体・立方体・円柱・球・円錐など。","対応する寸法（縦/横/高さ、半径、高さ）を入力します。","体積を確認し、mm³ / cm³ / m³ / L の単位を切り替えられます。"],
"explanationTitle":"体積の計算方法",
"formula":"直方体 = 縦×横×高さ；円柱 = πr²h；球 = 4/3·πr³",
"explanation":["体積は三次元の物体が占める空間の大きさで、単位は長さの立方です。直方体は縦×横×高さ、円柱は底面積 πr²×高さ、球は 4/3πr³ です。","単位換算に注意：1 m³ = 1000 L。液体は L/mL、固体は cm³ で表すことが多いです。塗料や荷造り、水槽の容量に体積が関わります。"],
"faq":[{"q":"体積と容量は同じ？","a":"近い概念です。容量は容器が入る量（L/mL）、体積は物体の空間（m³/cm³）。数値は等価に換算できます。"},{"q":"リットルと立方メートルの関係は？","a":"1 m³ = 1000 L、1 L = 1000 mL = 1000 cm³。ツールが表示を切り替えます。"},{"q":"不規則な物体の体積は？","a":"排水法（メスシリンダーで水位上昇を読む）や、3D スキャンして計算します。"}]},
"es":{"steps":["Elige un sólido: ortoedro, cubo, cilindro, esfera, cono y más.","Introduce las dimensiones correspondientes (largo/ancho/alto, radio, altura).","Lee el volumen y cambia unidades entre mm³ / cm³ / m³ / L."],
"explanationTitle":"¿Cómo se calcula el volumen?",
"formula":"ortoedro = l×a×h; cilindro = πr²h; esfera = 4/3·πr³",
"explanation":["El volumen es el espacio que ocupa un objeto tridimensional, en unidades cúbicas. Un ortoedro es largo × ancho × alto; un cilindro base πr² por altura; una esfera 4/3πr³.","Ojo con las unidades: 1 metro cúbico = 1000 litros. Los líquidos suelen ir en litros o mililitros, los sólidos en cm³. El volumen importa para pintura, cajas y acuarios."],
"faq":[{"q":"¿Volumen y capacidad son iguales?","a":"Casi. Capacidad es lo que cabe en un recipiente (L/mL); volumen es el espacio que ocupa (m³/cm³). Se convierten directamente."},{"q":"¿Litros y metros cúbicos?","a":"1 m³ = 1000 L, y 1 L = 1000 mL = 1000 cm³. La herramienta cambia la visualización."},{"q":"¿Cómo mido el volumen de un objeto irregular?","a":"Por desplazamiento de agua (sumerge y lee el ascenso en una probeta), o escanea en 3D y calcula."}]},
}

G["pythagorean-calculator"] = {
"zh":{"steps":["确认已知两边：直角边 a、b，或一边与斜边 c。","输入已知数值，未知边留空（也可只求斜边）。","查看第三边长度，并附勾股定理的代数推导过程。"],
"explanationTitle":"勾股定理是什么？",
"formula":"a² + b² = c²（c 为斜边）",
"explanation":["勾股定理指出：在直角三角形中，两直角边的平方和等于斜边的平方。它是欧几里得几何的基础定理，广泛应用于建筑、导航、图形与信号处理。","求斜边时用 √(a²+b²)；已知斜边与一边求另一直角边则用 √(c²−a²)。注意它只适用于直角三角形，非直角需用余弦定理。"],
"faq":[{"q":"只适用于直角三角形吗？","a":"是。勾股定理仅对直角三角形成立；一般三角形要用余弦定理 c²=a²+b²−2ab·cosC。"},{"q":"怎么求斜边？","a":"将两直角边平方相加再开平方：c = √(a²+b²)。"},{"q":"单位需要一致吗？","a":"需要。a、b、c 必须同一长度单位，结果才是该单位下的边长。"}]},
"zh-TW":{"steps":["確認已知兩邊：直角邊 a、b，或一邊與斜邊 c。","輸入已知數值，未知邊留空（也可只求斜邊）。","查看第三邊長度，並附勾股定理的代數推導過程。"],
"explanationTitle":"勾股定理是什麼？",
"formula":"a² + b² = c²（c 為斜邊）",
"explanation":["勾股定理指出：在直角三角形中，兩直角邊的平方和等於斜邊的平方。它是歐幾里得幾何的基礎定理，廣泛應用於建築、導航、圖形與訊號處理。","求斜邊時用 √(a²+b²)；已知斜邊與一邊求另一直角邊則用 √(c²−a²)。注意它只適用於直角三角形，非直角需用餘弦定理。"],
"faq":[{"q":"只適用於直角三角形嗎？","a":"是。勾股定理僅對直角三角形成立；一般三角形要用餘弦定理 c²=a²+b²−2ab·cosC。"},{"q":"怎麼求斜邊？","a":"將兩直角邊平方相加再開平方：c = √(a²+b²)。"},{"q":"單位需要一致嗎？","a":"需要。a、b、c 必須同一長度單位，結果才是該單位下的邊長。"}]},
"en":{"steps":["State the known sides: legs a and b, or one leg and hypotenuse c.","Enter the known values and leave the unknown blank (you can solve for the hypotenuse only).","Read the third side and see the algebraic steps of the theorem."],
"explanationTitle":"What is the Pythagorean theorem?",
"formula":"a² + b² = c² (c is the hypotenuse)",
"explanation":["The Pythagorean theorem says that in a right triangle, the square of the two legs equals the square of the hypotenuse. It is a foundation of Euclidean geometry and is used in construction, navigation, graphics and signal processing.","For the hypotenuse use √(a²+b²); if you know the hypotenuse and one leg, the other leg is √(c²−a²). It applies only to right triangles; others need the law of cosines."],
"faq":[{"q":"Only for right triangles?","a":"Yes. The theorem holds only for right triangles; general triangles use the law of cosines c²=a²+b²−2ab·cosC."},{"q":"How do I find the hypotenuse?","a":"Square the legs, add them, then take the square root: c = √(a²+b²)."},{"q":"Must the units match?","a":"Yes. a, b and c must share one length unit, or the result is meaningless."}]},
"de":{"steps":["Gib die bekannten Seiten an: Katheten a und b oder eine Kathete und Hypotenuse c.","Trage die bekannten Werte ein, die Unbekannte leer lassen (auch nur Hypotenuse möglich).","Lies die dritte Seite und die algebraischen Schritte des Satzes."],
"explanationTitle":"Was ist der Satz des Pythagoras?",
"formula":"a² + b² = c² (c ist die Hypotenuse)",
"explanation":["Der Satz des Pythagoras besagt: Im rechtwinkligen Dreieck ist die Summe der Kathetenquadrate gleich dem Hypotenusenquadrat. Er ist Grundlage der euklidischen Geometrie und wird in Bau, Navigation, Grafik und Signalverarbeitung genutzt.","Für die Hypotenuse √(a²+b²); kennt man Hypotenuse und eine Kathete, ist die andere √(c²−a²). Er gilt nur für rechtwinklige Dreiecke; sonst Kosinussatz."],
"faq":[{"q":"Nur für rechtwinklige Dreiecke?","a":"Ja. Er gilt nur für rechtwinklige Dreiecke; allgemeine brauchen den Kosinussatz c²=a²+b²−2ab·cosC."},{"q":"Wie finde ich die Hypotenuse?","a":"Katheten quadrieren, addieren, Wurzel ziehen: c = √(a²+b²)."},{"q":"Müssen Einheiten gleich sein?","a":"Ja. a, b und c brauchen dieselbe Längeneinheit."}]},
"ja":{"steps":["既知の辺を指定します。直角を挟む辺 a・b、または一辺と斜辺 c。","既知の値を入力し、未知の辺は空欄にします（斜辺だけ求めることも可）。","第三の辺を確認し、定理の代数展開も表示します。"],
"explanationTitle":"三平方の定理とは？",
"formula":"a² + b² = c²（c は斜辺）",
"explanation":["三平方の定理は、直角三角形において直角を挟む二辺の二乗和が斜辺の二乗に等しいことを示します。ユークリッド幾何の基礎で、建築・航海・グラフィックス・信号処理に広く使われます。","斜辺は √(a²+b²)。斜辺と一辺から他辺を求めるなら √(c²−a²)。直角三角形のみに適用され、それ以外は余弦定理を使います。"],
"faq":[{"q":"直角三角形のみですか？","a":"はい。直角三角形にのみ成り立ちます。一般の三角形は余弦定理 c²=a²+b²−2ab·cosC を使います。"},{"q":"斜辺の求め方は？","a":"二辺を二乗して足し、平方根をとります：c = √(a²+b²)。"},{"q":"単位はそろえる必要がありますか？","a":"必要です。a・b・c は同じ長さの単位にそろえてください。"}]},
"es":{"steps":["Indica los lados conocidos: catetos a y b, o un cateto e hipotenusa c.","Introduce los valores conocidos y deja en blanco el desconocido (también solo la hipotenusa).","Lee el tercer lado y los pasos algebraicos del teorema."],
"explanationTitle":"¿Qué es el teorema de Pitágoras?",
"formula":"a² + b² = c² (c es la hipotenusa)",
"explanation":["El teorema de Pitágoras dice que en un triángulo rectángulo, el cuadrado de los catetos suma el cuadrado de la hipotenusa. Es base de la geometría euclídea y se usa en construcción, navegación, gráficos y procesamiento de señales.","Para la hipotenusa usa √(a²+b²); si conoces hipotenusa y un cateto, el otro es √(c²−a²). Solo vale para rectángulos; los demás usan la ley de cosenos."],
"faq":[{"q":"¿Solo para triángulos rectángulos?","a":"Sí. El teorema solo vale para rectángulos; los generales usan la ley de cosenos c²=a²+b²−2ab·cosC."},{"q":"¿Cómo hallo la hipotenusa?","a":"Eleva los catetos al cuadrado, súmalos y saca la raíz: c = √(a²+b²)."},{"q":"¿Deben coincidir las unidades?","a":"Sí. a, b y c deben usar la misma unidad de longitud."}]},
}

G["aspect-ratio"] = {
"zh":{"steps":["输入原始宽和高（或选择一个常见预设比例，如 16:9）。","指定输出的一边（宽或高），另一边由比例自动推出。","查看换算后的尺寸，并可对比不同比例下的画面裁剪情况。"],
"explanationTitle":"宽高比是什么？",
"formula":"宽 : 高 = 输出宽 : 输出高",
"explanation":["宽高比描述画面或图像的宽度与高度之比，常用「宽:高」表示。保持比例缩放可避免画面拉伸变形：只要输出两边的比值等于原始比值，内容就不会被压扁或拉长。","常见比例有 16:9（宽屏视频）、4:3（老式电视）、1:1（正方形社媒图）。设计海报、剪辑视频或适配手机屏幕时，正确设置比例能保证构图一致。"],
"faq":[{"q":"为什么图像拉伸会变形？","a":"因为缩放后宽高比与原始不同。锁定「保持比例」即可让另一边按比例自动计算，避免压扁。"},{"q":"16:9 和 4:3 差在哪？","a":"16:9 更宽，适合现代电视与视频；4:3 更接近正方形，是早期显示器的标准。"},{"q":"怎么把照片改成 1:1？","a":"以较短边为基准裁切较长边，或用本工具输入原尺寸与目标比例 1:1，得到需裁剪的尺寸。"}]},
"zh-TW":{"steps":["輸入原始寬和高（或選擇一個常見預設比例，如 16:9）。","指定輸出的一邊（寬或高），另一邊由比例自動推出。","查看換算後的尺寸，並可對比不同比例下的畫面裁剪情況。"],
"explanationTitle":"寬高比是什麼？",
"formula":"寬 : 高 = 輸出寬 : 輸出高",
"explanation":["寬高比描述畫面或圖像的寬度與高度之比，常用「寬:高」表示。保持比例縮放可避免畫面拉伸變形：只要輸出兩邊的比值等於原始比值，內容就不會被壓扁或拉長。","常見比例有 16:9（寬螢幕影片）、4:3（老式電視）、1:1（正方形社媒圖）。設計海報、剪輯影片或适配手機螢幕時，正確設定比例能保證構圖一致。"],
"faq":[{"q":"為什麼圖像拉伸會變形？","a":"因為縮放後寬高比與原始不同。鎖定「保持比例」即可讓另一邊按比例自動計算，避免壓扁。"},{"q":"16:9 和 4:3 差在哪？","a":"16:9 更寬，適合現代電視與影片；4:3 更接近正方形，是早期顯示器的標準。"},{"q":"怎麼把照片改成 1:1？","a":"以較短邊為基準裁切較長邊，或用本工具輸入原尺寸與目標比例 1:1，得到需裁切的尺寸。"}]},
"en":{"steps":["Enter the original width and height, or pick a common preset like 16:9.","Specify one output side (width or height); the other is derived from the ratio.","Read the converted dimensions and compare cropping across ratios."],
"explanationTitle":"What is aspect ratio?",
"formula":"width : height = output width : output height",
"explanation":["Aspect ratio is the width-to-height proportion of a frame or image, written as 'width:height'. Scaling while keeping the ratio avoids distortion: as long as the output sides keep the same proportion, content is neither squashed nor stretched.","Common ratios are 16:9 (widescreen video), 4:3 (older TV) and 1:1 (square social images). Setting the right ratio in posters, video or mobile layouts keeps composition consistent."],
"faq":[{"q":"Why does stretching distort an image?","a":"Because the scaled ratio differs from the original. Lock 'keep ratio' so the other side is computed automatically."},{"q":"What is the difference between 16:9 and 4:3?","a":"16:9 is wider, for modern TV and video; 4:3 is nearer square and was the older standard."},{"q":"How do I make a photo 1:1?","a":"Crop the longer side to the shorter, or enter the original size and target 1:1 to see the crop needed."}]},
"de":{"steps":["Gib Breite und Höhe ein oder wähle ein Preset wie 16:9.","Lege eine Ausgabeseite fest (Breite oder Höhe); die andere ergibt sich aus dem Verhältnis.","Lies die umgerechneten Maße und vergleiche Beschnitte."],
"explanationTitle":"Was ist das Seitenverhältnis?",
"formula":"Breite : Höhe = Ausgabebreite : Ausgabehöhe",
"explanation":["Das Seitenverhältnis ist das Verhältnis von Breite zu Höhe eines Bildes, geschrieben als 'Breite:Höhe'. Beim Skalieren das Verhältnis beibehalten verhindert Verzerrung: Stimmt das Verhältnis, wird nichts gestaucht.","Üblich sind 16:9 (Breitbild), 4:3 (älteres TV) und 1:1 (quadratische Social-Bilder). Richtiges Verhältnis hält Layouts in Postern, Video und mobil konsistent."],
"faq":[{"q":"Warum verzerrt Strecken das Bild?","a":"Weil das neue Verhältnis vom Original abweicht. 'Verhältnis beibehalten' berechnet die andere Seite automatisch."},{"q":"Unterschied 16:9 und 4:3?","a":"16:9 ist breiter (modernes TV/Video); 4:3 näher quadratisch (alter Standard)."},{"q":"Wie mache ich ein Foto 1:1?","a":"Beschneide die längere Seite auf die kürzere, oder gib Original und Ziel 1:1 ein."}]},
"ja":{"steps":["元の幅と高さを入力するか、16:9 などの定番比率を選びます。","出力する一边（幅または高さ）を指定すると、もう一边は比率から自動算出されます。","変換後のサイズを確認し、比率ごとのトリミングを比較できます。"],
"explanationTitle":"アスペクト比とは？",
"formula":"幅 : 高さ = 出力幅 : 出力高さ",
"explanation":["アスペクト比は画面や画像の幅と高さの比で、「幅:高さ」で表します。比率を保って拡大縮小すれば歪みません。出力の両辺の比が元と等しい限り、画像はつぶれも伸びもしません。","一般的な比率は 16:9（ワイド映像）、4:3（旧テレビ）、1:1（正方形の SNS 画像）です。ポスター・動画・スマホレイアウトで正しい比率を設定すると構図が揃います。"],
"faq":[{"q":"なぜ引き伸ばすと歪むのですか？","a":"縮小後の比が元と異なるためです。「比率を固定」にすればもう一边が自動計算されます。"},{"q":"16:9 と 4:3 の違いは？","a":"16:9 はより横長（现代の TV/動画）、4:3 は正方形に近い旧標準です。"},{"q":"写真を 1:1 にするには？","a":"長い辺を短い辺に合わせてトリミングするか、元サイズと目標 1:1 を入力して必要なトリミングを確認します。"}]},
"es":{"steps":["Introduce ancho y alto originales o elige un ajuste común como 16:9.","Indica un lado de salida (ancho o alto); el otro se deduce de la proporción.","Lee las dimensiones convertidas y compara recortes según proporción."],
"explanationTitle":"¿Qué es la relación de aspecto?",
"formula":"ancho : alto = ancho salida : alto salida",
"explanation":["La relación de aspecto es la proporción entre ancho y alto de un encuadre o imagen, escrita como 'ancho:alto'. Escalar manteniendo la proporción evita distorsión: si la salida conserva la proporción, nada se aplasta.","Proporciones comunes: 16:9 (vídeo panorámico), 4:3 (TV antigua) y 1:1 (imágenes cuadradas de redes). Fijar la proporción correcta mantiene la composición coherente."],
"faq":[{"q":"¿Por qué estirar distorsiona la imagen?","a":"Porque la proporción resultante difiere de la original. Bloquea 'mantener proporción' para calcular el otro lado."},{"q":"¿Diferencia entre 16:9 y 4:3?","a":"16:9 es más ancho (TV/vídeo moderno); 4:3 más cuadrado (estándar antiguo)."},{"q":"¿Cómo hago una foto 1:1?","a":"Recorta el lado largo al corto, o introduce el original y el objetivo 1:1 para ver el recorte."}]},
}

G["dpi"] = {
"zh":{"steps":["选择你要算的方向：由尺寸求 DPI，或由 DPI 求打印尺寸。","输入像素尺寸与物理尺寸（或输入 DPI 与目标像素）。","查看 DPI / PPI 结果，并给出打印清晰度建议。"],
"explanationTitle":"DPI 与 PPI 是什么？",
"formula":"DPI = 像素数 ÷ 物理尺寸(英寸)",
"explanation":["DPI（每英寸点数）常用于打印，PPI（每英寸像素）用于屏幕，两者常混用。它表示每英寸长度容纳多少个点/像素，数值越高画面越细腻。","打印照片一般建议 300 DPI 以上，才能保证近距离观看不出现明显颗粒；网页图片 72–96 PPI 即可。若像素不足却强行放大，打印会模糊。"],
"faq":[{"q":"DPI 和 PPI 一样吗？","a":"接近但不完全同：DPI 指打印机喷点密度，PPI 指屏幕像素密度。日常常被当作同义词使用。"},{"q":"打印照片要多少 DPI？","a":"通常 300 DPI 起，画质要求高可用 600；低于 150 DPI 近距离看会有明显颗粒感。"},{"q":"像素小能打印大图吗？","a":"勉强可以，但放得越大越模糊。应先确认目标尺寸下的 DPI 是否达标。"}]},
"zh-TW":{"steps":["選擇你要算的方向：由尺寸求 DPI，或由 DPI 求列印尺寸。","輸入像素尺寸與物理尺寸（或輸入 DPI 與目標像素）。","查看 DPI / PPI 結果，並給出列印清晰度建議。"],
"explanationTitle":"DPI 與 PPI 是什麼？",
"formula":"DPI = 像素數 ÷ 物理尺寸(英寸)",
"explanation":["DPI（每英寸點數）常用於列印，PPI（每英寸像素）用於螢幕，兩者常混用。它表示每英寸長度容納多少個點/像素，數值越高畫面越細膩。","列印照片一般建議 300 DPI 以上，才能保證近距離觀看不出現明顯顆粒；網頁圖片 72–96 PPI 即可。若像素不足卻強行放大，列印會模糊。"],
"faq":[{"q":"DPI 和 PPI 一樣嗎？","a":"接近但不完全同：DPI 指印表機噴點密度，PPI 指螢幕像素密度。日常常被當作同義詞使用。"},{"q":"列印照片要多少 DPI？","a":"通常 300 DPI 起，畫質要求高可用 600；低於 150 DPI 近距離看會有明顯顆粒感。"},{"q":"像素小能列印大圖嗎？","a":"勉強可以，但放得越大越模糊。應先確認目標尺寸下的 DPI 是否達標。"}]},
"en":{"steps":["Choose the direction: size → DPI, or DPI → print size.","Enter pixel dimensions and physical size (or DPI and target pixels).","Read the DPI / PPI and get print sharpness advice."],
"explanationTitle":"What are DPI and PPI?",
"formula":"DPI = pixels ÷ physical size (inches)",
"explanation":["DPI (dots per inch) is used for printing, PPI (pixels per inch) for screens; the terms are often mixed. They express how many dots/pixels fit in one inch — higher means finer detail.","Photos are usually printed at 300 DPI or more so they look sharp up close; web images at 72–96 PPI are fine. Enlarging low-pixel images prints blurry."],
"faq":[{"q":"Are DPI and PPI the same?","a":"Close but not identical: DPI is printer dot density, PPI screen pixel density; everyday use treats them as synonyms."},{"q":"How much DPI for a photo print?","a":"Typically 300 DPI and up, 600 for high quality; below 150 DPI looks grainy up close."},{"q":"Can small pixels print large?","a":"Barely, and the larger you go the blurrier. Check the DPI at your target size first."}]},
"de":{"steps":["Wähle die Richtung: Größe → DPI oder DPI → Druckgröße.","Gib Pixelmaße und physikalische Größe ein (oder DPI und Zielpixel).","Lies DPI / PPI und erhalte Tipps zur Druckschärfe."],
"explanationTitle":"Was sind DPI und PPI?",
"formula":"DPI = Pixel ÷ physikalische Größe (Zoll)",
"explanation":["DPI (Punkte pro Zoll) für Druck, PPI (Pixel pro Zoll) für Bildschirme; oft vermischt. Sie sagen, wie viele Punkte/Pixel pro Zoll passen — höher bedeutet feiner.","Fotos druckt man meist mit 300 DPI oder mehr für scharfe Nahsicht; Webbilder mit 72–96 PPI reichen. Kleine Pixel groß drucken wird unscharf."],
"faq":[{"q":"Sind DPI und PPI gleich?","a":"Ähnlich, aber nicht identisch: DPI ist Druckerpunkt-, PPI Bildschirmpixeldichte; im Alltag Synonyme."},{"q":"Wie viel DPI für Fotodruck?","a":"Meist 300 DPI aufwärts, 600 für hohe Qualität; unter 150 DPI wirkt körnig."},{"q":"Können kleine Pixel groß drucken?","a":"Knapp, und je größer desto unschärfer. Prüfe zuerst den DPI bei Zielgröße."}]},
"ja":{"steps":["計算方向を選びます。サイズ→DPI、または DPI→印刷サイズ。","ピクセル寸法と物理寸法（または DPI と目標ピクセル）を入力します。","DPI / PPI を確認し、印刷の鮮明さのアドバイスを得られます。"],
"explanationTitle":"DPI と PPI とは？",
"formula":"DPI = ピクセル数 ÷ 物理サイズ(インチ)",
"explanation":["DPI（1 インチあたりのドット数）は印刷、PPI（1 インチあたりのピクセル数）は画面で使われ、混同されがちです。1 インチに何ドット/ピクセル入るかを示し、大きいほど精細です。","写真印刷は通常 300 DPI 以上が推奨され、近くで見ても粒状感が出にくいです。Web 画像は 72–96 PPI で十分。像素が少ないのに拡大すると印刷はぼけます。"],
"faq":[{"q":"DPI と PPI は同じ？","a":"近いですが厳密には異なります。DPI はプリンタのドット密度、PPI は画面の像素密度。日常的には同義に使われます。"},{"q":"写真印刷は何 DPI？","a":"通常 300 DPI 以上、高画質なら 600。150 DPI 以下だと近づくと粒状感が目立ちます。"},{"q":"像素が少なくても大判印刷できますか？","a":"無理に拡大するとぼやけます。目標サイズでの DPI が基準を満たすか確認してください。"}]},
"es":{"steps":["Elige la dirección: tamaño → DPI o DPI → tamaño de impresión.","Introduce píxeles y tamaño físico (o DPI y píxeles objetivo).","Lee DPI / PPI y recibe consejo de nitidez de impresión."],
"explanationTitle":"¿Qué son DPI y PPI?",
"formula":"DPI = píxeles ÷ tamaño físico (pulgadas)",
"explanation":["DPI (puntos por pulgada) se usa en impresión, PPI (píxeles por pulgada) en pantallas; a menudo se mezclan. Indican cuántos puntos/píxeles caben en una pulgada: a más, más detalle.","Las fotos suelen imprimirse a 300 DPI o más para verse nítidas de cerca; las web con 72–96 PPI bastan. Agrandar pocos píxeles imprime borroso."],
"faq":[{"q":"¿Son iguales DPI y PPI?","a":"Cercanos pero no idénticos: DPI es densidad de puntos del plotter, PPI de píxeles de pantalla; en el uso diario son sinónimos."},{"q":"¿Cuánto DPI para imprimir fotos?","a":"Normalmente 300 DPI en adelante, 600 para alta calidad; bajo 150 DPI se ve granulado."},{"q":"¿Pueden píxeles pequeños imprimir grande?","a":"Apenas, y cuanto más grande más borroso. Verifica el DPI a tu tamaño objetivo."}]},
}

G["image-filesize"] = {
"zh":{"steps":["选择图像类型：照片(JPEG)、透明图(PNG)、或原始(RAW)。","输入分辨率（长×宽）与预估质量/压缩比。","查看估算文件大小，并对比不同格式的体积差异。"],
"explanationTitle":"图片文件大小怎么估？",
"formula":"字节数 ≈ 像素总数 × 每像素位深 × (1 − 压缩率)",
"explanation":["图像文件大小主要由分辨率、位深与压缩方式决定。一张 1200 万像素的照片，未压缩时数据量巨大；JPEG 通过有损压缩可缩小到几 MB，PNG 无损但体积更大，RAW 则保留全部传感器数据。","同样内容下，JPEG < PNG 通常成立；含大量纯色或文字的图用 PNG 更划算。上传前估算体积，可避免超出平台限制或拖慢加载。"],
"faq":[{"q":"JPEG 和 PNG 哪个更小？","a":"对照片类图像，JPEG 通常远小于 PNG；但纯色/线条图 PNG 可能更小，因为无损压缩对这种内容更高效。"},{"q":"为什么 RAW 文件那么大？","a":"RAW 保留传感器原始数据、未做压缩处理，便于后期，但体积常是 JPEG 的数倍。"},{"q":"分辨率翻倍体积也翻倍吗？","a":"像素数翻倍则未压缩数据翻倍；压缩后增幅略小，但仍明显变大，所以高清图要更注意体积。"}]},
"zh-TW":{"steps":["選擇圖像類型：照片(JPEG)、透明圖(PNG)、或原始(RAW)。","輸入解析度（長×寬）與預估品質/壓縮比。","查看估算檔案大小，並對比不同格式的體積差異。"],
"explanationTitle":"圖片檔案大小怎麼估？",
"formula":"位元組數 ≈ 像素總數 × 每像素位深 × (1 − 壓縮率)",
"explanation":["圖像檔案大小主要由解析度、位深與壓縮方式決定。一張 1200 萬像素的照片，未壓縮時資料量巨大；JPEG 透過有損壓縮可縮小到幾 MB，PNG 無損但體積更大，RAW 則保留全部感測器資料。","同樣內容下，JPEG < PNG 通常成立；含大量純色或文字的圖用 PNG 更划算。上傳前估算體積，可避免超出平台限制或拖慢載入。"],
"faq":[{"q":"JPEG 和 PNG 哪個更小？","a":"對照片類圖像，JPEG 通常遠小於 PNG；但純色/線條圖 PNG 可能更小，因為無損壓縮對這種內容更高效。"},{"q":"為什麼 RAW 檔案那麼大？","a":"RAW 保留感測器原始資料、未做壓縮處理，便於後期，但體積常是 JPEG 的數倍。"},{"q":"解析度翻倍體積也翻倍嗎？","a":"像素數翻倍則未壓縮資料翻倍；壓縮後增幅略小，但仍明顯變大，所以高清圖要更注意體積。"}]},
"en":{"steps":["Pick the image type: photo (JPEG), transparent (PNG) or raw (RAW).","Enter resolution (width × height) and estimated quality/compression.","Read the estimated file size and compare formats."],
"explanationTitle":"How is image file size estimated?",
"formula":"bytes ≈ total pixels × bit depth × (1 − compression)",
"explanation":["Image size is driven by resolution, bit depth and compression. A 12-megapixel photo is huge uncompressed; JPEG's lossy compression shrinks it to a few MB, PNG is lossless but larger, and RAW keeps all sensor data.","Usually JPEG < PNG for photos; but flat/line art is often smaller as PNG because lossless suits it. Estimating size before upload avoids limits and slow loads."],
"faq":[{"q":"Which is smaller, JPEG or PNG?","a":"For photos JPEG is usually far smaller; for flat/line art PNG can win because lossless compression suits that content."},{"q":"Why are RAW files so big?","a":"RAW keeps unprocessed sensor data for editing, often several times the JPEG size."},{"q":"Does doubling resolution double the size?","a":"Uncompressed data doubles; compressed growth is a bit less but still clearly larger, so watch size on hi-res images."}]},
"de":{"steps":["Wähle den Typ: Foto (JPEG), transparent (PNG) oder roh (RAW).","Gib Auflösung (Breite × Höhe) und geschätzte Qualität/Kompression ein.","Lies die geschätzte Dateigröße und vergleiche Formate."],
"explanationTitle":"Wie schätzt man Bilddateigröße?",
"formula":"Bytes ≈ Pixel gesamt × Bitrate × (1 − Kompression)",
"explanation":["Die Größe hängt von Auflösung, Bitrate und Kompression ab. Ein 12-Megapixel-Foto ist unkomprimiert riesig; JPEG schrumpft es verlustbehaftet auf wenige MB, PNG ist verlustfrei größer, RAW behält alle Sensordaten.","Meist gilt JPEG < PNG bei Fotos; bei flachen/Lineart-Bildern ist PNG oft kleiner, da verlustfrei passt. Größe vor Upload schätzen spart Limits und Ladezeit."],
"faq":[{"q":"Was ist kleiner, JPEG oder PNG?","a":"Bei Fotos meist JPEG viel kleiner; bei flachen/Lineart-Bildern kann PNG gewinnen, da verlustfrei passt."},{"q":"Warum sind RAW-Dateien so groß?","a":"RAW behält unkomprimierte Sensordaten fürs Nachbearbeiten, oft ein Mehrfaches der JPEG-Größe."},{"q":"Verdoppelt Auflösung die Größe?","a":"Unkomprimierte Daten verdoppeln sich; komprimiert etwas weniger, aber deutlich größer – bei Hi-Res aufpassen."}]},
"ja":{"steps":["画像の種類を選びます。写真(JPEG)、透過(PNG)、または生(RAW)。","解像度（幅×高さ）と推定品質/圧縮率を入力します。","推定ファイルサイズを確認し、形式ごとの違いを比較できます。"],
"explanationTitle":"画像ファイルサイズの見積もり方",
"formula":"バイト数 ≈ 全像素数 × ビット深度 × (1 − 圧縮率)",
"explanation":["画像サイズは解像度・ビット深度・圧縮方式で決まります。1200 万画素の写真は非圧縮だと巨大です。JPEG は非可逆圧縮で数 MB に、PNG は可逆だが大きく、RAW はセンサー全データを保持します。","写真なら通常 JPEG < PNG ですが、図形・テキスト多めの画像は PNG の方が小さくなることもあります。アップロード前に体積を抑えると、制限超えや読み込み遅延を防げます。"],
"faq":[{"q":"JPEG と PNG どちらが小さい？","a":"写真なら大抵 JPEG がずっと小さいです。しかし図形・線画は PNG（可逆）が有利な場合があります。"},{"q":"なぜ RAW はこんなに大きい？","a":"RAW は後処理のためセンサー生データをそのまま保持し、JPEG の数倍になることが多いです。"},{"q":"解像度を倍にすると体積も倍？","a":"非圧縮なら像素数が倍でデータも倍。圧縮後はやや抑えられますが明らかに大きくなるので注意。"}]},
"es":{"steps":["Elige el tipo: foto (JPEG), transparente (PNG) o crudo (RAW).","Introduce resolución (ancho × alto) y calidad/compresión estimada.","Lee el tamaño estimado y compara formatos."],
"explanationTitle":"¿Cómo se estima el tamaño de imagen?",
"formula":"bytes ≈ píxeles totales × profundidad × (1 − compresión)",
"explanation":["El tamaño depende de resolución, profundidad de bits y compresión. Una foto de 12 megapíxeles es enorme sin comprimir; JPEG la reduce a pocos MB con pérdida, PNG es sin pérdida y mayor, RAW guarda todos los datos del sensor.","Suele cumplirse JPEG < PNG en fotos; pero gráficos/texto planos pueden ser más pequeños en PNG. Estimar antes de subir evita límites y cargas lentas."],
"faq":[{"q":"¿Cuál es menor, JPEG o PNG?","a":"En fotos JPEG suele ser mucho menor; en gráficos planos PNG puede ganar porque la compresión sin pérdida le sienta bien."},{"q":"¿Por qué los RAW son tan grandes?","a":"El RAW guarda datos sin procesar del sensor para edición, a menudo varias veces el tamaño JPEG."},{"q":"¿Duplicar resolución duplica el tamaño?","a":"Los datos sin comprimir se duplican; comprimido crece algo menos pero sigue creciendo mucho, así que vigila en imágenes de alta resolución."}]},
}

G["megapixels"] = {
"zh":{"steps":["输入传感器的宽和高（像素），或选择常见规格。","工具计算总像素并换算为百万像素（MP）。","查看对应可打印尺寸建议（按指定 DPI）。"],
"explanationTitle":"百万像素是什么？",
"formula":"百万像素 = (宽 × 高) ÷ 1,000,000",
"explanation":["百万像素（Megapixel, MP）等于图像总像素数除以一百万，描述相机或图像的解析能力。像素越多，可放大的尺寸越大、细节越丰富。","但像素不是画质的唯一因素：镜头、传感器尺寸与信号处理同样关键。普通网络分享几 MP 足够，打印 A4 照片建议 12–24 MP。"],
"faq":[{"q":"像素越多越清晰吗？","a":"在同等条件下是，但受镜头与传感器大小限制。小传感器堆高像素反而可能噪点更多。"},{"q":"打印需要几 MP？","a":"6×4 英寸快照约 4 MP 够用；A4 打印建议 12 MP 以上，海报级需 24 MP+。"},{"q":"手机几千万像素有用吗？","a":"多数用于多帧合成与裁切，单张直出受光学限制，实际增益有限。"}]},
"zh-TW":{"steps":["輸入感測器的寬和高（像素），或選擇常見規格。","工具計算總像素並換算為百萬像素（MP）。","查看對應可列印尺寸建議（依指定 DPI）。"],
"explanationTitle":"百萬像素是什麼？",
"formula":"百萬像素 = (寬 × 高) ÷ 1,000,000",
"explanation":["百萬像素（Megapixel, MP）等於圖像總像素數除以一百萬，描述相機或圖像的解析能力。像素越多，可放大的尺寸越大、細節越豐富。","但像素不是畫質的唯一因素：鏡頭、感測器尺寸與訊號處理同樣關鍵。普通網路分享幾 MP 足夠，列印 A4 照片建議 12–24 MP。"],
"faq":[{"q":"像素越多越清晰嗎？","a":"在同等條件下是，但受鏡頭與感測器大小限制。小感測器堆高像素反而可能噪點更多。"},{"q":"列印需要幾 MP？","a":"6×4 英寸快照約 4 MP 夠用；A4 列印建議 12 MP 以上，海報級需 24 MP+。"},{"q":"手機幾千萬像素有用嗎？","a":"多數用於多幀合成與裁切，單張直出受光學限制，實際增益有限。"}]},
"en":{"steps":["Enter the sensor width and height in pixels, or pick a common spec.","The tool totals the pixels and converts to megapixels (MP).","See the suggested printable size at a chosen DPI."],
"explanationTitle":"What are megapixels?",
"formula":"megapixels = (width × height) ÷ 1,000,000",
"explanation":["A megapixel (MP) is one million pixels; it describes a camera or image's resolving power. More pixels mean larger possible enlargements and finer detail.","But pixels are not the only quality factor: lens, sensor size and processing matter too. A few MP suffice for web sharing; A4 prints benefit from 12–24 MP."],
"faq":[{"q":"More pixels means sharper?","a":"Up to a point, but lens and sensor size cap it; cramming pixels on a small sensor can add noise."},{"q":"How many MP to print?","a":"A 6×4 snap needs about 4 MP; A4 prints want 12 MP+, posters 24 MP+."},{"q":"Are tens of MP on phones useful?","a":"Mostly for multi-frame fusion and cropping; straight-out shots are limited by optics, so real gain is modest."}]},
"de":{"steps":["Gib Sensobreite und -höhe in Pixeln ein oder wähle eine Spezifikation.","Das Tool summiert die Pixel und rechnet in Megapixel (MP) um.","Sieh den empfohlenen Druck bei gewähltem DPI."],
"explanationTitle":"Was sind Megapixel?",
"formula":"Megapixel = (Breite × Höhe) ÷ 1.000.000",
"explanation":["Ein Megapixel (MP) sind eine Million Pixel; er beschreibt die Auflösung von Kamera oder Bild. Mehr Pixel erlauben größere Vergrößerungen und mehr Detail.","Aber Pixel sind nicht der einzige Qualitätsfaktor: Linse, Sensorgröße und Verarbeitung zählen. Wenige MP reichen fürs Web; A4-Druck will 12–24 MP."],
"faq":[{"q":"Mehr Pixel = schärfer?","a":"Bis zu einer Grenze, danach bremsen Linse und Sensor; viele Pixel auf kleinem Sensor machen Rauschen."},{"q":"Wie viele MP zum Drucken?","a":"Ein 6×4 Bild braucht etwa 4 MP; A4 will 12 MP+, Poster 24 MP+."},{"q":"Bringen Smartphone-MP viel?","a":"Meist für Mehrfachaufnahmen und Beschnitt; directe Fotos sind optisch begrenzt, der Nutzen ist moderat."}]},
"ja":{"steps":["センサーの幅と高さ（像素）を入力するか、よくある仕様を選びます。","工具が総像素を計算し、メガ像素（MP）に換算します。","指定 DPI での印刷可能サイズの目安を確認できます。"],
"explanationTitle":"メガ画素とは？",
"formula":"メガ画素 = (幅 × 高さ) ÷ 1,000,000",
"explanation":["メガ画素（MP）は 100 万画素のことで、カメラや画像の解像力を示します。画素が多いほど大きく引き伸ばせ、細部が豊かになります。","ただし画質は画素だけで決まるわけではなく、レンズ・センサーサイズ・処理も重要です。Web 共有は数 MP で足り、A4 印刷は 12–24 MP が望ましいです。"],
"faq":[{"q":"画素が多いほど鮮明？","a":"条件が同じならそうですが、レンズとセンサーサイズが限界です。小センサーに詰め込むとノイズが増えることも。"},{"q":"印刷には何 MP 必要？","a":"6×4 インチは約 4 MP、A4 は 12 MP 以上、ポスターは 24 MP 以上が目安です。"},{"q":"スマホの数千万画素は意味ある？","a":"多くは多重合成やトリミング用で、そのまま出力は光学で制限されるため実益は限定的です。"}]},
"es":{"steps":["Introduce ancho y alto del sensor en píxeles o elige una especificación.","La herramienta suma los píxeles y los convierte a megapíxeles (MP).","Ve el tamaño imprimible sugerido a un DPI elegido."],
"explanationTitle":"¿Qué son los megapíxeles?",
"formula":"megapíxeles = (ancho × alto) ÷ 1.000.000",
"explanation":["Un megapíxel (MP) son un millón de píxeles; describe el poder de resolución de cámara o imagen. Más píxeles permiten ampliaciones mayores y más detalle.","Pero los píxeles no son el único factor: lente, tamaño de sensor y procesado también cuentan. Pocos MP bastan en web; A4 aprecia 12–24 MP."],
"faq":[{"q":"¿Más píxeles = más nitidez?","a":"Hasta cierto punto; lente y sensor ponen el límite, y apilar píxeles en sensor pequeño puede sumar ruido."},{"q":"¿Cuántos MP para imprimir?","a":"Una foto 6×4 quiere unos 4 MP; A4 unos 12 MP+, pósters 24 MP+."},{"q":"¿Sirven los decenas de MP del móvil?","a":"Mayormente para fusión multi-fotograma y recorte; la foto directa está limitada por la óptica, así que el gain real es modesto."}]},
}

G["age"] = {
"zh":{"steps":["输入出生日期（年/月/日），可含出生时间以更精确。","输入当前日期（默认今天）。","查看精确年龄：岁、月、日，以及已度过的总天数。"],
"explanationTitle":"年龄怎么精确算？",
"formula":"年龄 = 当前日期 − 出生日期（按历法逐段相减）",
"explanation":["精确年龄不是简单用年份相减，而是要处理月份与日期的借位：若当前日小于出生日，需向月份借一位并换算天数。这样得出的岁/月/日才准确。","总天数可用于纪念、保险或法律年龄计算。注意时区与闰年的影响：闰年 2 月 29 日出生的人，在非闰年通常按 2 月 28 日或 3 月 1 日计龄，各地习俗不同。"],
"faq":[{"q":"为什么年份相减不准？","a":"因为没考虑今年生日是否已过。逐段计算月日才能得出真实的岁/月/日。"},{"q":"闰年 2 月 29 日出生怎么算？","a":"非闰年一般按 2 月 28 日或 3 月 1 日计，具体依当地习惯；本工具按通用规则处理。"},{"q":"能算总人数天数吗？","a":"可以，结果会显示从出生到今天经过的总天数，含闰年差异。"}]},
"zh-TW":{"steps":["輸入出生日期（年/月/日），可含出生時間以更精確。","輸入目前日期（預設今天）。","查看精確年齡：歲、月、日，以及已度過的總天數。"],
"explanationTitle":"年齡怎麼精確算？",
"formula":"年齡 = 目前日期 − 出生日期（按曆法逐段相減）",
"explanation":["精確年齡不是簡單用年份相減，而是要處理月份與日期的借位：若目前日小於出生日，需向月份借一位並換算天數。這樣得出的歲/月/日才準確。","總天數可用於紀念、保險或法律年齡計算。注意時區與閏年的影響：閏年 2 月 29 日出生的人，在非閏年通常按 2 月 28 日或 3 月 1 日計齡，各地習俗不同。"],
"faq":[{"q":"為什麼年份相減不準？","a":"因為沒考慮今年生日是否已過。逐段計算月日才能得出真實的歲/月/日。"},{"q":"閏年 2 月 29 日出生怎麼算？","a":"非閏年一般按 2 月 28 日或 3 月 1 日計，具體依當地習慣；本工具按通用規則處理。"},{"q":"能算總人天數嗎？","a":"可以，結果會顯示從出生到今天經過的總天數，含閏年差異。"}]},
"en":{"steps":["Enter the birth date (Y/M/D); add the time for more precision.","Enter the current date (defaults to today).","Read the exact age in years, months, days and total days lived."],
"explanationTitle":"How is age calculated precisely?",
"formula":"age = current date − birth date (calendar-aware subtraction)",
"explanation":["Exact age is not a simple year difference; you must handle borrowing between months and days. If today's day is before the birth day, you borrow from the month and convert to days, giving an accurate years/months/days result.","Total days are useful for milestones, insurance or legal age. Watch time zones and leap years: someone born on 29 Feb is usually counted on 28 Feb or 1 Mar in non-leap years, varying by custom."],
"faq":[{"q":"Why is subtracting years wrong?","a":"It ignores whether this year's birthday has passed. Step-by-step months/days give the true age."},{"q":"Born on 29 Feb in a leap year?","a":"In non-leap years it is usually counted on 28 Feb or 1 Mar depending on custom; the tool follows the common rule."},{"q":"Can it show total days lived?","a":"Yes, the result includes total days from birth to today, with leap-year differences."}]},
"de":{"steps":["Gib das Geburtsdatum (J/M/T) ein; mit Uhrzeit genauer.","Gib das heutige Datum ein (Standard: heute).","Lies das genaue Alter in Jahren, Monaten, Tagen und总 Tagen."],
"explanationTitle":"Wie berechnet man das Alter genau?",
"formula":"Alter = heutiges Datum − Geburtsdatum (kalendergerecht)",
"explanation":["Das genaue Alter ist keine einfache Jahresdifferenz; man muss Monate und Tage übertragen. Ist der heutige Tag vor dem Geburtstag, wird vom Monat geborgt und in Tage umgerechnet.","总 Tage nutzt man für Jubiläen, Versicherungen oder das gesetzliche Alter. Beachte Zeitzonen und Schaltjahre: Am 29.2. Geborene werden im Nicht-Schaltjahr meist am 28.2. oder 1.3. gezählt."],
"faq":[{"q":"Warum stimmt Jahresabzug nicht?","a":"Er ignoriert, ob der Geburtstag schon war. Schrittweise Monate/Tage geben das wahre Alter."},{"q":"Geboren am 29.2. eines Schaltjahrs?","a":"Im Nicht-Schaltjahr meist am 28.2. oder 1.3. je nach Brauch; das Tool folgt der üblichen Regel."},{"q":"Kann es总 Tage zeigen?","a":"Ja, das Ergebnis enthält die总 Tage seit Geburt inkl. Schaltjahre."}]},
"ja":{"steps":["生年月日（年/月/日）を入力します。より正確にするには時刻も。","現在の日付を入力します（初期値は今日）。","正確な年齢（歳・月・日）と、生きてきた総日数を確認できます。"],
"explanationTitle":"年齢の正確な計算方法",
"formula":"年齢 = 現在の日付 − 生年月日（暦を考慮）",
"explanation":["正確な年齢は単なる年差ではなく、月と日の繰り下がりを処理します。今日の日が誕生日より前なら、月から借りて日数に換算します。これで正しい歳・月・日が得られます。","総日数は記念日や保険・法的年齢に使えます。閏年とタイムゾーンに注意：2 月 29 日生まれは平年で 2 月 28 日または 3 月 1 日に数えるのが一般的です（地域により異なる）。"],
"faq":[{"q":"なぜ年を引き算するだけではダメ？","a":"今年の誕生日を過ぎたか考慮していないからです。月日を順に計算して真の年齢を出します。"},{"q":"うるう年 2 月 29 日生まれは？","a":"平年は通常 2 月 28 日または 3 月 1 日に数えます（慣習による）。本ツールは一般的な規則に従います。"},{"q":"生きてきた総日数も出ますか？","a":"はい。生まれてから今日までの総日数を、うるう年差を含めて表示します。"}]},
"es":{"steps":["Introduce la fecha de nacimiento (A/M/D); añade la hora para más precisión.","Introduce la fecha actual (por defecto hoy).","Lee la edad exacta en años, meses, días y días totales vividos."],
"explanationTitle":"¿Cómo se calcula la edad con precisión?",
"formula":"edad = fecha actual − fecha de nacimiento (resta calendario)",
"explanation":["La edad exacta no es una simple resta de años; hay que llevar meses y días. Si el día de hoy es anterior al del cumpleaños, se toma del mes y se convierte a días, dando años/meses/días correctos.","Los días totales sirven para hitos, seguros o edad legal. Ojo con husos y años bisiestos: quien nace 29 feb suele contarse 28 feb o 1 mar en años no bisiestos, según costumbre."],
"faq":[{"q":"¿Por qué restar años falla?","a":"Ignora si el cumpleaños de este año ya pasó. Meses/días paso a paso dan la edad real."},{"q":"¿Nacido el 29 feb de año bisiesto?","a":"En no bisiestos suele contarse 28 feb o 1 mar según costumbre; la herramienta sigue la regla común."},{"q":"¿Muestra días totales vividos?","a":"Sí, el resultado incluye los días totales desde el nacimiento, con años bisiestos."}]},
}

G["day-counter"] = {
"zh":{"steps":["输入起始日期与结束日期（含或不含端点可切换）。","工具自动跨月、跨年计算，处理大小月与闰年。","查看间隔天数，并可换算为周数或工作日天数。"],
"explanationTitle":"两个日期相差多少天？",
"formula":"间隔 = 结束日期的序号 − 起始日期的序号",
"explanation":["日期差的本质是把两个日期转换成「从某个纪元起的第几天」，再相减。这样闰年、大小月都被自然消化，不必手动判断。","常用于合同期限、项目周期、孕期周数或活动倒计时。若只算工作日，需额外排除周末与法定假日。"],
"faq":[{"q":"包含起止日吗？","a":"可在「含端点/不含端点」之间切换。倒计时常用不含，工期统计常用含。"},{"q":"能只算工作日吗？","a":"本工具可给出工作日天数；法定假日因地区而异，需自行剔除。"},{"q":"跨越闰年准确吗？","a":"准确。计算基于真实日历序号，闰年的 2 月 29 日已计入。"}]},
"zh-TW":{"steps":["輸入起始日期與結束日期（含或不含端點可切換）。","工具自動跨月、跨年計算，處理大小月與閏年。","查看間隔天數，並可換算為週數或工作日天數。"],
"explanationTitle":"兩個日期相差多少天？",
"formula":"間隔 = 結束日期的序號 − 起始日期的序號",
"explanation":["日期差的本質是把兩個日期轉換成「從某個紀元起的第幾天」，再相減。這樣閏年、大小月都被自然消化，不必手動判斷。","常用於合約期限、專案週期、孕期週數或活動倒數。若只算工作日，需額外排除週末與法定假日。"],
"faq":[{"q":"包含起止日嗎？","a":"可在「含端點/不含端點」之間切換。倒數計時常用不含，工期統計常用含。"},{"q":"能只算工作日嗎？","a":"本工具可給出工作日天數；法定假日因地區而異，需自行剔除。"},{"q":"跨越閏年準確嗎？","a":"準確。計算基於真實日曆序號，閏年的 2 月 29 日已計入。"}]},
"en":{"steps":["Enter the start and end dates; toggle whether endpoints are included.","The tool spans months and years, handling short/long months and leap years.","Read the day gap and convert it to weeks or working days."],
"explanationTitle":"How many days between two dates?",
"formula":"gap = end ordinal − start ordinal",
"explanation":["A date difference converts each date to its 'day number since an epoch' and subtracts. Leap years and month lengths are handled naturally, no manual rules needed.","It is used for contract terms, project cycles, pregnancy weeks or event countdowns. Working days need weekends and public holidays excluded."],
"faq":[{"q":"Are endpoints included?","a":"Toggle 'include/exclude endpoints'. Countdowns usually exclude; schedules usually include."},{"q":"Can it count only workdays?","a":"The tool can give working-day counts; public holidays vary by region and must be removed manually."},{"q":"Accurate across leap years?","a":"Yes. It uses true calendar ordinals, including 29 Feb."}]},
"de":{"steps":["Gib Start- und Enddatum ein; wähle, ob Endpunkte zählen.","Das Tool überbrückt Monate/Jahre und behandelt Schaltjahre.","Lies die Tage und rechne in Wochen oder Arbeitstage um."],
"explanationTitle":"Wie viele Tage zwischen zwei Daten?",
"formula":"Abstand = Endordinal − Startordinal",
"explanation":["Eine Datumsdifferenz wandelt jedes Datum in seine 'Tagesnummer ab Epoche' und zieht ab. Schaltjahre und Monatslängen sind automatisch enthalten.","Nützlich für Vertragslaufzeiten, Projektzyklen, Schwangerschaftswochen oder Countdowns. Arbeitstage brauchen Wochenenden und Feiertage abzüglich."],
"faq":[{"q":"Zählen Endpunkte?","a":"Umschaltbar 'inkl./exkl. Endpunkte'. Countdowns meist exkl., Pläne meist inkl."},{"q":"Nur Arbeitstage zählbar?","a":"Das Tool liefert Arbeitstage; Feiertage variieren regional und müssen manuell abgezogen werden."},{"q":"Genau über Schaltjahre?","a":"Ja. Es nutzt echte Kalenderordinalzahlen inkl. 29. Feb."}]},
"ja":{"steps":["開始日と終了日を入力します。端点数え込みの切り替え可。","月や年をまたぎ、大小月・閏年も自動処理します。","日数の差を確認し、週数や営業日数に換算できます。"],
"explanationTitle":"2 つの日付の日数差",
"formula":"差 = 終了日の通算番号 − 開始日の通算番号",
"explanation":["日付差は各日付を「ある紀元からの通算日数」に変換して引き算します。閏年や月の大小は自然に処理され、手動ルールは不要です。","契約期間・プロジェクト・妊娠週数・イベントのカウントダウンに使います。営業日は週末と祝日を除く必要があります。"],
"faq":[{"q":"開始・終了日は含みますか？","a":"「含む/含まない」を切り替えられます。カウントダウンは含まず、工期は含むのが一般的です。"},{"q":"営業日だけ数えられますか？","a":"本ツールは営業日数も出せます。祝日は地域により異なり手動で除いてください。"},{"q":"閏年をまたいでも正確？","a":"正確です。実際の暦の通算番号を用いており 2 月 29 日も含みます。"}]},
"es":{"steps":["Introduce inicio y fin; alterna si los extremos cuentan.","La herramienta cruza meses y años y maneja bisiestos.","Lee la diferencia en días y conviértela a semanas o laborables."],
"explanationTitle":"¿Cuántos días entre dos fechas?",
"formula":"diferencia = ordinal fin − ordinal inicio",
"explanation":["La diferencia convierte cada fecha en su 'número de día desde una época' y resta. Bisiestos y largos de mes se manejan solos.","Sirve para plazos de contrato, ciclos de proyecto, semanas de embarazo o cuentas atrás. Los laborables exigen quitar fines de semana y festivos."],
"faq":[{"q":"¿Cuentan los extremos?","a":"Conmutable 'incluir/excluir extremos'. Cuentas atrás suelen excluir; cronogramas incluir."},{"q":"¿Solo días laborables?","a":"La herramienta da laborables; los festivos varían por región y hay que quitarlos a mano."},{"q":"¿Preciso en años bisiestos?","a":"Sí. Usa ordinales reales del calendario, incluido 29 feb."}]},
}

G["time-zone"] = {
"zh":{"steps":["选择源时区与目标时区（支持主要城市与 UTC 偏移）。","输入要转换的本地时间。","查看目标时区对应时间，并标注是否处于夏令时。"],
"explanationTitle":"时区转换怎么算？",
"formula":"目标时间 = 源时间 + (目标偏移 − 源偏移)",
"explanation":["地球按经度划分 24 个时区，相邻时区相差 1 小时。转换时用目标时区与源时区的 UTC 偏移之差加到原时间上即可。","夏令时（DST）会让部分地区在夏季把时钟拨快 1 小时，导致偏移临时变化。跨国会议、航班与远程协作都要先确认双方是否处于夏令时。"],
"faq":[{"q":"什么是 UTC 偏移？","a":"UTC 偏移表示该时区相对协调世界时（UTC）的小时差，如北京为 UTC+8、伦敦冬季为 UTC+0。"},{"q":"夏令时会影响转换吗？","a":"会。实行夏令时的地区在夏季偏移 +1 小时，转换时务必勾选对应日期是否已生效。"},{"q":"为什么同一国家有多个时区？","a":"幅员辽阔的国家（如美国、俄罗斯）横跨多个经度，自然划分出若干时区。"}]},
"zh-TW":{"steps":["選擇源時區與目標時區（支援主要城市與 UTC 偏移）。","輸入要轉換的本地時間。","查看目標時區對應時間，並標註是否處於夏令時。"],
"explanationTitle":"時區轉換怎麼算？",
"formula":"目標時間 = 源時間 + (目標偏移 − 源偏移)",
"explanation":["地球按經度劃分 24 個時區，相鄰時區相差 1 小時。轉換時用目標時區與源時區的 UTC 偏移之差加到原時間上即可。","夏令時（DST）會讓部分地區在夏季把時鐘撥快 1 小時，導致偏移暫時變化。跨國會議、航班與遠端協作都要先確認雙方是否處於夏令時。"],
"faq":[{"q":"什麼是 UTC 偏移？","a":"UTC 偏移表示該時區相對協調世界時（UTC）的小時差，如北京為 UTC+8、倫敦冬季為 UTC+0。"},{"q":"夏令時會影響轉換嗎？","a":"會。實行夏令時的地區在夏季偏移 +1 小時，轉換時務必勾選對應日期是否已生效。"},{"q":"為什麼同一國家有多個時區？","a":"幅員遼闊的國家（如美國、俄羅斯）橫跨多個經度，自然劃分出若干時區。"}]},
"en":{"steps":["Pick the source and target time zones (major cities and UTC offsets).","Enter the local time to convert.","Read the target time and whether daylight saving is in effect."],
"explanationTitle":"How are time zones converted?",
"formula":"target = source + (target offset − source offset)",
"explanation":["Earth is split into 24 time zones by longitude, each an hour apart. To convert, add the difference between the target and source UTC offsets to the original time.","Daylight Saving Time (DST) moves clocks forward one hour in summer for some regions, changing the offset temporarily. Cross-border meetings, flights and remote work must check DST on both sides."],
"faq":[{"q":"What is a UTC offset?","a":"It is the hour difference from Coordinated Universal Time; e.g. Beijing is UTC+8, London winter is UTC+0."},{"q":"Does DST affect conversion?","a":"Yes. Regions on DST shift +1 hour in summer, so confirm the date's status when converting."},{"q":"Why do some countries have many zones?","a":"Large countries (USA, Russia) span several longitudes and naturally split into zones."}]},
"de":{"steps":["Wähle Quell- und Zielzeitzone (Städte und UTC-Offsets).","Gib die umzurechnende Ortszeit ein.","Lies die Zielzeit und ob Sommerzeit gilt."],
"explanationTitle":"Wie rechnet man Zeitzonen um?",
"formula":"Ziel = Quelle + (Zieloffset − Quelloffset)",
"explanation":["Die Erde ist in 24 Zonen je eine Stunde geteilt. Man addiert die Differenz der UTC-Offsets von Ziel und Quelle zur Ausgangszeit.","Die Sommerzeit (DST) stellt Uhren im Sommer eine Stunde vor, der Offset ändert sich temporär. Grenzüberschreitende Meetings, Flüge und Remotearbeit müssen DST prüfen."],
"faq":[{"q":"Was ist ein UTC-Offset?","a":"Die Stundendifferenz zu UTC; Peking ist UTC+8, London Winter UTC+0."},{"q":"Beeinflusst DST die Umrechnung?","a":"Ja. Regionen mit DST sind im Sommer +1 Stunde; datumsspezifisch prüfen."},{"q":"Warum mehrere Zonen in einem Land?","a":"Große Länder (USA, Russland) spannen viele Längengrade und teilen sich natürlich auf."}]},
"ja":{"steps":["元のタイムゾーンと宛先を選びます（主要都市と UTC オフセット対応）。","変換する現地時刻を入力します。","宛先の時刻と、夏時間中かどうかを確認できます。"],
"explanationTitle":"タイムゾーンの変換方法",
"formula":"宛先 = 元 + (宛先オフセット − 元オフセット)",
"explanation":["地球は経度で 24 のタイムゾーンに分かれ、隣同士は 1 時間違います。変換は宛先と元の UTC オフセット差を元の時刻に加えます。","夏時間（DST）は一部地域で夏季に時計を 1 時間進め、オフセットが一時的に変わります。国際会議・フライト・リモートでは双方の DST を確認してください。"],
"faq":[{"q":"UTC オフセットとは？","a":"UTC からの時間差です。北京は UTC+8、ロンドン冬は UTC+0 など。"},{"q":"夏時間は影響しますか？","a":"します。DST 地域は夏に +1 時間になるため、日付ごとに状態を確認してください。"},{"q":"なぜ同じ国に複数のゾーンがある？","a":"米国やロシアのように広大な国は複数の経度をまたぐため、自然に複数ゾーンに分かれます。"}]},
"es":{"steps":["Elige zona origen y destino (ciudades y offsets UTC).","Introduce la hora local a convertir.","Lee la hora destino y si rige el horario de verano."],
"explanationTitle":"¿Cómo se convierten husos horarios?",
"formula":"destino = origen + (offset destino − offset origen)",
"explanation":["La Tierra se divide en 24 husos por longitud, cada uno una hora. Para convertir sumas la diferencia de offsets UTC de destino y origen a la hora original.","El horario de verano (DST) adelanta el reloj una hora en verano en algunas regiones, cambiando el offset temporalmente. Reuniones, vuelos y teletrabajo deben comprobar DST en ambos lados."],
"faq":[{"q":"¿Qué es un offset UTC?","a":"La diferencia de horas con el Tiempo Universal Coordinado; Pekín es UTC+8, Londres invierno UTC+0."},{"q":"¿Afecta el horario de verano?","a":"Sí. Las regiones con DST suman +1 en verano; confirma el estado según la fecha."},{"q":"¿Por qué un país tiene varias zonas?","a":"Países grandes (EE. UU., Rusia) cubren varias longitudes y se dividen naturalmente."}]},
}

G["subnet-calculator"] = {
"zh":{"steps":["输入 IP 地址与子网掩码（或 CIDR 前缀，如 /24）。","工具解析网络地址、广播地址与可用主机范围。","查看总主机数、可用主机数与二进制对照。"],
"explanationTitle":"子网与 CIDR 是什么？",
"formula":"主机数 = 2^(32 − 前缀) − 2（减去网络号与广播地址）",
"explanation":["IPv4 地址是 32 位，子网掩码标出其中多少位用于网络、多少位用于主机。CIDR 用「/数字」表示网络位长度，例如 /24 表示前 24 位是网络号，后 8 位是主机位。","每个子网要扣除网络地址和广播地址这两个特殊地址，所以可用主机数 = 2^主机位 − 2。合理划分子网能减少广播风暴、提升地址利用率。"],
"faq":[{"q":"/24 有多少个可用 IP？","a":"主机位 8 位，共 256 个地址，减去网络与广播，可用 254 个。"},{"q":"为什么可用数要减 2？","a":"因为网络地址（全 0）和广播地址（全 1）不能分配给主机。"},{"q":"CIDR 和子网掩码关系？","a":"CIDR 前缀就是掩码中连续 1 的个数。/24 等价于 255.255.255.0。"}]},
"zh-TW":{"steps":["輸入 IP 位址與子網路遮罩（或 CIDR 前綴，如 /24）。","工具解析網路位址、廣播位址與可用主機範圍。","查看總主機數、可用主機數與二進位對照。"],
"explanationTitle":"子網與 CIDR 是什麼？",
"formula":"主機數 = 2^(32 − 前綴) − 2（減去網路號與廣播位址）",
"explanation":["IPv4 位址是 32 位元，子網路遮罩標出其中多少位用於網路、多少位用於主機。CIDR 用「/數字」表示網路位長度，例如 /24 表示前 24 位元是網路號，後 8 位元是主機位。","每個子網要扣除網路位址和廣播位址這兩個特殊位址，所以可用主機數 = 2^主機位 − 2。合理劃分子網能減少廣播風暴、提升位址利用率。"],
"faq":[{"q":"/24 有多少個可用 IP？","a":"主機位 8 位元，共 256 個位址，減去網路與廣播，可用 254 個。"},{"q":"為什麼可用數要減 2？","a":"因為網路位址（全 0）和廣播位址（全 1）不能分配給主機。"},{"q":"CIDR 和子網路遮罩關係？","a":"CIDR 前綴就是遮罩中連續 1 的個數。/24 等價於 255.255.255.0。"}]},
"en":{"steps":["Enter the IP address and subnet mask (or CIDR prefix like /24).","The tool derives the network address, broadcast address and usable host range.","Read total hosts, usable hosts and the binary view."],
"explanationTitle":"What are subnets and CIDR?",
"formula":"hosts = 2^(32 − prefix) − 2 (minus network and broadcast)",
"explanation":["An IPv4 address is 32 bits; the subnet mask marks how many bits are network and how many are host. CIDR writes the network length as '/number', e.g. /24 means the first 24 bits are network, the last 8 are host.","Each subnet loses the network and broadcast addresses, so usable hosts = 2^hostbits − 2. Good subnetting cuts broadcast storms and improves address use."],
"faq":[{"q":"How many usable IPs in /24?","a":"8 host bits → 256 addresses; minus network and broadcast leaves 254 usable."},{"q":"Why subtract 2?","a":"The network address (all 0s) and broadcast (all 1s) cannot be assigned to hosts."},{"q":"CIDR vs subnet mask?","a":"The CIDR prefix is the count of consecutive 1s in the mask. /24 equals 255.255.255.0."}]},
"de":{"steps":["Gib IP und Subnetzmaske ein (oder CIDR-Präfix wie /24).","Das Tool ermittelt Netz-, Broadcast-Adresse und nutzbaren Bereich.","Lies Gesamt-, nutzbare Hosts und die Binäransicht."],
"explanationTitle":"Was sind Subnetze und CIDR?",
"formula":"Hosts = 2^(32 − Präfix) − 2 (ohne Netz- und Broadcast)",
"explanation":["Eine IPv4-Adresse hat 32 Bit; die Maske trennt Netz- und Host-Bits. CIDR schreibt die Netzlänge als '/Zahl', z. B. bedeutet /24: 24 Netzbits, 8 Hostbits.","Jedes Subnetz verliert Netz- und Broadcast-Adresse, also nutzbare Hosts = 2^Hostbits − 2. Gute Unterteilung mindert Broadcast-Stürme."],
"faq":[{"q":"Wie viele IPs in /24 nutzbar?","a":"8 Hostbits → 256 Adressen; abzüglich Netz/Broadcast bleiben 254."},{"q":"Warum −2?","a":"Netzadresse (alle 0) und Broadcast (alle 1) sind für Hosts gesperrt."},{"q":"CIDR vs Maske?","a":"Das CIDR-Präfix ist die Zahl der aufeinanderfolgenden 1en. /24 = 255.255.255.0."}]},
"ja":{"steps":["IP アドレスとサブネットマスク（または /24 のような CIDR プレフィックス）を入力します。","ネットワークアドレス・ブロードキャストアドレス・利用可能ホスト範囲を算出します。","ホスト総数・利用可能数・バイナリ表示を確認できます。"],
"explanationTitle":"サブネットと CIDR とは？",
"formula":"ホスト数 = 2^(32 − プレフィックス) − 2（ネットワーク/ブロードキャスト分を減算）",
"explanation":["IPv4 アドレスは 32 ビットで、サブネットマスクがどこまでがネットワーク部かを示します。CIDR は「/数字」でネットワーク長を表し、/24 なら上位 24 ビットがネットワーク、下位 8 ビットがホストです。","各サブネットではネットワークアドレスとブロードキャストアドレスの 2 つが使えないため、利用可能ホスト数 = 2^ホストビット − 2 です。適切な分割はブロードキャストストームを減らします。"],
"faq":[{"q":"/24 の利用可能 IP は？","a":"ホストビット 8 で 256 アドレス。ネット/ブロードキャストを引き 254 が利用可能です。"},{"q":"なぜ 2 を引く？","a":"ネットワーク（全 0）とブロードキャスト（全 1）はホストに割り当てられないためです。"},{"q":"CIDR とサブネットマスクの関係は？","a":"CIDR プレフィックスはマスク中の連続する 1 の個数です。/24 は 255.255.255.0 に等しいです。"}]},
"es":{"steps":["Introduce IP y máscara (o prefijo CIDR como /24).","La herramienta deduce red, broadcast y rango de hosts usables.","Lee hosts totales, usables y la vista binaria."],
"explanationTitle":"¿Qué son subredes y CIDR?",
"formula":"hosts = 2^(32 − prefijo) − 2 (menos red y broadcast)",
"explanation":["Una IPv4 tiene 32 bits; la máscara marca cuántos son de red y cuántos de host. CIDR escribe la longitud de red como '/número'; /24 son 24 bits de red y 8 de host.","Cada subred pierde la dirección de red y la de broadcast, así que hosts usables = 2^hostbits − 2. Una buena división reduce tormentas de broadcast."],
"faq":[{"q":"¿Cuántas IP usables en /24?","a":"8 bits de host → 256 direcciones; menos red y broadcast quedan 254."},{"q":"¿Por qué restar 2?","a":"La de red (todo 0) y la de broadcast (todo 1) no se asignan a hosts."},{"q":"¿CIDR vs máscara?","a":"El prefijo CIDR es la cuenta de 1s seguidas en la máscara. /24 equivale a 255.255.255.0."}]},
}

G["url-encoder"] = {
"zh":{"steps":["粘贴需要编码的 URL 或查询字符串。","选择编码方式：百分号编码（URL encode）或解码。","查看编码结果，特殊字符被安全转义为 %XX 形式。"],
"explanationTitle":"URL 编码是什么？",
"formula":"空格 → %20；中文/特殊字符 → UTF-8 字节的 %XX 序列",
"explanation":["URL 只能安全包含少数字符（字母、数字和少数符号）。空格、中文、&、= 等字符在网址中有特殊含义或无法传输，必须用百分号编码转义为 % 加两位十六进制。","编码后链接才能被正确解析与传输，避免参数被截断或注入。解码则是逆向过程，把 %XX 还原为原字符。表单提交、API 调用与拼接查询参数时常会用到。"],
"faq":[{"q":"为什么空格变成 %20？","a":"空格不是 URL 安全字符，标准编码为 %20（也有用 + 表示表单空格的变体）。"},{"q":"中文为什么要编码？","a":"URL 基于 ASCII，中文需先按 UTF-8 转成字节再逐字节 %XX 编码，接收方再解码还原。"},{"q":"编码会丢失信息吗？","a":"不会。编码是可逆的，解码后即可完整还原原始字符串。"}]},
"zh-TW":{"steps":["貼上需要編碼的 URL 或查詢字串。","選擇編碼方式：百分號編碼（URL encode）或解碼。","查看編碼結果，特殊字元被安全轉義為 %XX 形式。"],
"explanationTitle":"URL 編碼是什麼？",
"formula":"空格 → %20；中文/特殊字元 → UTF-8 位元組的 %XX 序列",
"explanation":["URL 只能安全包含少數字元（字母、數字和少數符號）。空格、中文、&、= 等字元在網址中有特殊含義或無法傳輸，必須用百分號編碼轉義為 % 加兩位十六進位。","編碼後連結才能被正確解析與傳輸，避免參數被截斷或注入。解碼則是逆向過程，把 %XX 還原為原字元。表單提交、API 呼叫與拼接查詢參數時常會用到。"],
"faq":[{"q":"為什麼空格變成 %20？","a":"空格不是 URL 安全字元，標準編碼為 %20（也有用 + 表示表單空格的變體）。"},{"q":"中文為什麼要編碼？","a":"URL 基於 ASCII，中文需先按 UTF-8 轉成位元組再逐位元組 %XX 編碼，接收方再解碼還原。"},{"q":"編碼會遺失資訊嗎？","a":"不會。編碼是可逆的，解碼後即可完整還原原始字串。"}]},
"en":{"steps":["Paste the URL or query string to encode.","Choose percent-encoding (URL encode) or decode.","Read the result where unsafe characters become %XX escapes."],
"explanationTitle":"What is URL encoding?",
"formula":"space → %20; non-ASCII → UTF-8 bytes as %XX",
"explanation":["A URL may safely contain only a few characters (letters, digits and a few symbols). Spaces, Chinese text, & and = have special meaning or cannot travel, so they must be escaped as % followed by two hex digits.","Encoding lets links parse and transmit correctly, avoiding truncated parameters or injection. Decoding reverses it, turning %XX back to the original. It appears in form posts, API calls and query building."],
"faq":[{"q":"Why does space become %20?","a":"Space is not URL-safe; the standard escape is %20 (a + variant exists for form spaces)."},{"q":"Why encode Chinese?","a":"URLs are ASCII-based; Chinese is first turned into UTF-8 bytes, then each byte into %XX, and decoded back on receipt."},{"q":"Does encoding lose information?","a":"No. It is reversible; decoding restores the exact original string."}]},
"de":{"steps":["Füge die zu kodierende URL oder Query ein.","Wähle Prozentkodierung (URL-Encode) oder Dekodierung.","Lies das Ergebnis, bei dem unsichere Zeichen als %XX erscheinen."],
"explanationTitle":"Was ist URL-Kodierung?",
"formula":"Leerzeichen → %20; Nicht-ASCII → UTF-8-Bytes als %XX",
"explanation":["Eine URL darf nur wenige Zeichen sicher enthalten (Buchstaben, Ziffern, wenige Symbole). Leerzeichen, Chinesisch, & und = haben Sonderbedeutung oder lassen sich nicht übertragen und werden als % plus zwei Hexziffern maskiert.","Kodierung lässt Links korrekt parsen und übertragen, ohne Parameter abzuschneiden. Dekodieren kehrt es um. Man braucht es bei Formularen, APIs und Queries."],
"faq":[{"q":"Warum wird Leerzeichen %20?","a":"Leerzeichen ist nicht URL-sicher; Standard-Escape ist %20 (Formulare nutzen auch +)."},{"q":"Warum Chinesisch kodieren?","a":"URLs sind ASCII; Chinesisch wird erst UTF-8-Bytes, dann je Byte %XX, beim Empfang decodiert."},{"q":"Geht Information verloren?","a":"Nein. Es ist umkehrbar; Dekodieren stellt den Originaltext exakt her."}]},
"ja":{"steps":["エンコードしたい URL やクエリ文字列を貼り付けます。","パーセントエンコード（URL エンコード）かデコードを選びます。","結果を確認でき、不安全な文字は %XX にエスケープされます。"],
"explanationTitle":"URL エンコードとは？",
"formula":"空白 → %20；非 ASCII → UTF-8 バイトを %XX に",
"explanation":["URL で安全に扱えるのは一部の文字（英数字と少数の記号）だけです。空白や中文、&、= は意味を持つか転送できないため、% と 2 桁の 16 進数にエスケープします。","エンコードによりリンクが正しく解析・送信され、パラメータの截断や注入を防げます。デコードはその逆で %XX を元に戻します。フォーム送信や API 呼び出しで頻出します。"],
"faq":[{"q":"なぜ空白が %20 になる？","a":"空白は URL 安全ではないためで、標準エスケープは %20 です（フォームでは + も）。"},{"q":"中文はなぜエンコードする？","a":"URL は ASCII ベースのため、中文は UTF-8 バイトに変換してから %XX 化し、受信側で復元します。"},{"q":"エンコードで情報は失われる？","a":"失われません。可逆であり、デコードで元の文字列に戻ります。"}]},
"es":{"steps":["Pega la URL o la cadena de consulta a codificar.","Elige codificación porcentual (URL encode) o decodificación.","Lee el resultado donde los caracteres inseguros son %XX."],
"explanationTitle":"¿Qué es la codificación URL?",
"formula":"espacio → %20; no ASCII → bytes UTF-8 como %XX",
"explanation":["Una URL solo admite de forma segura pocos caracteres (letras, dígitos y pocos símbolos). Espacios, chino, & y = tienen significado especial o no viajan, así que se escapan como % y dos dígitos hex.","Codificar permite que los enlaces se analicen y transmitan bien, sin truncar parámetros ni inyección. Decodificar invierte el proceso. Aparece en formularios, APIs y consultas."],
"faq":[{"q":"¿Por qué el espacio se vuelve %20?","a":"El espacio no es seguro en URL; el escape estándar es %20 (en formularios también +)."},{"q":"¿Por qué codificar el chino?","a":"Las URL son ASCII; el chino se vuelve bytes UTF-8 y luego %XX, y se decodifica al recibirse."},{"q":"¿Pierde información la codificación?","a":"No. Es reversible; decodificar restaura la cadena original exacta."}]},
}

G["download-calculator"] = {
"zh":{"steps":["输入文件大小（如 500 MB）与你的下载带宽（如 100 Mbps）。","注意单位：带宽常用 Mbps（兆比特/秒），文件用 MB（兆字节）。","查看预计下载时间，并对比不同带宽下的耗时。"],
"explanationTitle":"下载时间怎么估算？",
"formula":"时间(秒) = 文件字节数 × 8 ÷ 带宽(bps)",
"explanation":["下载时间等于数据总比特数除以传输速率。关键陷阱是单位：带宽标称的 100 Mbps 是「兆比特/秒」，而文件大小用「兆字节 MB」，1 字节 = 8 比特，所以实际速度要除以 8。","真实耗时还会受网络开销、服务器限速、Wi-Fi 衰减影响，通常比理论值慢 10%–30%。本工具给出理论下限，便于你规划等待时间。"],
"faq":[{"q":"Mbps 和 MB 一样吗？","a":"不一样。Mbps 是兆比特/秒，MB 是兆字节；1 MB = 8 Mb。带宽标号几乎都用小写 b（比特）。"},{"q":"为什么实际比计算慢？","a":"有协议开销、服务器限速、无线信号衰减等，通常慢 10%–30%。"},{"q":"怎么让下载更快？","a":"用有线连接、靠近路由器、避开高峰，或升级带宽；本工具可帮你估算不同带宽的耗时。"}]},
"zh-TW":{"steps":["輸入檔案大小（如 500 MB）與你的下載頻寬（如 100 Mbps）。","注意單位：頻寬常用 Mbps（兆位元/秒），檔案用 MB（兆位元組）。","查看預計下載時間，並對比不同頻寬下的耗時。"],
"explanationTitle":"下載時間怎麼估算？",
"formula":"時間(秒) = 檔案位元組數 × 8 ÷ 頻寬(bps)",
"explanation":["下載時間等於資料總位元數除以傳輸速率。關鍵陷阱是單位：頻寬標稱的 100 Mbps 是「兆位元/秒」，而檔案大小用「兆位元組 MB」，1 位元組 = 8 位元，所以實際速度要除以 8。","真實耗時還會受網路開銷、伺服器限速、Wi-Fi 衰减影響，通常比理論值慢 10%–30%。本工具給出理論下限，便於你規劃等待時間。"],
"faq":[{"q":"Mbps 和 MB 一樣嗎？","a":"不一樣。Mbps 是兆位元/秒，MB 是兆位元組；1 MB = 8 Mb。頻寬標號幾乎都用小寫 b（位元）。"},{"q":"為什麼實際比計算慢？","a":"有協定開銷、伺服器限速、無線訊號衰减等，通常慢 10%–30%。"},{"q":"怎麼讓下載更快？","a":"用有線連接、靠近路由器、避開高峰，或升級頻寬；本工具可幫你估算不同頻寬的耗時。"}]},
"en":{"steps":["Enter the file size (e.g. 500 MB) and your download bandwidth (e.g. 100 Mbps).","Mind the units: bandwidth is Mbps (megabits/s), files are MB (megabytes).","Read the estimated download time and compare across bandwidths."],
"explanationTitle":"How is download time estimated?",
"formula":"time(s) = file bytes × 8 ÷ bandwidth(bps)",
"explanation":["Download time is total bits divided by transfer rate. The key trap is units: a '100 Mbps' plan is megabits per second, while files use megabytes, and 1 byte = 8 bits, so real speed is divided by 8.","Real time is also hit by protocol overhead, server throttling and Wi-Fi loss, typically 10%–30% slower than theory. The tool gives the theoretical floor to plan your wait."],
"faq":[{"q":"Are Mbps and MB the same?","a":"No. Mbps is megabits per second, MB is megabytes; 1 MB = 8 Mb. Plans almost always use lowercase b (bits)."},{"q":"Why is real download slower?","a":"Protocol overhead, server throttling and wireless loss add 10%–30%."},{"q":"How to download faster?","a":"Use wired, stay near the router, avoid peaks or upgrade bandwidth; the tool estimates time per bandwidth."}]},
"de":{"steps":["Gib Dateigröße (z. B. 500 MB) und Bandbreite (z. B. 100 Mbps) ein.","Achte auf Einheiten: Bandbreite in Mbps (Megabit/s), Dateien in MB (Megabyte).","Lies die geschätzte Zeit und vergleiche Bandbreiten."],
"explanationTitle":"Wie schätzt man Downloadzeit?",
"formula":"Zeit(s) = Dateibytes × 8 ÷ Bandbreite(bps)",
"explanation":["Downloadzeit ist die Gesamtzahl der Bits durch die Übertragungsrate. Die Falle sind Einheiten: '100 Mbps' sind Megabit pro Sekunde, Dateien nutzen Megabyte, und 1 Byte = 8 Bit, also echte Speed ÷ 8.","Realität bremst durch Protokoll-Overhead, Server-Limits und WLAN-Verlust, meist 10–30 % langsamer. Das Tool liefert die Untergrenze zum Planen."],
"faq":[{"q":"Mbps und MB gleich?","a":"Nein. Mbps sind Megabit/s, MB Megabyte; 1 MB = 8 Mb. Tarife nutzen fast immer kleines b (Bit)."},{"q":"Warum real langsamer?","a":"Overhead, Server-Drosselung und WLAN-Verlust addieren 10–30 %."},{"q":"Wie schneller downloaden?","a":"Kabel nutzen, näher am Router, Spitzen meiden oder Bandbreite erhöhen; das Tool schätzt pro Bandbreite."}]},
"ja":{"steps":["ファイルサイズ（例 500 MB）とダウンロード帯域（例 100 Mbps）を入力します。","単位に注意：帯域は Mbps（メガビット/秒）、ファイルは MB（メガバイト）。","推定ダウンロード時間を確認し、帯域ごとの違いを比較できます。"],
"explanationTitle":"ダウンロード時間の見積もり方",
"formula":"時間(秒) = ファイルバイト数 × 8 ÷ 帯域(bps)",
"explanation":["ダウンロード時間は全ビット数を転送レートで割ったものです。罠は単位：「100 Mbps」はメガビット/秒ですが、ファイルはメガバイト。1 バイト = 8 ビットなので実速度は 8 で割ります。","実際はプロトコルオーバーヘッド・サーバー制限・Wi-Fi 減衰で、理論値より 10–30% 遅くなります。本ツールは計画用の理論下限を出します。"],
"faq":[{"q":"Mbps と MB は同じ？","a":"違います。Mbps はメガビット/秒、MB はメガバイトで 1 MB = 8 Mb。回線表記はほぼ小文字 b（ビット）です。"},{"q":"なぜ実測は計算より遅い？","a":"プロトコルオーバーヘッドやサーバー制限、無線減衰で通常 10–30% 遅くなります。"},{"q":"ダウンロードを速くするには？","a":"有線接続、ルーター近く、混雑回避、または帯域増強を。本ツールで帯域ごとの時間を推定できます。"}]},
"es":{"steps":["Introduce el tamaño (p. ej. 500 MB) y tu ancho de banda (p. ej. 100 Mbps).","Ojo con unidades: el ancho es Mbps (megabits/s), los archivos MB (megabytes).","Lee el tiempo estimado y compáralo entre anchos de banda."],
"explanationTitle":"¿Cómo se estima el tiempo de descarga?",
"formula":"tiempo(s) = bytes archivo × 8 ÷ ancho(bps)",
"explanation":["El tiempo es el total de bits dividido por la tasa de transferencia. La trampa son las unidades: '100 Mbps' son megabits por segundo, pero los archivos usan megabytes y 1 byte = 8 bits, así que la velocidad real se divide entre 8.","La realidad añade overhead de protocolo, límites del servidor y pérdida Wi-Fi, típicamente 10–30 % más lenta. La herramienta da el suelo teórico para planear."],
"faq":[{"q":"¿Mbps y MB son iguales?","a":"No. Mbps son megabits por segundo, MB megabytes; 1 MB = 8 Mb. Las tarifas casi siempre usan b minúscula (bits)."},{"q":"¿Por qué la realidad es más lenta?","a":"Overhead, límites del servidor y pérdida inalámbrica suman 10–30 %."},{"q":"¿Cómo descargar más rápido?","a":"Usa cable, acércate al router, evita picos o sube ancho; la herramienta estima por ancho."}]},
}

# ---- 写入 6 个语言文件 ----
for loc in LOCALES:
    path = os.path.join(BASE, f"{loc}.json")
    with open(path, "r", encoding="utf-8") as f:
        d = json.load(f)
    conv = d.setdefault("converter", {})
    n = 0
    for tid, langs in G.items():
        if loc not in langs:
            continue
        conv.setdefault(tid, {})["guide"] = langs[loc]
        n += 1
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    print(f"{loc}: wrote {n} guides -> {path}")

print("DONE total tools:", len(G))
