// Emoji Character Reference

export interface EmojiEntry {
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
  unicode: string;
  htmlEntity: string;
}

export const EMOJI_CATEGORIES = [
  "smileys",
  "people",
  "animals",
  "food",
  "activities",
  "travel",
  "objects",
  "symbols",
  "flags",
] as const;

export type EmojiCategory = (typeof EMOJI_CATEGORIES)[number];

export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys
  {
    emoji: "\u{1F600}",
    name: "grinning",
    category: "smileys",
    keywords: ["happy", "smile", "joy"],
    unicode: "U+1F600",
    htmlEntity: "&#128512;",
  },
  {
    emoji: "\u{1F601}",
    name: "beaming",
    category: "smileys",
    keywords: ["happy", "smile", "eyes"],
    unicode: "U+1F601",
    htmlEntity: "&#128513;",
  },
  {
    emoji: "\u{1F602}",
    name: "joy",
    category: "smileys",
    keywords: ["laugh", "cry", "lol"],
    unicode: "U+1F602",
    htmlEntity: "&#128514;",
  },
  {
    emoji: "\u{1F603}",
    name: "smiley",
    category: "smileys",
    keywords: ["happy", "smile", "open"],
    unicode: "U+1F603",
    htmlEntity: "&#128515;",
  },
  {
    emoji: "\u{1F604}",
    name: "smile",
    category: "smileys",
    keywords: ["happy", "eyes", "grin"],
    unicode: "U+1F604",
    htmlEntity: "&#128516;",
  },
  {
    emoji: "\u{1F605}",
    name: "sweat smile",
    category: "smileys",
    keywords: ["hot", "happy", "nervous"],
    unicode: "U+1F605",
    htmlEntity: "&#128517;",
  },
  {
    emoji: "\u{1F606}",
    name: "laughing",
    category: "smileys",
    keywords: ["happy", "lol", "satisfied"],
    unicode: "U+1F606",
    htmlEntity: "&#128518;",
  },
  {
    emoji: "\u{1F609}",
    name: "wink",
    category: "smileys",
    keywords: ["flirt", "playful", "secret"],
    unicode: "U+1F609",
    htmlEntity: "&#128521;",
  },
  {
    emoji: "\u{1F60A}",
    name: "blush",
    category: "smileys",
    keywords: ["happy", "shy", "smile"],
    unicode: "U+1F60A",
    htmlEntity: "&#128522;",
  },
  {
    emoji: "\u{1F60D}",
    name: "heart eyes",
    category: "smileys",
    keywords: ["love", "crush", "adore"],
    unicode: "U+1F60D",
    htmlEntity: "&#128525;",
  },
  {
    emoji: "\u{1F618}",
    name: "kissing heart",
    category: "smileys",
    keywords: ["love", "kiss", "flirt"],
    unicode: "U+1F618",
    htmlEntity: "&#128536;",
  },
  {
    emoji: "\u{1F914}",
    name: "thinking",
    category: "smileys",
    keywords: ["hmm", "consider", "ponder"],
    unicode: "U+1F914",
    htmlEntity: "&#129300;",
  },
  {
    emoji: "\u{1F60E}",
    name: "sunglasses",
    category: "smileys",
    keywords: ["cool", "summer", "confident"],
    unicode: "U+1F60E",
    htmlEntity: "&#128526;",
  },
  {
    emoji: "\u{1F62D}",
    name: "crying",
    category: "smileys",
    keywords: ["sad", "sob", "upset"],
    unicode: "U+1F62D",
    htmlEntity: "&#128557;",
  },
  {
    emoji: "\u{1F621}",
    name: "angry",
    category: "smileys",
    keywords: ["mad", "rage", "furious"],
    unicode: "U+1F621",
    htmlEntity: "&#128545;",
  },
  {
    emoji: "\u{1F631}",
    name: "scream",
    category: "smileys",
    keywords: ["scared", "horror", "shocked"],
    unicode: "U+1F631",
    htmlEntity: "&#128561;",
  },

  // People
  {
    emoji: "\u{1F44D}",
    name: "thumbs up",
    category: "people",
    keywords: ["yes", "good", "approve"],
    unicode: "U+1F44D",
    htmlEntity: "&#128077;",
  },
  {
    emoji: "\u{1F44E}",
    name: "thumbs down",
    category: "people",
    keywords: ["no", "bad", "disapprove"],
    unicode: "U+1F44E",
    htmlEntity: "&#128078;",
  },
  {
    emoji: "\u{1F44F}",
    name: "clap",
    category: "people",
    keywords: ["applause", "bravo", "congrats"],
    unicode: "U+1F44F",
    htmlEntity: "&#128079;",
  },
  {
    emoji: "\u{1F64F}",
    name: "pray",
    category: "people",
    keywords: ["please", "hope", "thanks"],
    unicode: "U+1F64F",
    htmlEntity: "&#128591;",
  },
  {
    emoji: "\u{1F4AA}",
    name: "muscle",
    category: "people",
    keywords: ["strong", "flex", "power"],
    unicode: "U+1F4AA",
    htmlEntity: "&#128170;",
  },
  {
    emoji: "\u{270B}",
    name: "raised hand",
    category: "people",
    keywords: ["stop", "high five", "wave"],
    unicode: "U+270B",
    htmlEntity: "&#9995;",
  },
  {
    emoji: "\u{1F44B}",
    name: "wave",
    category: "people",
    keywords: ["hello", "goodbye", "hi"],
    unicode: "U+1F44B",
    htmlEntity: "&#128075;",
  },
  {
    emoji: "\u{1F918}",
    name: "rock on",
    category: "people",
    keywords: ["metal", "rock", "cool"],
    unicode: "U+1F918",
    htmlEntity: "&#129304;",
  },

  // Animals
  {
    emoji: "\u{1F436}",
    name: "dog",
    category: "animals",
    keywords: ["pet", "puppy", "woof"],
    unicode: "U+1F436",
    htmlEntity: "&#128054;",
  },
  {
    emoji: "\u{1F431}",
    name: "cat",
    category: "animals",
    keywords: ["pet", "kitten", "meow"],
    unicode: "U+1F431",
    htmlEntity: "&#128049;",
  },
  {
    emoji: "\u{1F42D}",
    name: "mouse",
    category: "animals",
    keywords: ["animal", "rodent", "cheese"],
    unicode: "U+1F42D",
    htmlEntity: "&#128045;",
  },
  {
    emoji: "\u{1F430}",
    name: "rabbit",
    category: "animals",
    keywords: ["bunny", "pet", "easter"],
    unicode: "U+1F430",
    htmlEntity: "&#128048;",
  },
  {
    emoji: "\u{1F43B}",
    name: "bear",
    category: "animals",
    keywords: ["animal", "teddy", "grizzly"],
    unicode: "U+1F43B",
    htmlEntity: "&#128059;",
  },
  {
    emoji: "\u{1F981}",
    name: "lion",
    category: "animals",
    keywords: ["king", "wild", "safari"],
    unicode: "U+1F981",
    htmlEntity: "&#129409;",
  },
  {
    emoji: "\u{1F984}",
    name: "unicorn",
    category: "animals",
    keywords: ["magic", "fantasy", "horse"],
    unicode: "U+1F984",
    htmlEntity: "&#129412;",
  },
  {
    emoji: "\u{1F98B}",
    name: "butterfly",
    category: "animals",
    keywords: ["insect", "beautiful", "nature"],
    unicode: "U+1F98B",
    htmlEntity: "&#129419;",
  },

  // Food
  {
    emoji: "\u{1F34E}",
    name: "apple",
    category: "food",
    keywords: ["fruit", "red", "healthy"],
    unicode: "U+1F34E",
    htmlEntity: "&#127822;",
  },
  {
    emoji: "\u{1F355}",
    name: "pizza",
    category: "food",
    keywords: ["food", "italian", "slice"],
    unicode: "U+1F355",
    htmlEntity: "&#127829;",
  },
  {
    emoji: "\u{1F354}",
    name: "burger",
    category: "food",
    keywords: ["food", "fast food", "hamburger"],
    unicode: "U+1F354",
    htmlEntity: "&#127828;",
  },
  {
    emoji: "\u{1F35F}",
    name: "fries",
    category: "food",
    keywords: ["food", "fast food", "chips"],
    unicode: "U+1F35F",
    htmlEntity: "&#127839;",
  },
  {
    emoji: "\u{2615}",
    name: "coffee",
    category: "food",
    keywords: ["drink", "caffeine", "morning"],
    unicode: "U+2615",
    htmlEntity: "&#9749;",
  },
  {
    emoji: "\u{1F37A}",
    name: "beer",
    category: "food",
    keywords: ["drink", "alcohol", "cheers"],
    unicode: "U+1F37A",
    htmlEntity: "&#127866;",
  },
  {
    emoji: "\u{1F370}",
    name: "cake",
    category: "food",
    keywords: ["dessert", "birthday", "sweet"],
    unicode: "U+1F370",
    htmlEntity: "&#127856;",
  },
  {
    emoji: "\u{1F36B}",
    name: "chocolate",
    category: "food",
    keywords: ["sweet", "candy", "dessert"],
    unicode: "U+1F36B",
    htmlEntity: "&#127851;",
  },

  // Activities
  {
    emoji: "\u{26BD}",
    name: "soccer",
    category: "activities",
    keywords: ["sport", "football", "ball"],
    unicode: "U+26BD",
    htmlEntity: "&#9917;",
  },
  {
    emoji: "\u{1F3C0}",
    name: "basketball",
    category: "activities",
    keywords: ["sport", "ball", "nba"],
    unicode: "U+1F3C0",
    htmlEntity: "&#127936;",
  },
  {
    emoji: "\u{1F3C8}",
    name: "football",
    category: "activities",
    keywords: ["sport", "american", "nfl"],
    unicode: "U+1F3C8",
    htmlEntity: "&#127944;",
  },
  {
    emoji: "\u{1F3AE}",
    name: "video game",
    category: "activities",
    keywords: ["gaming", "controller", "play"],
    unicode: "U+1F3AE",
    htmlEntity: "&#127918;",
  },
  {
    emoji: "\u{1F3B5}",
    name: "music",
    category: "activities",
    keywords: ["note", "song", "sound"],
    unicode: "U+1F3B5",
    htmlEntity: "&#127925;",
  },
  {
    emoji: "\u{1F3A4}",
    name: "microphone",
    category: "activities",
    keywords: ["sing", "karaoke", "music"],
    unicode: "U+1F3A4",
    htmlEntity: "&#127908;",
  },
  {
    emoji: "\u{1F3AC}",
    name: "clapper",
    category: "activities",
    keywords: ["movie", "film", "action"],
    unicode: "U+1F3AC",
    htmlEntity: "&#127916;",
  },
  {
    emoji: "\u{1F3A8}",
    name: "palette",
    category: "activities",
    keywords: ["art", "paint", "creative"],
    unicode: "U+1F3A8",
    htmlEntity: "&#127912;",
  },

  // Travel
  {
    emoji: "\u{2708}",
    name: "airplane",
    category: "travel",
    keywords: ["travel", "fly", "flight"],
    unicode: "U+2708",
    htmlEntity: "&#9992;",
  },
  {
    emoji: "\u{1F697}",
    name: "car",
    category: "travel",
    keywords: ["vehicle", "drive", "transport"],
    unicode: "U+1F697",
    htmlEntity: "&#128663;",
  },
  {
    emoji: "\u{1F680}",
    name: "rocket",
    category: "travel",
    keywords: ["space", "launch", "fast"],
    unicode: "U+1F680",
    htmlEntity: "&#128640;",
  },
  {
    emoji: "\u{1F6A2}",
    name: "ship",
    category: "travel",
    keywords: ["boat", "cruise", "sea"],
    unicode: "U+1F6A2",
    htmlEntity: "&#128674;",
  },
  {
    emoji: "\u{1F3D6}",
    name: "beach",
    category: "travel",
    keywords: ["vacation", "summer", "island"],
    unicode: "U+1F3D6",
    htmlEntity: "&#127958;",
  },
  {
    emoji: "\u{1F5FC}",
    name: "tokyo tower",
    category: "travel",
    keywords: ["japan", "landmark", "travel"],
    unicode: "U+1F5FC",
    htmlEntity: "&#128508;",
  },
  {
    emoji: "\u{1F30D}",
    name: "globe",
    category: "travel",
    keywords: ["earth", "world", "planet"],
    unicode: "U+1F30D",
    htmlEntity: "&#127757;",
  },
  {
    emoji: "\u{2600}",
    name: "sun",
    category: "travel",
    keywords: ["weather", "sunny", "bright"],
    unicode: "U+2600",
    htmlEntity: "&#9728;",
  },

  // Objects
  {
    emoji: "\u{1F4BB}",
    name: "laptop",
    category: "objects",
    keywords: ["computer", "work", "tech"],
    unicode: "U+1F4BB",
    htmlEntity: "&#128187;",
  },
  {
    emoji: "\u{1F4F1}",
    name: "phone",
    category: "objects",
    keywords: ["mobile", "cell", "smartphone"],
    unicode: "U+1F4F1",
    htmlEntity: "&#128241;",
  },
  {
    emoji: "\u{1F4D6}",
    name: "book",
    category: "objects",
    keywords: ["read", "study", "knowledge"],
    unicode: "U+1F4D6",
    htmlEntity: "&#128214;",
  },
  {
    emoji: "\u{1F4A1}",
    name: "lightbulb",
    category: "objects",
    keywords: ["idea", "bright", "innovation"],
    unicode: "U+1F4A1",
    htmlEntity: "&#128161;",
  },
  {
    emoji: "\u{1F511}",
    name: "key",
    category: "objects",
    keywords: ["lock", "security", "access"],
    unicode: "U+1F511",
    htmlEntity: "&#128273;",
  },
  {
    emoji: "\u{1F50D}",
    name: "magnifying",
    category: "objects",
    keywords: ["search", "zoom", "find"],
    unicode: "U+1F50D",
    htmlEntity: "&#128269;",
  },
  {
    emoji: "\u{1F4E7}",
    name: "email",
    category: "objects",
    keywords: ["mail", "message", "inbox"],
    unicode: "U+1F4E7",
    htmlEntity: "&#128231;",
  },
  {
    emoji: "\u{1F4B0}",
    name: "money bag",
    category: "objects",
    keywords: ["rich", "wealth", "cash"],
    unicode: "U+1F4B0",
    htmlEntity: "&#128176;",
  },

  // Symbols
  {
    emoji: "\u{2764}",
    name: "red heart",
    category: "symbols",
    keywords: ["love", "like", "romance"],
    unicode: "U+2764",
    htmlEntity: "&#10084;",
  },
  {
    emoji: "\u{1F494}",
    name: "broken heart",
    category: "symbols",
    keywords: ["sad", "breakup", "hurt"],
    unicode: "U+1F494",
    htmlEntity: "&#128148;",
  },
  {
    emoji: "\u{2705}",
    name: "check",
    category: "symbols",
    keywords: ["yes", "done", "complete"],
    unicode: "U+2705",
    htmlEntity: "&#9989;",
  },
  {
    emoji: "\u{274C}",
    name: "cross mark",
    category: "symbols",
    keywords: ["no", "wrong", "delete"],
    unicode: "U+274C",
    htmlEntity: "&#10060;",
  },
  {
    emoji: "\u{2B50}",
    name: "star",
    category: "symbols",
    keywords: ["favorite", "rating", "gold"],
    unicode: "U+2B50",
    htmlEntity: "&#11088;",
  },
  {
    emoji: "\u{1F525}",
    name: "fire",
    category: "symbols",
    keywords: ["hot", "lit", "trending"],
    unicode: "U+1F525",
    htmlEntity: "&#128293;",
  },
  {
    emoji: "\u{1F4AF}",
    name: "100",
    category: "symbols",
    keywords: ["perfect", "score", "complete"],
    unicode: "U+1F4AF",
    htmlEntity: "&#128175;",
  },
  {
    emoji: "\u{26A0}",
    name: "warning",
    category: "symbols",
    keywords: ["alert", "caution", "danger"],
    unicode: "U+26A0",
    htmlEntity: "&#9888;",
  },

  // Flags
  {
    emoji: "\u{1F1FA}\u{1F1F8}",
    name: "usa",
    category: "flags",
    keywords: ["america", "united states", "us"],
    unicode: "U+1F1FA U+1F1F8",
    htmlEntity: "&#127482;&#127480;",
  },
  {
    emoji: "\u{1F1EC}\u{1F1E7}",
    name: "uk",
    category: "flags",
    keywords: ["britain", "england", "british"],
    unicode: "U+1F1EC U+1F1E7",
    htmlEntity: "&#127468;&#127463;",
  },
  {
    emoji: "\u{1F1EB}\u{1F1F7}",
    name: "france",
    category: "flags",
    keywords: ["french", "paris", "europe"],
    unicode: "U+1F1EB U+1F1F7",
    htmlEntity: "&#127467;&#127479;",
  },
  {
    emoji: "\u{1F1E9}\u{1F1EA}",
    name: "germany",
    category: "flags",
    keywords: ["german", "berlin", "europe"],
    unicode: "U+1F1E9 U+1F1EA",
    htmlEntity: "&#127465;&#127466;",
  },
  {
    emoji: "\u{1F1EF}\u{1F1F5}",
    name: "japan",
    category: "flags",
    keywords: ["japanese", "tokyo", "asia"],
    unicode: "U+1F1EF U+1F1F5",
    htmlEntity: "&#127471;&#127477;",
  },
  {
    emoji: "\u{1F1E8}\u{1F1F3}",
    name: "china",
    category: "flags",
    keywords: ["chinese", "beijing", "asia"],
    unicode: "U+1F1E8 U+1F1F3",
    htmlEntity: "&#127464;&#127475;",
  },
  {
    emoji: "\u{1F1E7}\u{1F1F7}",
    name: "brazil",
    category: "flags",
    keywords: ["brazilian", "south america"],
    unicode: "U+1F1E7 U+1F1F7",
    htmlEntity: "&#127463;&#127479;",
  },
  {
    emoji: "\u{1F1E8}\u{1F1E6}",
    name: "canada",
    category: "flags",
    keywords: ["canadian", "maple"],
    unicode: "U+1F1E8 U+1F1E6",
    htmlEntity: "&#127464;&#127462;",
  },
];

export function getEmojiByCategory(category: EmojiCategory): EmojiEntry[] {
  return EMOJI_DATA.filter((e) => e.category === category);
}

export function searchEmoji(query: string): EmojiEntry[] {
  const q = query.toLowerCase();
  return EMOJI_DATA.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.keywords.some((k) => k.toLowerCase().includes(q)) ||
      e.emoji === query
  );
}

export function getEmojiUnicode(emoji: string): string {
  return [...emoji]
    .map((char) => `U+${char.codePointAt(0)?.toString(16).toUpperCase().padStart(4, "0")}`)
    .join(" ");
}

export function emojiToHTMLEntity(emoji: string): string {
  return [...emoji].map((char) => `&#${char.codePointAt(0)};`).join("");
}
