// HTML Character Entity Reference

export interface HTMLCharEntity {
  char: string;
  name: string;
  entity: string;
  decimal: number;
  hex: string;
  category: string;
  description: string;
}

export const HTML_CHAR_CATEGORIES = [
  "punctuation",
  "currency",
  "math",
  "arrows",
  "symbols",
  "greek",
  "latin",
  "spacing",
] as const;

export type HTMLCharCategory = (typeof HTML_CHAR_CATEGORIES)[number];

export const HTML_CHAR_ENTITIES: HTMLCharEntity[] = [
  // Punctuation
  {
    char: "&",
    name: "amp",
    entity: "&amp;",
    decimal: 38,
    hex: "26",
    category: "punctuation",
    description: "Ampersand",
  },
  {
    char: "<",
    name: "lt",
    entity: "&lt;",
    decimal: 60,
    hex: "3C",
    category: "punctuation",
    description: "Less than",
  },
  {
    char: ">",
    name: "gt",
    entity: "&gt;",
    decimal: 62,
    hex: "3E",
    category: "punctuation",
    description: "Greater than",
  },
  {
    char: '"',
    name: "quot",
    entity: "&quot;",
    decimal: 34,
    hex: "22",
    category: "punctuation",
    description: "Quotation mark",
  },
  {
    char: "'",
    name: "apos",
    entity: "&#39;",
    decimal: 39,
    hex: "27",
    category: "punctuation",
    description: "Apostrophe",
  },
  {
    char: "\u2026",
    name: "hellip",
    entity: "&hellip;",
    decimal: 8230,
    hex: "2026",
    category: "punctuation",
    description: "Horizontal ellipsis",
  },
  {
    char: "\u2014",
    name: "mdash",
    entity: "&mdash;",
    decimal: 8212,
    hex: "2014",
    category: "punctuation",
    description: "Em dash",
  },
  {
    char: "\u2013",
    name: "ndash",
    entity: "&ndash;",
    decimal: 8211,
    hex: "2013",
    category: "punctuation",
    description: "En dash",
  },
  {
    char: "\u2018",
    name: "lsquo",
    entity: "&lsquo;",
    decimal: 8216,
    hex: "2018",
    category: "punctuation",
    description: "Left single quote",
  },
  {
    char: "\u2019",
    name: "rsquo",
    entity: "&rsquo;",
    decimal: 8217,
    hex: "2019",
    category: "punctuation",
    description: "Right single quote",
  },
  {
    char: "\u201c",
    name: "ldquo",
    entity: "&ldquo;",
    decimal: 8220,
    hex: "201C",
    category: "punctuation",
    description: "Left double quote",
  },
  {
    char: "\u201d",
    name: "rdquo",
    entity: "&rdquo;",
    decimal: 8221,
    hex: "201D",
    category: "punctuation",
    description: "Right double quote",
  },
  {
    char: "\u00ab",
    name: "laquo",
    entity: "&laquo;",
    decimal: 171,
    hex: "AB",
    category: "punctuation",
    description: "Left angle quote",
  },
  {
    char: "\u00bb",
    name: "raquo",
    entity: "&raquo;",
    decimal: 187,
    hex: "BB",
    category: "punctuation",
    description: "Right angle quote",
  },

  // Currency
  {
    char: "\u20ac",
    name: "euro",
    entity: "&euro;",
    decimal: 8364,
    hex: "20AC",
    category: "currency",
    description: "Euro sign",
  },
  {
    char: "\u00a3",
    name: "pound",
    entity: "&pound;",
    decimal: 163,
    hex: "A3",
    category: "currency",
    description: "Pound sign",
  },
  {
    char: "\u00a5",
    name: "yen",
    entity: "&yen;",
    decimal: 165,
    hex: "A5",
    category: "currency",
    description: "Yen sign",
  },
  {
    char: "\u00a2",
    name: "cent",
    entity: "&cent;",
    decimal: 162,
    hex: "A2",
    category: "currency",
    description: "Cent sign",
  },
  {
    char: "\u00a4",
    name: "curren",
    entity: "&curren;",
    decimal: 164,
    hex: "A4",
    category: "currency",
    description: "Currency sign",
  },

  // Math
  {
    char: "\u00b1",
    name: "plusmn",
    entity: "&plusmn;",
    decimal: 177,
    hex: "B1",
    category: "math",
    description: "Plus-minus",
  },
  {
    char: "\u00d7",
    name: "times",
    entity: "&times;",
    decimal: 215,
    hex: "D7",
    category: "math",
    description: "Multiplication",
  },
  {
    char: "\u00f7",
    name: "divide",
    entity: "&divide;",
    decimal: 247,
    hex: "F7",
    category: "math",
    description: "Division",
  },
  {
    char: "\u2260",
    name: "ne",
    entity: "&ne;",
    decimal: 8800,
    hex: "2260",
    category: "math",
    description: "Not equal",
  },
  {
    char: "\u2264",
    name: "le",
    entity: "&le;",
    decimal: 8804,
    hex: "2264",
    category: "math",
    description: "Less or equal",
  },
  {
    char: "\u2265",
    name: "ge",
    entity: "&ge;",
    decimal: 8805,
    hex: "2265",
    category: "math",
    description: "Greater or equal",
  },
  {
    char: "\u221e",
    name: "infin",
    entity: "&infin;",
    decimal: 8734,
    hex: "221E",
    category: "math",
    description: "Infinity",
  },
  {
    char: "\u00b2",
    name: "sup2",
    entity: "&sup2;",
    decimal: 178,
    hex: "B2",
    category: "math",
    description: "Superscript 2",
  },
  {
    char: "\u00b3",
    name: "sup3",
    entity: "&sup3;",
    decimal: 179,
    hex: "B3",
    category: "math",
    description: "Superscript 3",
  },
  {
    char: "\u00bd",
    name: "frac12",
    entity: "&frac12;",
    decimal: 189,
    hex: "BD",
    category: "math",
    description: "Fraction 1/2",
  },
  {
    char: "\u00bc",
    name: "frac14",
    entity: "&frac14;",
    decimal: 188,
    hex: "BC",
    category: "math",
    description: "Fraction 1/4",
  },
  {
    char: "\u00be",
    name: "frac34",
    entity: "&frac34;",
    decimal: 190,
    hex: "BE",
    category: "math",
    description: "Fraction 3/4",
  },
  {
    char: "\u221a",
    name: "radic",
    entity: "&radic;",
    decimal: 8730,
    hex: "221A",
    category: "math",
    description: "Square root",
  },
  {
    char: "\u2211",
    name: "sum",
    entity: "&sum;",
    decimal: 8721,
    hex: "2211",
    category: "math",
    description: "Sum",
  },
  {
    char: "\u220f",
    name: "prod",
    entity: "&prod;",
    decimal: 8719,
    hex: "220F",
    category: "math",
    description: "Product",
  },

  // Arrows
  {
    char: "\u2190",
    name: "larr",
    entity: "&larr;",
    decimal: 8592,
    hex: "2190",
    category: "arrows",
    description: "Left arrow",
  },
  {
    char: "\u2192",
    name: "rarr",
    entity: "&rarr;",
    decimal: 8594,
    hex: "2192",
    category: "arrows",
    description: "Right arrow",
  },
  {
    char: "\u2191",
    name: "uarr",
    entity: "&uarr;",
    decimal: 8593,
    hex: "2191",
    category: "arrows",
    description: "Up arrow",
  },
  {
    char: "\u2193",
    name: "darr",
    entity: "&darr;",
    decimal: 8595,
    hex: "2193",
    category: "arrows",
    description: "Down arrow",
  },
  {
    char: "\u2194",
    name: "harr",
    entity: "&harr;",
    decimal: 8596,
    hex: "2194",
    category: "arrows",
    description: "Left-right arrow",
  },
  {
    char: "\u21b5",
    name: "crarr",
    entity: "&crarr;",
    decimal: 8629,
    hex: "21B5",
    category: "arrows",
    description: "Carriage return",
  },
  {
    char: "\u21d0",
    name: "lArr",
    entity: "&lArr;",
    decimal: 8656,
    hex: "21D0",
    category: "arrows",
    description: "Double left arrow",
  },
  {
    char: "\u21d2",
    name: "rArr",
    entity: "&rArr;",
    decimal: 8658,
    hex: "21D2",
    category: "arrows",
    description: "Double right arrow",
  },

  // Symbols
  {
    char: "\u00a9",
    name: "copy",
    entity: "&copy;",
    decimal: 169,
    hex: "A9",
    category: "symbols",
    description: "Copyright",
  },
  {
    char: "\u00ae",
    name: "reg",
    entity: "&reg;",
    decimal: 174,
    hex: "AE",
    category: "symbols",
    description: "Registered",
  },
  {
    char: "\u2122",
    name: "trade",
    entity: "&trade;",
    decimal: 8482,
    hex: "2122",
    category: "symbols",
    description: "Trademark",
  },
  {
    char: "\u00b0",
    name: "deg",
    entity: "&deg;",
    decimal: 176,
    hex: "B0",
    category: "symbols",
    description: "Degree",
  },
  {
    char: "\u00b6",
    name: "para",
    entity: "&para;",
    decimal: 182,
    hex: "B6",
    category: "symbols",
    description: "Paragraph",
  },
  {
    char: "\u00a7",
    name: "sect",
    entity: "&sect;",
    decimal: 167,
    hex: "A7",
    category: "symbols",
    description: "Section",
  },
  {
    char: "\u2020",
    name: "dagger",
    entity: "&dagger;",
    decimal: 8224,
    hex: "2020",
    category: "symbols",
    description: "Dagger",
  },
  {
    char: "\u2021",
    name: "Dagger",
    entity: "&Dagger;",
    decimal: 8225,
    hex: "2021",
    category: "symbols",
    description: "Double dagger",
  },
  {
    char: "\u2022",
    name: "bull",
    entity: "&bull;",
    decimal: 8226,
    hex: "2022",
    category: "symbols",
    description: "Bullet",
  },
  {
    char: "\u2665",
    name: "hearts",
    entity: "&hearts;",
    decimal: 9829,
    hex: "2665",
    category: "symbols",
    description: "Heart",
  },
  {
    char: "\u2660",
    name: "spades",
    entity: "&spades;",
    decimal: 9824,
    hex: "2660",
    category: "symbols",
    description: "Spade",
  },
  {
    char: "\u2666",
    name: "diams",
    entity: "&diams;",
    decimal: 9830,
    hex: "2666",
    category: "symbols",
    description: "Diamond",
  },
  {
    char: "\u2663",
    name: "clubs",
    entity: "&clubs;",
    decimal: 9827,
    hex: "2663",
    category: "symbols",
    description: "Club",
  },
  {
    char: "\u2713",
    name: "check",
    entity: "&#10003;",
    decimal: 10003,
    hex: "2713",
    category: "symbols",
    description: "Check mark",
  },
  {
    char: "\u2717",
    name: "cross",
    entity: "&#10007;",
    decimal: 10007,
    hex: "2717",
    category: "symbols",
    description: "Cross mark",
  },
  {
    char: "\u2605",
    name: "star",
    entity: "&#9733;",
    decimal: 9733,
    hex: "2605",
    category: "symbols",
    description: "Black star",
  },

  // Greek
  {
    char: "\u03b1",
    name: "alpha",
    entity: "&alpha;",
    decimal: 945,
    hex: "3B1",
    category: "greek",
    description: "Greek alpha",
  },
  {
    char: "\u03b2",
    name: "beta",
    entity: "&beta;",
    decimal: 946,
    hex: "3B2",
    category: "greek",
    description: "Greek beta",
  },
  {
    char: "\u03b3",
    name: "gamma",
    entity: "&gamma;",
    decimal: 947,
    hex: "3B3",
    category: "greek",
    description: "Greek gamma",
  },
  {
    char: "\u03b4",
    name: "delta",
    entity: "&delta;",
    decimal: 948,
    hex: "3B4",
    category: "greek",
    description: "Greek delta",
  },
  {
    char: "\u03b5",
    name: "epsilon",
    entity: "&epsilon;",
    decimal: 949,
    hex: "3B5",
    category: "greek",
    description: "Greek epsilon",
  },
  {
    char: "\u03c0",
    name: "pi",
    entity: "&pi;",
    decimal: 960,
    hex: "3C0",
    category: "greek",
    description: "Greek pi",
  },
  {
    char: "\u03c3",
    name: "sigma",
    entity: "&sigma;",
    decimal: 963,
    hex: "3C3",
    category: "greek",
    description: "Greek sigma",
  },
  {
    char: "\u03c9",
    name: "omega",
    entity: "&omega;",
    decimal: 969,
    hex: "3C9",
    category: "greek",
    description: "Greek omega",
  },
  {
    char: "\u0394",
    name: "Delta",
    entity: "&Delta;",
    decimal: 916,
    hex: "394",
    category: "greek",
    description: "Greek capital delta",
  },
  {
    char: "\u03a3",
    name: "Sigma",
    entity: "&Sigma;",
    decimal: 931,
    hex: "3A3",
    category: "greek",
    description: "Greek capital sigma",
  },
  {
    char: "\u03a9",
    name: "Omega",
    entity: "&Omega;",
    decimal: 937,
    hex: "3A9",
    category: "greek",
    description: "Greek capital omega",
  },

  // Spacing
  {
    char: " ",
    name: "nbsp",
    entity: "&nbsp;",
    decimal: 160,
    hex: "A0",
    category: "spacing",
    description: "Non-breaking space",
  },
  {
    char: "\u2003",
    name: "emsp",
    entity: "&emsp;",
    decimal: 8195,
    hex: "2003",
    category: "spacing",
    description: "Em space",
  },
  {
    char: "\u2002",
    name: "ensp",
    entity: "&ensp;",
    decimal: 8194,
    hex: "2002",
    category: "spacing",
    description: "En space",
  },
  {
    char: "\u2009",
    name: "thinsp",
    entity: "&thinsp;",
    decimal: 8201,
    hex: "2009",
    category: "spacing",
    description: "Thin space",
  },
];

export function getCharsByCategory(category: HTMLCharCategory): HTMLCharEntity[] {
  return HTML_CHAR_ENTITIES.filter((e) => e.category === category);
}

export function searchChars(query: string): HTMLCharEntity[] {
  const q = query.toLowerCase();
  return HTML_CHAR_ENTITIES.filter(
    (e) =>
      e.char.toLowerCase().includes(q) ||
      e.name.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.entity.toLowerCase().includes(q)
  );
}
